// Code generated by mockery. DO NOT EDIT.
// template: github.com/FuturFusion/operations-center/internal/util/logger/slog.gotmpl

package middleware

import (
	"context"
	"io"
	"log/slog"

	"github.com/FuturFusion/operations-center/internal/image"
	"github.com/FuturFusion/operations-center/internal/util/logger"
)

// SimplestreamsPortWithSlog implements image.SimplestreamsPort that is instrumented with slog logger.
type SimplestreamsPortWithSlog struct {
	_base                 image.SimplestreamsPort
	_isInformativeErrFunc func(error) bool
}

type SimplestreamsPortWithSlogOption func(s *SimplestreamsPortWithSlog)

func SimplestreamsPortWithSlogWithInformativeErrFunc(isInformativeErrFunc func(error) bool) SimplestreamsPortWithSlogOption {
	return func(_base *SimplestreamsPortWithSlog) {
		_base._isInformativeErrFunc = isInformativeErrFunc
	}
}

// NewSimplestreamsPortWithSlog instruments an implementation of the image.SimplestreamsPort with simple logging.
func NewSimplestreamsPortWithSlog(base image.SimplestreamsPort, opts ...SimplestreamsPortWithSlogOption) SimplestreamsPortWithSlog {
	this := SimplestreamsPortWithSlog{
		_base:                 base,
		_isInformativeErrFunc: func(error) bool { return false },
	}

	for _, opt := range opts {
		opt(&this)
	}

	return this
}

// GetFile implements image.SimplestreamsPort.
func (_d SimplestreamsPortWithSlog) GetFile(ctx context.Context, source image.IncusImageSource, path string) (readCloser io.ReadCloser, err error) {
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.Any("source", source),
			slog.String("path", path),
		)
	}
	log.DebugContext(ctx, "=> calling GetFile")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("readCloser", readCloser),
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			if _d._isInformativeErrFunc(err) {
				log.DebugContext(ctx, "<= method GetFile returned an informative error")
			} else {
				log.ErrorContext(ctx, "<= method GetFile returned an error")
			}
		} else {
			log.DebugContext(ctx, "<= method GetFile finished")
		}
	}()
	return _d._base.GetFile(ctx, source, path)
}

// GetImageList implements image.SimplestreamsPort.
func (_d SimplestreamsPortWithSlog) GetImageList(ctx context.Context, source image.IncusImageSource) (incusImages image.IncusImages, err error) {
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.Any("source", source),
		)
	}
	log.DebugContext(ctx, "=> calling GetImageList")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("incusImages", incusImages),
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			if _d._isInformativeErrFunc(err) {
				log.DebugContext(ctx, "<= method GetImageList returned an informative error")
			} else {
				log.ErrorContext(ctx, "<= method GetImageList returned an error")
			}
		} else {
			log.DebugContext(ctx, "<= method GetImageList finished")
		}
	}()
	return _d._base.GetImageList(ctx, source)
}
