// Code generated by generate-inventory; DO NOT EDIT.

import { StoragePool } from "types/storage_pool";
import { processResponse } from "util/response";

export const fetchStoragePools = (
  filter: string,
): Promise<StoragePool[]> => {
  let url = "/1.0/inventory/storage_pools?recursion=1";
  if (filter) {
    url += `&filter=${filter}`;
  }

  return new Promise((resolve, reject) => {
    fetch(url)
      .then(processResponse)
      .then((data) => resolve(data.metadata))
      .catch(reject);
  });
};
