---

all: False
# Workaround for https://github.com/vektra/mockery/issues/1041, remove when issue is resolved.
# template: matryer
template: file://./internal/mock/matryer_moq.gotmpl
require-template-schema-exists: false
force-file-write: true
include-interface-regex: "(.+Repo|.+Port|.*ServerClient|ClusterService|ServerService|TokenService|InventorySyncer)"
dir: >-
  {{- $targetDir := "mock" -}}
  {{- if and (.InterfaceName | hasSuffix "ServerClient") -}}
  {{- $targetDir = "server/mock" -}}
  {{- end -}}
  {{- if .InterfaceName | hasSuffix "Repo" -}}
  {{- $targetDir = "repo/mock" -}}
  {{- end -}}
  {{- if .InterfaceName | hasSuffix "Port" -}}
  {{- $targetDir = "adapter/mock" -}}
  {{- end -}}
  {{- .InterfaceDir -}}/{{- $targetDir -}}
filename: "{{ .InterfaceName | snakecase }}_mock_gen.go"
structname: "{{ .InterfaceName }}Mock"
pkgname: mock
packages:
  github.com/FuturFusion/operations-center/internal/inventory:
  github.com/FuturFusion/operations-center/internal/provisioning:
