// Code generated by mockery. DO NOT EDIT.
// template: github.com/FuturFusion/operations-center/internal/metrics/prometheus.gotmpl

package middleware

import (
	"context"
	"time"

	"github.com/prometheus/client_golang/prometheus"
	"github.com/prometheus/client_golang/prometheus/promauto"

	"github.com/FuturFusion/operations-center/internal/provisioning"
)

// TokenClientPortWithPrometheus implements provisioning.TokenClientPort interface with all methods wrapped
// with Prometheus metrics.
type TokenClientPortWithPrometheus struct {
	base         provisioning.TokenClientPort
	instanceName string
}

var tokenClientPortDurationSummaryVec = promauto.NewSummaryVec(
	prometheus.SummaryOpts{
		Name:       "token_client_port_duration_seconds",
		Help:       "tokenClientPort runtime duration and result",
		MaxAge:     time.Minute,
		Objectives: map[float64]float64{0.5: 0.05, 0.9: 0.01, 0.99: 0.001},
	},
	[]string{"instance_name", "method", "result"},
)

// NewTokenClientPortWithPrometheus returns an instance of the provisioning.TokenClientPort decorated with prometheus summary metric.
func NewTokenClientPortWithPrometheus(base provisioning.TokenClientPort, instanceName string) TokenClientPortWithPrometheus {
	return TokenClientPortWithPrometheus{
		base:         base,
		instanceName: instanceName,
	}
}

// GetSecurityConfig implements provisioning.TokenClientPort.
func (_d TokenClientPortWithPrometheus) GetSecurityConfig(ctx context.Context, server provisioning.Server) (v provisioning.ServerSystemSecurity, err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		tokenClientPortDurationSummaryVec.WithLabelValues(_d.instanceName, "GetSecurityConfig", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.GetSecurityConfig(ctx, server)
}
