// Code generated by mockery. DO NOT EDIT.
// template: github.com/FuturFusion/operations-center/internal/util/logger/slog.gotmpl

package middleware

import (
	"context"

	"github.com/FuturFusion/operations-center/internal/inventory"
	"github.com/FuturFusion/operations-center/internal/provisioning"
	"github.com/lxc/incus/v6/shared/api"
)

// NetworkZoneServerClientWithErrorWrapper implements inventory.NetworkZoneServerClient that wraps errors based custom logic.
type NetworkZoneServerClientWithErrorWrapper struct {
	_base        inventory.NetworkZoneServerClient
	_wrapErrFunc func(error) error
}

// NewNetworkZoneServerClientWithErrorWrapper instruments an implementation of the inventory.NetworkZoneServerClient with error wrapping.
func NewNetworkZoneServerClientWithErrorWrapper(base inventory.NetworkZoneServerClient, wrapErrFunc func(error) error) NetworkZoneServerClientWithErrorWrapper {
	this := NetworkZoneServerClientWithErrorWrapper{
		_base:        base,
		_wrapErrFunc: wrapErrFunc,
	}

	return this
}

// GetNetworkZoneByName implements inventory.NetworkZoneServerClient.
func (_d NetworkZoneServerClientWithErrorWrapper) GetNetworkZoneByName(ctx context.Context, endpoint provisioning.Endpoint, projectName string, networkZoneName string) (networkZone api.NetworkZone, err error) {
	defer func() {
		if err != nil {
			err = _d._wrapErrFunc(err)
		}
	}()
	return _d._base.GetNetworkZoneByName(ctx, endpoint, projectName, networkZoneName)
}

// GetNetworkZones implements inventory.NetworkZoneServerClient.
func (_d NetworkZoneServerClientWithErrorWrapper) GetNetworkZones(ctx context.Context, endpoint provisioning.Endpoint) (networkZones []api.NetworkZone, err error) {
	defer func() {
		if err != nil {
			err = _d._wrapErrFunc(err)
		}
	}()
	return _d._base.GetNetworkZones(ctx, endpoint)
}
