// Code generated by mockery. DO NOT EDIT.
// template: github.com/FuturFusion/operations-center/internal/metrics/prometheus.gotmpl

package middleware

import (
	"context"
	"time"

	"github.com/FuturFusion/operations-center/internal/inventory"
	"github.com/FuturFusion/operations-center/internal/provisioning"
	"github.com/lxc/incus/v6/shared/api"
	"github.com/prometheus/client_golang/prometheus"
	"github.com/prometheus/client_golang/prometheus/promauto"
)

// NetworkServerClientWithPrometheus implements inventory.NetworkServerClient interface with all methods wrapped
// with Prometheus metrics.
type NetworkServerClientWithPrometheus struct {
	base         inventory.NetworkServerClient
	instanceName string
}

var networkServerClientDurationSummaryVec = promauto.NewSummaryVec(
	prometheus.SummaryOpts{
		Name:       "network_server_client_duration_seconds",
		Help:       "networkServerClient runtime duration and result",
		MaxAge:     time.Minute,
		Objectives: map[float64]float64{0.5: 0.05, 0.9: 0.01, 0.99: 0.001},
	},
	[]string{"instance_name", "method", "result"},
)

// NewNetworkServerClientWithPrometheus returns an instance of the inventory.NetworkServerClient decorated with prometheus summary metric.
func NewNetworkServerClientWithPrometheus(base inventory.NetworkServerClient, instanceName string) NetworkServerClientWithPrometheus {
	return NetworkServerClientWithPrometheus{
		base:         base,
		instanceName: instanceName,
	}
}

// GetNetworkByName implements inventory.NetworkServerClient.
func (_d NetworkServerClientWithPrometheus) GetNetworkByName(ctx context.Context, endpoint provisioning.Endpoint, networkName string) (network api.Network, err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		networkServerClientDurationSummaryVec.WithLabelValues(_d.instanceName, "GetNetworkByName", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.GetNetworkByName(ctx, endpoint, networkName)
}

// GetNetworks implements inventory.NetworkServerClient.
func (_d NetworkServerClientWithPrometheus) GetNetworks(ctx context.Context, endpoint provisioning.Endpoint) (networks []api.Network, err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		networkServerClientDurationSummaryVec.WithLabelValues(_d.instanceName, "GetNetworks", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.GetNetworks(ctx, endpoint)
}
