// Code generated by mockery. DO NOT EDIT.
// template: github.com/FuturFusion/operations-center/internal/util/logger/slog.gotmpl

package middleware

import (
	"context"

	"github.com/FuturFusion/operations-center/internal/inventory"
	"github.com/FuturFusion/operations-center/internal/provisioning"
	"github.com/lxc/incus/v6/shared/api"
)

// NetworkIntegrationServerClientWithErrorWrapper implements inventory.NetworkIntegrationServerClient that wraps errors based custom logic.
type NetworkIntegrationServerClientWithErrorWrapper struct {
	_base        inventory.NetworkIntegrationServerClient
	_wrapErrFunc func(error) error
}

// NewNetworkIntegrationServerClientWithErrorWrapper instruments an implementation of the inventory.NetworkIntegrationServerClient with error wrapping.
func NewNetworkIntegrationServerClientWithErrorWrapper(base inventory.NetworkIntegrationServerClient, wrapErrFunc func(error) error) NetworkIntegrationServerClientWithErrorWrapper {
	this := NetworkIntegrationServerClientWithErrorWrapper{
		_base:        base,
		_wrapErrFunc: wrapErrFunc,
	}

	return this
}

// GetNetworkIntegrationByName implements inventory.NetworkIntegrationServerClient.
func (_d NetworkIntegrationServerClientWithErrorWrapper) GetNetworkIntegrationByName(ctx context.Context, endpoint provisioning.Endpoint, networkIntegrationName string) (networkIntegration api.NetworkIntegration, err error) {
	defer func() {
		if err != nil {
			err = _d._wrapErrFunc(err)
		}
	}()
	return _d._base.GetNetworkIntegrationByName(ctx, endpoint, networkIntegrationName)
}

// GetNetworkIntegrations implements inventory.NetworkIntegrationServerClient.
func (_d NetworkIntegrationServerClientWithErrorWrapper) GetNetworkIntegrations(ctx context.Context, endpoint provisioning.Endpoint) (networkIntegrations []api.NetworkIntegration, err error) {
	defer func() {
		if err != nil {
			err = _d._wrapErrFunc(err)
		}
	}()
	return _d._base.GetNetworkIntegrations(ctx, endpoint)
}
