// Code generated by mockery. DO NOT EDIT.
// template: github.com/FuturFusion/operations-center/internal/logger/slog.gotmpl

package middleware

import (
	"context"
	"log/slog"

	"github.com/FuturFusion/operations-center/internal/inventory"
	"github.com/FuturFusion/operations-center/internal/logger"
	"github.com/FuturFusion/operations-center/internal/provisioning"
	"github.com/lxc/incus/v6/shared/api"
)

// StoragePoolServerClientWithSlog implements inventory.StoragePoolServerClient that is instrumented with slog logger.
type StoragePoolServerClientWithSlog struct {
	_base                 inventory.StoragePoolServerClient
	_isInformativeErrFunc func(error) bool
}

type StoragePoolServerClientWithSlogOption func(s *StoragePoolServerClientWithSlog)

func StoragePoolServerClientWithSlogWithInformativeErrFunc(isInformativeErrFunc func(error) bool) StoragePoolServerClientWithSlogOption {
	return func(_base *StoragePoolServerClientWithSlog) {
		_base._isInformativeErrFunc = isInformativeErrFunc
	}
}

// NewStoragePoolServerClientWithSlog instruments an implementation of the inventory.StoragePoolServerClient with simple logging.
func NewStoragePoolServerClientWithSlog(base inventory.StoragePoolServerClient, opts ...StoragePoolServerClientWithSlogOption) StoragePoolServerClientWithSlog {
	this := StoragePoolServerClientWithSlog{
		_base:                 base,
		_isInformativeErrFunc: func(error) bool { return false },
	}

	for _, opt := range opts {
		opt(&this)
	}

	return this
}

// GetStoragePoolByName implements inventory.StoragePoolServerClient.
func (_d StoragePoolServerClientWithSlog) GetStoragePoolByName(ctx context.Context, endpoint provisioning.Endpoint, storagePoolName string) (storagePool api.StoragePool, err error) {
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.Any("endpoint", endpoint),
			slog.String("storagePoolName", storagePoolName),
		)
	}
	log.DebugContext(ctx, "=> calling GetStoragePoolByName")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("storagePool", storagePool),
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			if _d._isInformativeErrFunc(err) {
				log.DebugContext(ctx, "<= method GetStoragePoolByName returned an informative error")
			} else {
				log.ErrorContext(ctx, "<= method GetStoragePoolByName returned an error")
			}
		} else {
			log.DebugContext(ctx, "<= method GetStoragePoolByName finished")
		}
	}()
	return _d._base.GetStoragePoolByName(ctx, endpoint, storagePoolName)
}

// GetStoragePools implements inventory.StoragePoolServerClient.
func (_d StoragePoolServerClientWithSlog) GetStoragePools(ctx context.Context, endpoint provisioning.Endpoint) (storagePools []api.StoragePool, err error) {
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.Any("endpoint", endpoint),
		)
	}
	log.DebugContext(ctx, "=> calling GetStoragePools")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("storagePools", storagePools),
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			if _d._isInformativeErrFunc(err) {
				log.DebugContext(ctx, "<= method GetStoragePools returned an informative error")
			} else {
				log.ErrorContext(ctx, "<= method GetStoragePools returned an error")
			}
		} else {
			log.DebugContext(ctx, "<= method GetStoragePools finished")
		}
	}()
	return _d._base.GetStoragePools(ctx, endpoint)
}
