// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package mock

import (
	"context"
	"sync"

	"github.com/FuturFusion/operations-center/internal/inventory"
	"github.com/google/uuid"
)

// Ensure that ProfileRepoMock does implement inventory.ProfileRepo.
// If this is not the case, regenerate this file with mockery.
var _ inventory.ProfileRepo = &ProfileRepoMock{}

// ProfileRepoMock is a mock implementation of inventory.ProfileRepo.
//
//	func TestSomethingThatUsesProfileRepo(t *testing.T) {
//
//		// make and configure a mocked inventory.ProfileRepo
//		mockedProfileRepo := &ProfileRepoMock{
//			CreateFunc: func(ctx context.Context, profile inventory.Profile) (inventory.Profile, error) {
//				panic("mock out the Create method")
//			},
//			DeleteByClusterNameFunc: func(ctx context.Context, cluster string) error {
//				panic("mock out the DeleteByClusterName method")
//			},
//			DeleteByUUIDFunc: func(ctx context.Context, id uuid.UUID) error {
//				panic("mock out the DeleteByUUID method")
//			},
//			GetAllUUIDsWithFilterFunc: func(ctx context.Context, filter inventory.ProfileFilter) ([]uuid.UUID, error) {
//				panic("mock out the GetAllUUIDsWithFilter method")
//			},
//			GetAllWithFilterFunc: func(ctx context.Context, filter inventory.ProfileFilter) (inventory.Profiles, error) {
//				panic("mock out the GetAllWithFilter method")
//			},
//			GetByUUIDFunc: func(ctx context.Context, id uuid.UUID) (inventory.Profile, error) {
//				panic("mock out the GetByUUID method")
//			},
//			UpdateByUUIDFunc: func(ctx context.Context, profile inventory.Profile) (inventory.Profile, error) {
//				panic("mock out the UpdateByUUID method")
//			},
//		}
//
//		// use mockedProfileRepo in code that requires inventory.ProfileRepo
//		// and then make assertions.
//
//	}
type ProfileRepoMock struct {
	// CreateFunc mocks the Create method.
	CreateFunc func(ctx context.Context, profile inventory.Profile) (inventory.Profile, error)

	// DeleteByClusterNameFunc mocks the DeleteByClusterName method.
	DeleteByClusterNameFunc func(ctx context.Context, cluster string) error

	// DeleteByUUIDFunc mocks the DeleteByUUID method.
	DeleteByUUIDFunc func(ctx context.Context, id uuid.UUID) error

	// GetAllUUIDsWithFilterFunc mocks the GetAllUUIDsWithFilter method.
	GetAllUUIDsWithFilterFunc func(ctx context.Context, filter inventory.ProfileFilter) ([]uuid.UUID, error)

	// GetAllWithFilterFunc mocks the GetAllWithFilter method.
	GetAllWithFilterFunc func(ctx context.Context, filter inventory.ProfileFilter) (inventory.Profiles, error)

	// GetByUUIDFunc mocks the GetByUUID method.
	GetByUUIDFunc func(ctx context.Context, id uuid.UUID) (inventory.Profile, error)

	// UpdateByUUIDFunc mocks the UpdateByUUID method.
	UpdateByUUIDFunc func(ctx context.Context, profile inventory.Profile) (inventory.Profile, error)

	// calls tracks calls to the methods.
	calls struct {
		// Create holds details about calls to the Create method.
		Create []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Profile is the profile argument value.
			Profile inventory.Profile
		}
		// DeleteByClusterName holds details about calls to the DeleteByClusterName method.
		DeleteByClusterName []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Cluster is the cluster argument value.
			Cluster string
		}
		// DeleteByUUID holds details about calls to the DeleteByUUID method.
		DeleteByUUID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID uuid.UUID
		}
		// GetAllUUIDsWithFilter holds details about calls to the GetAllUUIDsWithFilter method.
		GetAllUUIDsWithFilter []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Filter is the filter argument value.
			Filter inventory.ProfileFilter
		}
		// GetAllWithFilter holds details about calls to the GetAllWithFilter method.
		GetAllWithFilter []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Filter is the filter argument value.
			Filter inventory.ProfileFilter
		}
		// GetByUUID holds details about calls to the GetByUUID method.
		GetByUUID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID uuid.UUID
		}
		// UpdateByUUID holds details about calls to the UpdateByUUID method.
		UpdateByUUID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Profile is the profile argument value.
			Profile inventory.Profile
		}
	}
	lockCreate                sync.RWMutex
	lockDeleteByClusterName   sync.RWMutex
	lockDeleteByUUID          sync.RWMutex
	lockGetAllUUIDsWithFilter sync.RWMutex
	lockGetAllWithFilter      sync.RWMutex
	lockGetByUUID             sync.RWMutex
	lockUpdateByUUID          sync.RWMutex
}

// Create calls CreateFunc.
func (mock *ProfileRepoMock) Create(ctx context.Context, profile inventory.Profile) (inventory.Profile, error) {
	if mock.CreateFunc == nil {
		panic("ProfileRepoMock.CreateFunc: method is nil but ProfileRepo.Create was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Profile inventory.Profile
	}{
		Ctx:     ctx,
		Profile: profile,
	}
	mock.lockCreate.Lock()
	mock.calls.Create = append(mock.calls.Create, callInfo)
	mock.lockCreate.Unlock()
	return mock.CreateFunc(ctx, profile)
}

// CreateCalls gets all the calls that were made to Create.
// Check the length with:
//
//	len(mockedProfileRepo.CreateCalls())
func (mock *ProfileRepoMock) CreateCalls() []struct {
	Ctx     context.Context
	Profile inventory.Profile
} {
	var calls []struct {
		Ctx     context.Context
		Profile inventory.Profile
	}
	mock.lockCreate.RLock()
	calls = mock.calls.Create
	mock.lockCreate.RUnlock()
	return calls
}

// DeleteByClusterName calls DeleteByClusterNameFunc.
func (mock *ProfileRepoMock) DeleteByClusterName(ctx context.Context, cluster string) error {
	if mock.DeleteByClusterNameFunc == nil {
		panic("ProfileRepoMock.DeleteByClusterNameFunc: method is nil but ProfileRepo.DeleteByClusterName was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Cluster string
	}{
		Ctx:     ctx,
		Cluster: cluster,
	}
	mock.lockDeleteByClusterName.Lock()
	mock.calls.DeleteByClusterName = append(mock.calls.DeleteByClusterName, callInfo)
	mock.lockDeleteByClusterName.Unlock()
	return mock.DeleteByClusterNameFunc(ctx, cluster)
}

// DeleteByClusterNameCalls gets all the calls that were made to DeleteByClusterName.
// Check the length with:
//
//	len(mockedProfileRepo.DeleteByClusterNameCalls())
func (mock *ProfileRepoMock) DeleteByClusterNameCalls() []struct {
	Ctx     context.Context
	Cluster string
} {
	var calls []struct {
		Ctx     context.Context
		Cluster string
	}
	mock.lockDeleteByClusterName.RLock()
	calls = mock.calls.DeleteByClusterName
	mock.lockDeleteByClusterName.RUnlock()
	return calls
}

// DeleteByUUID calls DeleteByUUIDFunc.
func (mock *ProfileRepoMock) DeleteByUUID(ctx context.Context, id uuid.UUID) error {
	if mock.DeleteByUUIDFunc == nil {
		panic("ProfileRepoMock.DeleteByUUIDFunc: method is nil but ProfileRepo.DeleteByUUID was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  uuid.UUID
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockDeleteByUUID.Lock()
	mock.calls.DeleteByUUID = append(mock.calls.DeleteByUUID, callInfo)
	mock.lockDeleteByUUID.Unlock()
	return mock.DeleteByUUIDFunc(ctx, id)
}

// DeleteByUUIDCalls gets all the calls that were made to DeleteByUUID.
// Check the length with:
//
//	len(mockedProfileRepo.DeleteByUUIDCalls())
func (mock *ProfileRepoMock) DeleteByUUIDCalls() []struct {
	Ctx context.Context
	ID  uuid.UUID
} {
	var calls []struct {
		Ctx context.Context
		ID  uuid.UUID
	}
	mock.lockDeleteByUUID.RLock()
	calls = mock.calls.DeleteByUUID
	mock.lockDeleteByUUID.RUnlock()
	return calls
}

// GetAllUUIDsWithFilter calls GetAllUUIDsWithFilterFunc.
func (mock *ProfileRepoMock) GetAllUUIDsWithFilter(ctx context.Context, filter inventory.ProfileFilter) ([]uuid.UUID, error) {
	if mock.GetAllUUIDsWithFilterFunc == nil {
		panic("ProfileRepoMock.GetAllUUIDsWithFilterFunc: method is nil but ProfileRepo.GetAllUUIDsWithFilter was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Filter inventory.ProfileFilter
	}{
		Ctx:    ctx,
		Filter: filter,
	}
	mock.lockGetAllUUIDsWithFilter.Lock()
	mock.calls.GetAllUUIDsWithFilter = append(mock.calls.GetAllUUIDsWithFilter, callInfo)
	mock.lockGetAllUUIDsWithFilter.Unlock()
	return mock.GetAllUUIDsWithFilterFunc(ctx, filter)
}

// GetAllUUIDsWithFilterCalls gets all the calls that were made to GetAllUUIDsWithFilter.
// Check the length with:
//
//	len(mockedProfileRepo.GetAllUUIDsWithFilterCalls())
func (mock *ProfileRepoMock) GetAllUUIDsWithFilterCalls() []struct {
	Ctx    context.Context
	Filter inventory.ProfileFilter
} {
	var calls []struct {
		Ctx    context.Context
		Filter inventory.ProfileFilter
	}
	mock.lockGetAllUUIDsWithFilter.RLock()
	calls = mock.calls.GetAllUUIDsWithFilter
	mock.lockGetAllUUIDsWithFilter.RUnlock()
	return calls
}

// GetAllWithFilter calls GetAllWithFilterFunc.
func (mock *ProfileRepoMock) GetAllWithFilter(ctx context.Context, filter inventory.ProfileFilter) (inventory.Profiles, error) {
	if mock.GetAllWithFilterFunc == nil {
		panic("ProfileRepoMock.GetAllWithFilterFunc: method is nil but ProfileRepo.GetAllWithFilter was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Filter inventory.ProfileFilter
	}{
		Ctx:    ctx,
		Filter: filter,
	}
	mock.lockGetAllWithFilter.Lock()
	mock.calls.GetAllWithFilter = append(mock.calls.GetAllWithFilter, callInfo)
	mock.lockGetAllWithFilter.Unlock()
	return mock.GetAllWithFilterFunc(ctx, filter)
}

// GetAllWithFilterCalls gets all the calls that were made to GetAllWithFilter.
// Check the length with:
//
//	len(mockedProfileRepo.GetAllWithFilterCalls())
func (mock *ProfileRepoMock) GetAllWithFilterCalls() []struct {
	Ctx    context.Context
	Filter inventory.ProfileFilter
} {
	var calls []struct {
		Ctx    context.Context
		Filter inventory.ProfileFilter
	}
	mock.lockGetAllWithFilter.RLock()
	calls = mock.calls.GetAllWithFilter
	mock.lockGetAllWithFilter.RUnlock()
	return calls
}

// GetByUUID calls GetByUUIDFunc.
func (mock *ProfileRepoMock) GetByUUID(ctx context.Context, id uuid.UUID) (inventory.Profile, error) {
	if mock.GetByUUIDFunc == nil {
		panic("ProfileRepoMock.GetByUUIDFunc: method is nil but ProfileRepo.GetByUUID was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  uuid.UUID
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockGetByUUID.Lock()
	mock.calls.GetByUUID = append(mock.calls.GetByUUID, callInfo)
	mock.lockGetByUUID.Unlock()
	return mock.GetByUUIDFunc(ctx, id)
}

// GetByUUIDCalls gets all the calls that were made to GetByUUID.
// Check the length with:
//
//	len(mockedProfileRepo.GetByUUIDCalls())
func (mock *ProfileRepoMock) GetByUUIDCalls() []struct {
	Ctx context.Context
	ID  uuid.UUID
} {
	var calls []struct {
		Ctx context.Context
		ID  uuid.UUID
	}
	mock.lockGetByUUID.RLock()
	calls = mock.calls.GetByUUID
	mock.lockGetByUUID.RUnlock()
	return calls
}

// UpdateByUUID calls UpdateByUUIDFunc.
func (mock *ProfileRepoMock) UpdateByUUID(ctx context.Context, profile inventory.Profile) (inventory.Profile, error) {
	if mock.UpdateByUUIDFunc == nil {
		panic("ProfileRepoMock.UpdateByUUIDFunc: method is nil but ProfileRepo.UpdateByUUID was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Profile inventory.Profile
	}{
		Ctx:     ctx,
		Profile: profile,
	}
	mock.lockUpdateByUUID.Lock()
	mock.calls.UpdateByUUID = append(mock.calls.UpdateByUUID, callInfo)
	mock.lockUpdateByUUID.Unlock()
	return mock.UpdateByUUIDFunc(ctx, profile)
}

// UpdateByUUIDCalls gets all the calls that were made to UpdateByUUID.
// Check the length with:
//
//	len(mockedProfileRepo.UpdateByUUIDCalls())
func (mock *ProfileRepoMock) UpdateByUUIDCalls() []struct {
	Ctx     context.Context
	Profile inventory.Profile
} {
	var calls []struct {
		Ctx     context.Context
		Profile inventory.Profile
	}
	mock.lockUpdateByUUID.RLock()
	calls = mock.calls.UpdateByUUID
	mock.lockUpdateByUUID.RUnlock()
	return calls
}
