// Code generated by mockery. DO NOT EDIT.
// template: github.com/FuturFusion/operations-center/internal/logger/slog.gotmpl

package middleware

import (
	"context"
	"log/slog"

	"github.com/FuturFusion/operations-center/internal/inventory"
	"github.com/FuturFusion/operations-center/internal/logger"
	"github.com/google/uuid"
)

// ImageServiceWithSlog implements inventory.ImageService that is instrumented with slog logger.
type ImageServiceWithSlog struct {
	_log                  *slog.Logger
	_base                 inventory.ImageService
	_isInformativeErrFunc func(error) bool
}

type ImageServiceWithSlogOption func(s *ImageServiceWithSlog)

func ImageServiceWithSlogWithInformativeErrFunc(isInformativeErrFunc func(error) bool) ImageServiceWithSlogOption {
	return func(_base *ImageServiceWithSlog) {
		_base._isInformativeErrFunc = isInformativeErrFunc
	}
}

// NewImageServiceWithSlog instruments an implementation of the inventory.ImageService with simple logging.
func NewImageServiceWithSlog(base inventory.ImageService, log *slog.Logger, opts ...ImageServiceWithSlogOption) ImageServiceWithSlog {
	this := ImageServiceWithSlog{
		_base:                 base,
		_log:                  log,
		_isInformativeErrFunc: func(error) bool { return false },
	}

	for _, opt := range opts {
		opt(&this)
	}

	return this
}

// GetAllUUIDsWithFilter implements inventory.ImageService.
func (_d ImageServiceWithSlog) GetAllUUIDsWithFilter(ctx context.Context, filter inventory.ImageFilter) (uUIDs []uuid.UUID, err error) {
	log := _d._log.With()
	if _d._log.Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.Any("filter", filter),
		)
	}
	log.DebugContext(ctx, "=> calling GetAllUUIDsWithFilter")
	defer func() {
		log := _d._log.With()
		if _d._log.Enabled(ctx, logger.LevelTrace) {
			log = _d._log.With(
				slog.Any("uUIDs", uUIDs),
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = _d._log.With("err", err)
			}
		}
		if err != nil {
			if _d._isInformativeErrFunc(err) {
				log.DebugContext(ctx, "<= method GetAllUUIDsWithFilter returned an informative error")
			} else {
				log.ErrorContext(ctx, "<= method GetAllUUIDsWithFilter returned an error")
			}
		} else {
			log.DebugContext(ctx, "<= method GetAllUUIDsWithFilter finished")
		}
	}()
	return _d._base.GetAllUUIDsWithFilter(ctx, filter)
}

// GetAllWithFilter implements inventory.ImageService.
func (_d ImageServiceWithSlog) GetAllWithFilter(ctx context.Context, filter inventory.ImageFilter) (images inventory.Images, err error) {
	log := _d._log.With()
	if _d._log.Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.Any("filter", filter),
		)
	}
	log.DebugContext(ctx, "=> calling GetAllWithFilter")
	defer func() {
		log := _d._log.With()
		if _d._log.Enabled(ctx, logger.LevelTrace) {
			log = _d._log.With(
				slog.Any("images", images),
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = _d._log.With("err", err)
			}
		}
		if err != nil {
			if _d._isInformativeErrFunc(err) {
				log.DebugContext(ctx, "<= method GetAllWithFilter returned an informative error")
			} else {
				log.ErrorContext(ctx, "<= method GetAllWithFilter returned an error")
			}
		} else {
			log.DebugContext(ctx, "<= method GetAllWithFilter finished")
		}
	}()
	return _d._base.GetAllWithFilter(ctx, filter)
}

// GetByUUID implements inventory.ImageService.
func (_d ImageServiceWithSlog) GetByUUID(ctx context.Context, id uuid.UUID) (image inventory.Image, err error) {
	log := _d._log.With()
	if _d._log.Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.Any("id", id),
		)
	}
	log.DebugContext(ctx, "=> calling GetByUUID")
	defer func() {
		log := _d._log.With()
		if _d._log.Enabled(ctx, logger.LevelTrace) {
			log = _d._log.With(
				slog.Any("image", image),
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = _d._log.With("err", err)
			}
		}
		if err != nil {
			if _d._isInformativeErrFunc(err) {
				log.DebugContext(ctx, "<= method GetByUUID returned an informative error")
			} else {
				log.ErrorContext(ctx, "<= method GetByUUID returned an error")
			}
		} else {
			log.DebugContext(ctx, "<= method GetByUUID finished")
		}
	}()
	return _d._base.GetByUUID(ctx, id)
}

// ResyncByUUID implements inventory.ImageService.
func (_d ImageServiceWithSlog) ResyncByUUID(ctx context.Context, id uuid.UUID) (err error) {
	log := _d._log.With()
	if _d._log.Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.Any("id", id),
		)
	}
	log.DebugContext(ctx, "=> calling ResyncByUUID")
	defer func() {
		log := _d._log.With()
		if _d._log.Enabled(ctx, logger.LevelTrace) {
			log = _d._log.With(
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = _d._log.With("err", err)
			}
		}
		if err != nil {
			if _d._isInformativeErrFunc(err) {
				log.DebugContext(ctx, "<= method ResyncByUUID returned an informative error")
			} else {
				log.ErrorContext(ctx, "<= method ResyncByUUID returned an error")
			}
		} else {
			log.DebugContext(ctx, "<= method ResyncByUUID finished")
		}
	}()
	return _d._base.ResyncByUUID(ctx, id)
}

// SyncCluster implements inventory.ImageService.
func (_d ImageServiceWithSlog) SyncCluster(ctx context.Context, cluster string) (err error) {
	log := _d._log.With()
	if _d._log.Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.String("cluster", cluster),
		)
	}
	log.DebugContext(ctx, "=> calling SyncCluster")
	defer func() {
		log := _d._log.With()
		if _d._log.Enabled(ctx, logger.LevelTrace) {
			log = _d._log.With(
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = _d._log.With("err", err)
			}
		}
		if err != nil {
			if _d._isInformativeErrFunc(err) {
				log.DebugContext(ctx, "<= method SyncCluster returned an informative error")
			} else {
				log.ErrorContext(ctx, "<= method SyncCluster returned an error")
			}
		} else {
			log.DebugContext(ctx, "<= method SyncCluster finished")
		}
	}()
	return _d._base.SyncCluster(ctx, cluster)
}
