// Code generated by mockery. DO NOT EDIT.
// template: github.com/FuturFusion/operations-center/internal/metrics/prometheus.gotmpl

package middleware

import (
	"context"
	"time"

	"github.com/FuturFusion/operations-center/internal/inventory"
	"github.com/prometheus/client_golang/prometheus"
	"github.com/prometheus/client_golang/prometheus/promauto"
)

// NetworkACLServiceWithPrometheus implements inventory.NetworkACLService interface with all methods wrapped
// with Prometheus metrics.
type NetworkACLServiceWithPrometheus struct {
	base         inventory.NetworkACLService
	instanceName string
}

var networkACLServiceDurationSummaryVec = promauto.NewSummaryVec(
	prometheus.SummaryOpts{
		Name:       "network_acl_service_duration_seconds",
		Help:       "networkACLService runtime duration and result",
		MaxAge:     time.Minute,
		Objectives: map[float64]float64{0.5: 0.05, 0.9: 0.01, 0.99: 0.001},
	},
	[]string{"instance_name", "method", "result"},
)

// NewNetworkACLServiceWithPrometheus returns an instance of the inventory.NetworkACLService decorated with prometheus summary metric.
func NewNetworkACLServiceWithPrometheus(base inventory.NetworkACLService, instanceName string) NetworkACLServiceWithPrometheus {
	return NetworkACLServiceWithPrometheus{
		base:         base,
		instanceName: instanceName,
	}
}

// GetAllIDsWithFilter implements inventory.NetworkACLService.
func (_d NetworkACLServiceWithPrometheus) GetAllIDsWithFilter(ctx context.Context, filter inventory.NetworkACLFilter) (ints []int, err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		networkACLServiceDurationSummaryVec.WithLabelValues(_d.instanceName, "GetAllIDsWithFilter", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.GetAllIDsWithFilter(ctx, filter)
}

// GetByID implements inventory.NetworkACLService.
func (_d NetworkACLServiceWithPrometheus) GetByID(ctx context.Context, id int) (networkACL inventory.NetworkACL, err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		networkACLServiceDurationSummaryVec.WithLabelValues(_d.instanceName, "GetByID", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.GetByID(ctx, id)
}

// ResyncByID implements inventory.NetworkACLService.
func (_d NetworkACLServiceWithPrometheus) ResyncByID(ctx context.Context, id int) (err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		networkACLServiceDurationSummaryVec.WithLabelValues(_d.instanceName, "ResyncByID", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.ResyncByID(ctx, id)
}

// SyncCluster implements inventory.NetworkACLService.
func (_d NetworkACLServiceWithPrometheus) SyncCluster(ctx context.Context, cluster string) (err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		networkACLServiceDurationSummaryVec.WithLabelValues(_d.instanceName, "SyncCluster", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.SyncCluster(ctx, cluster)
}
