// Code generated by mockery. DO NOT EDIT.
// template: github.com/FuturFusion/operations-center/internal/metrics/prometheus.gotmpl

package middleware

import (
	"context"
	"time"

	"github.com/FuturFusion/operations-center/internal/inventory"
	"github.com/prometheus/client_golang/prometheus"
	"github.com/prometheus/client_golang/prometheus/promauto"
)

// ProfileServiceWithPrometheus implements inventory.ProfileService interface with all methods wrapped
// with Prometheus metrics.
type ProfileServiceWithPrometheus struct {
	base         inventory.ProfileService
	instanceName string
}

var profileServiceDurationSummaryVec = promauto.NewSummaryVec(
	prometheus.SummaryOpts{
		Name:       "profile_service_duration_seconds",
		Help:       "profileService runtime duration and result",
		MaxAge:     time.Minute,
		Objectives: map[float64]float64{0.5: 0.05, 0.9: 0.01, 0.99: 0.001},
	},
	[]string{"instance_name", "method", "result"},
)

// NewProfileServiceWithPrometheus returns an instance of the inventory.ProfileService decorated with prometheus summary metric.
func NewProfileServiceWithPrometheus(base inventory.ProfileService, instanceName string) ProfileServiceWithPrometheus {
	return ProfileServiceWithPrometheus{
		base:         base,
		instanceName: instanceName,
	}
}

// GetAllIDsWithFilter implements inventory.ProfileService.
func (_d ProfileServiceWithPrometheus) GetAllIDsWithFilter(ctx context.Context, filter inventory.ProfileFilter) (ints []int, err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		profileServiceDurationSummaryVec.WithLabelValues(_d.instanceName, "GetAllIDsWithFilter", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.GetAllIDsWithFilter(ctx, filter)
}

// GetByID implements inventory.ProfileService.
func (_d ProfileServiceWithPrometheus) GetByID(ctx context.Context, id int) (profile inventory.Profile, err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		profileServiceDurationSummaryVec.WithLabelValues(_d.instanceName, "GetByID", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.GetByID(ctx, id)
}

// ResyncByID implements inventory.ProfileService.
func (_d ProfileServiceWithPrometheus) ResyncByID(ctx context.Context, id int) (err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		profileServiceDurationSummaryVec.WithLabelValues(_d.instanceName, "ResyncByID", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.ResyncByID(ctx, id)
}

// SyncCluster implements inventory.ProfileService.
func (_d ProfileServiceWithPrometheus) SyncCluster(ctx context.Context, cluster string) (err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		profileServiceDurationSummaryVec.WithLabelValues(_d.instanceName, "SyncCluster", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.SyncCluster(ctx, cluster)
}
