package api_test

import (
	"bytes"
	"context"
	"crypto/tls"
	"encoding/json"
	"io"
	"net"
	"net/http"
	"os"
	"path/filepath"
	"testing"
	"time"

	incustls "github.com/lxc/incus/v7/shared/tls"
	"github.com/stretchr/testify/require"

	"github.com/FuturFusion/operations-center/internal/api"
	config "github.com/FuturFusion/operations-center/internal/config/daemon"
	"github.com/FuturFusion/operations-center/internal/environment/mock"
	"github.com/FuturFusion/operations-center/internal/util/testing/certs"
	testingnet "github.com/FuturFusion/operations-center/internal/util/testing/net"
	"github.com/FuturFusion/operations-center/shared/api/system"
)

// Test GET and POST /1.0/system/certificate.
func TestSystemCertificate(t *testing.T) {
	// Setup daemon
	tmpDir := t.TempDir()

	ctx := context.Background()

	env := &mock.EnvironmentMock{
		IsIncusOSFunc: func() bool {
			return false
		},
		GetUnixSocketFunc: func() string {
			return filepath.Join(tmpDir, "unix.socket")
		},
		VarDirFunc: func() string {
			return tmpDir
		},
		CacheDirFunc: func() string {
			return tmpDir
		},
		UsrShareDirFunc: func() string {
			return tmpDir
		},
		GetTokenFunc: func(ctx context.Context) (string, error) {
			return "", nil
		},
	}

	config.InitTest(t, env, nil, config.InternalConfig{
		IsBackgroundTasksDisabled: true,
		SourcePollSkipFirst:       true,
	})
	err := config.UpdateNetwork(ctx, system.NetworkPut{
		OperationsCenterAddress: "https://127.0.0.1:17443",
		RestServerAddress:       testingnet.LocalhostIP(t) + ":17443",
	})
	require.NoError(t, err)

	d := api.NewDaemon(
		ctx,
		env,
	)

	err = d.Start(ctx)
	require.NoError(t, err)
	t.Cleanup(func() {
		err = d.Stop(context.Background())
		require.NoError(t, err)
	})

	// http client, used to get the server certificate.
	client := http.Client{
		Transport: &http.Transport{
			TLSClientConfig: &tls.Config{
				InsecureSkipVerify: true,
			},
		},
	}

	// unix socket client, bypass authentication and authorization.
	socketClient := &http.Client{
		Transport: &http.Transport{
			DialContext: func(_ context.Context, _, _ string) (net.Conn, error) {
				return net.Dial("unix", filepath.Join(tmpDir, "unix.socket"))
			},
		},
	}

	// Execute tests

	// 1. Get certificate auto generated by daemon during startup
	resp1, err := client.Get("https://localhost:17443")
	require.NoError(t, err)
	defer resp1.Body.Close()

	initialCertificateSerialNumber := resp1.TLS.PeerCertificates[0].SerialNumber.String()

	// 2. Update certificate with a certificate chain, consisting of the server
	// certificate followed by the intermediate CA certificate.
	_, intermediatePEM, leafPEM, keyPEM := certs.GenerateChain(t)
	certPEM := append(append([]byte{}, leafPEM...), intermediatePEM...)

	systemCertificatePost := system.CertificatePost{
		Certificate: string(certPEM),
		Key:         string(keyPEM),
	}

	cert, err := tls.X509KeyPair(certPEM, keyPEM)
	require.NoError(t, err)

	requestBody, err := json.Marshal(systemCertificatePost)
	require.NoError(t, err)

	req, err := http.NewRequest(http.MethodPost, "http://unix/1.0/system/certificate", bytes.NewBuffer(requestBody))

	resp2, err := socketClient.Do(req)
	require.NoError(t, err)
	defer resp2.Body.Close()

	body, err := io.ReadAll(resp2.Body)
	require.NoError(t, err)
	require.Contains(t, string(body), `"Success"`)

	// Update of server certificate is async, leave a little bit headroom for the server to update the certificate in the background.
	time.Sleep(10 * time.Millisecond)

	// 3. Get certificate after update
	resp3, err := client.Get("https://localhost:17443")
	require.NoError(t, err)
	defer resp3.Body.Close()

	updatedCertificateSerialNumber := resp3.TLS.PeerCertificates[0].SerialNumber.String()

	// 4. Get certificate through the API
	req, err = http.NewRequest(http.MethodGet, "http://unix/1.0/system/certificate", nil)
	require.NoError(t, err)

	resp4, err := socketClient.Do(req)
	require.NoError(t, err)
	defer resp4.Body.Close()

	body, err = io.ReadAll(resp4.Body)
	require.NoError(t, err)

	var certificateResponse struct {
		Metadata system.Certificate `json:"metadata"`
	}

	err = json.Unmarshal(body, &certificateResponse)
	require.NoError(t, err)

	// Assert results

	require.NotEqual(t, initialCertificateSerialNumber, updatedCertificateSerialNumber)
	require.Equal(t, cert.Leaf.SerialNumber.String(), updatedCertificateSerialNumber)
	require.Len(t, resp3.TLS.PeerCertificates, 2)

	require.Equal(t, string(certPEM), certificateResponse.Metadata.Certificate)
	require.Equal(t, incustls.CertFingerprint(cert.Leaf), certificateResponse.Metadata.Fingerprint)
	require.Equal(t, cert.Leaf.Subject.String(), certificateResponse.Metadata.Subject)
	require.Equal(t, cert.Leaf.NotAfter.UTC(), certificateResponse.Metadata.NotAfter.UTC())

	// The private key is never part of the response.
	require.NotContains(t, string(body), "PRIVATE KEY")
}

// Test POST /1.0/system/:clean-cache.
func TestSystemCleanCachePost(t *testing.T) {
	// Setup daemon
	varDir := t.TempDir()
	cacheDir := t.TempDir()

	ctx := context.Background()

	env := &mock.EnvironmentMock{
		IsIncusOSFunc: func() bool {
			return false
		},
		GetUnixSocketFunc: func() string {
			return filepath.Join(varDir, "unix.socket")
		},
		VarDirFunc: func() string {
			return varDir
		},
		CacheDirFunc: func() string {
			return cacheDir
		},
		UsrShareDirFunc: func() string {
			return varDir
		},
		GetTokenFunc: func(ctx context.Context) (string, error) {
			return "", nil
		},
	}

	config.InitTest(t, env, nil, config.InternalConfig{
		IsBackgroundTasksDisabled: true,
		SourcePollSkipFirst:       true,
	})
	err := config.UpdateNetwork(ctx, system.NetworkPut{
		OperationsCenterAddress: "https://127.0.0.1:17444",
		RestServerAddress:       testingnet.LocalhostIP(t) + ":17444",
	})
	require.NoError(t, err)

	d := api.NewDaemon(
		ctx,
		env,
	)

	err = d.Start(ctx)
	require.NoError(t, err)
	t.Cleanup(func() {
		err = d.Stop(context.Background())
		require.NoError(t, err)
	})

	socketClient := &http.Client{
		Transport: &http.Transport{
			DialContext: func(_ context.Context, _, _ string) (net.Conn, error) {
				return net.Dial("unix", filepath.Join(varDir, "unix.socket"))
			},
		},
	}

	// Populate the cache directory with some leftover data.
	err = os.MkdirAll(filepath.Join(cacheDir, "seed-images"), 0o700)
	require.NoError(t, err)

	err = os.WriteFile(filepath.Join(cacheDir, "seed-images", "leftover.img"), []byte(`leftover`), 0o600)
	require.NoError(t, err)

	// The ACME account below the cache dir can not be regenerated.
	err = os.MkdirAll(filepath.Join(cacheDir, "acme", "accounts"), 0o700)
	require.NoError(t, err)

	err = os.WriteFile(filepath.Join(cacheDir, "acme", "accounts", "key.pem"), []byte(`account key`), 0o600)
	require.NoError(t, err)

	// Execute test
	req, err := http.NewRequest(http.MethodPost, "http://unix/1.0/system/:clean-cache", nil)
	require.NoError(t, err)

	resp, err := socketClient.Do(req)
	require.NoError(t, err)
	defer resp.Body.Close()

	body, err := io.ReadAll(resp.Body)
	require.NoError(t, err)
	require.Contains(t, string(body), `"Success"`)

	// Assert results
	entries, err := os.ReadDir(filepath.Join(cacheDir, "seed-images"))
	require.NoError(t, err)
	require.Empty(t, entries)

	require.FileExists(t, filepath.Join(cacheDir, "acme", "accounts", "key.pem"))
}
