// Code generated by generate-inventory; DO NOT EDIT.

package api

import (
	"fmt"
	"net/http"
	"strconv"

	"github.com/google/uuid"

	"github.com/FuturFusion/operations-center/internal/inventory"
	"github.com/FuturFusion/operations-center/internal/security/authz"
	"github.com/FuturFusion/operations-center/internal/util/response"
	"github.com/FuturFusion/operations-center/shared/api"
)

type networkLoadBalancerHandler struct {
	service inventory.NetworkLoadBalancerService
}

func registerInventoryNetworkLoadBalancerHandler(router Router, authorizer *authz.Authorizer, service inventory.NetworkLoadBalancerService) {
	handler := &networkLoadBalancerHandler{
		service: service,
	}

	router.HandleFunc("GET /{$}", response.With(handler.networkLoadBalancersGet, assertPermission(authorizer, authz.ObjectTypeServer, authz.EntitlementCanView)))
	router.HandleFunc("GET /{uuid}", response.With(handler.networkLoadBalancerGet, assertPermission(authorizer, authz.ObjectTypeServer, authz.EntitlementCanView)))
	router.HandleFunc("POST /{uuid}/:resync", response.With(handler.networkLoadBalancerResyncPost, assertPermission(authorizer, authz.ObjectTypeServer, authz.EntitlementCanEdit)))
}

// swagger:operation GET /1.0/inventory/network_load_balancers network_load_balancers network_load_balancers_get
//
//	Get the network load balancers
//
//	Returns a list of network load balancers (URLs).
//
//	---
//	produces:
//	  - application/json
//	parameters:
//	  - in: query
//	    name: cluster
//	    description: Cluster name
//	    type: string
//	    x-example: cluster
//	  - in: query
//	    name: project
//	    description: Project name
//	    type: string
//	    x-example: default
//	  - in: query
//	    name: filter
//	    description: Filter expression
//	    type: string
//	    x-example: name == "value"
//	responses:
//	  "200":
//	    $ref: "#/responses/URLsResponse"
//	  "403":
//	    $ref: "#/responses/Forbidden"
//	  "500":
//	    $ref: "#/responses/InternalServerError"

// swagger:operation GET /1.0/inventory/network_load_balancers?recursion=1 network_load_balancers network_load_balancers_get_recursion
//
//	Get the network load balancers
//
//	Returns a list of network load balancers (structs).
//
//	---
//	produces:
//	  - application/json
//	parameters:
//	  - in: query
//	    name: cluster
//	    description: Cluster name
//	    type: string
//	    x-example: cluster
//	  - in: query
//	    name: project
//	    description: Project name
//	    type: string
//	    x-example: default
//	  - in: query
//	    name: filter
//	    description: Filter expression
//	    type: string
//	    x-example: name == "value"
//	responses:
//	  "200":
//	    $ref: "#/responses/NetworkLoadBalancersResponse"
//	  "403":
//	    $ref: "#/responses/Forbidden"
//	  "500":
//	    $ref: "#/responses/InternalServerError"
func (i *networkLoadBalancerHandler) networkLoadBalancersGet(r *http.Request) response.Response {
	// Parse the recursion field.
	recursion, err := strconv.Atoi(r.FormValue("recursion"))
	if err != nil {
		recursion = 0
	}

	var filter inventory.NetworkLoadBalancerFilter

	if r.URL.Query().Get("cluster") != "" {
		filter.Cluster = new(r.URL.Query().Get("cluster"))
	}

	if r.URL.Query().Get("project") != "" {
		filter.ProjectName = new(r.URL.Query().Get("project"))
	}

	if r.URL.Query().Get("filter") != "" {
		filter.Expression = new(r.URL.Query().Get("filter"))
	}

	if recursion == 1 {
		// FIXME: Should we require a non empty filter with recursion?
		networkLoadBalancers, err := i.service.GetAllWithFilter(r.Context(), filter)
		if err != nil {
			return response.SmartError(err)
		}

		result := make([]api.NetworkLoadBalancer, 0, len(networkLoadBalancers))
		for _, networkLoadBalancer := range networkLoadBalancers {
			result = append(result, api.NetworkLoadBalancer{
				UUID:        networkLoadBalancer.UUID,
				Cluster:     networkLoadBalancer.Cluster,
				ProjectName: networkLoadBalancer.ProjectName,
				NetworkName: networkLoadBalancer.NetworkName,
				Name:        networkLoadBalancer.Name,
				Object:      networkLoadBalancer.Object.NetworkLoadBalancer,
				LastUpdated: networkLoadBalancer.LastUpdated,
			})
		}

		return response.SyncResponse(true, result)
	}

	networkLoadBalancerUUIDs, err := i.service.GetAllUUIDsWithFilter(r.Context(), filter)
	if err != nil {
		return response.SmartError(err)
	}

	result := make([]string, 0, len(networkLoadBalancerUUIDs))
	for _, id := range networkLoadBalancerUUIDs {
		result = append(result, fmt.Sprintf("/%s/inventory/network_load_balancers/%s", api.APIVersion, id.String()))
	}

	return response.SyncResponse(true, result)
}

// swagger:operation GET /1.0/inventory/network_load_balancers/{uuid} network_load_balancers network_load_balancer_get
//
//	Get the network load balancer
//
//	Gets a specific network load balancer.
//
//	---
//	produces:
//	  - application/json
//	parameters:
//	  - in: path
//	    name: uuid
//	    description: UUID of the network load balancer
//	    type: string
//	    format: uuid
//	    required: true
//	responses:
//	  "200":
//	    $ref: "#/responses/NetworkLoadBalancerResponse"
//	  "403":
//	    $ref: "#/responses/Forbidden"
//	  "404":
//	    $ref: "#/responses/NotFound"
//	  "500":
//	    $ref: "#/responses/InternalServerError"
func (i *networkLoadBalancerHandler) networkLoadBalancerGet(r *http.Request) response.Response {
	id, err := uuid.Parse(r.PathValue("uuid"))
	if err != nil {
		return response.SmartError(err)
	}

	networkLoadBalancer, err := i.service.GetByUUID(r.Context(), id)
	if err != nil {
		return response.SmartError(err)
	}

	return response.SyncResponse(
		true,
		api.NetworkLoadBalancer{
			UUID:        networkLoadBalancer.UUID,
			Cluster:     networkLoadBalancer.Cluster,
			ProjectName: networkLoadBalancer.ProjectName,
			NetworkName: networkLoadBalancer.NetworkName,
			Name:        networkLoadBalancer.Name,
			Object:      networkLoadBalancer.Object.NetworkLoadBalancer,
			LastUpdated: networkLoadBalancer.LastUpdated,
		},
	)
}

// swagger:operation POST /1.0/inventory/network_load_balancers/{uuid}/:resync network_load_balancers network_load_balancer_get_resync_post
//
//	Resync the network load balancer
//
//	Resync a specific network load balancer.
//
//	---
//	produces:
//	  - application/json
//	parameters:
//	  - in: path
//	    name: uuid
//	    description: UUID of the network load balancer
//	    type: string
//	    format: uuid
//	    required: true
//	responses:
//	  "200":
//	    $ref: "#/responses/EmptySyncResponse"
//	  "403":
//	    $ref: "#/responses/Forbidden"
//	  "404":
//	    $ref: "#/responses/NotFound"
//	  "500":
//	    $ref: "#/responses/InternalServerError"
func (i *networkLoadBalancerHandler) networkLoadBalancerResyncPost(r *http.Request) response.Response {
	id, err := uuid.Parse(r.PathValue("uuid"))
	if err != nil {
		return response.SmartError(err)
	}

	err = i.service.ResyncByUUID(r.Context(), id)
	if err != nil {
		return response.SmartError(fmt.Errorf("Failed to resync network_load_balancer: %w", err))
	}

	return response.EmptySyncResponse
}

// The network load balancer
//
// swagger:response NetworkLoadBalancerResponse
type swaggerNetworkLoadBalancerResponse struct {
	// in: body
	Body struct {
		// Example: sync
		Type string `json:"type"`

		// Example: Success
		Status string `json:"status"`

		// Example: 200
		StatusCode int `json:"status_code"`

		Metadata api.NetworkLoadBalancer `json:"metadata"`
	}
}

// The network load balancers
//
// swagger:response NetworkLoadBalancersResponse
type swaggerNetworkLoadBalancersResponse struct {
	// in: body
	Body struct {
		// Example: sync
		Type string `json:"type"`

		// Example: Success
		Status string `json:"status"`

		// Example: 200
		StatusCode int `json:"status_code"`

		Metadata []api.NetworkLoadBalancer `json:"metadata"`
	}
}
