// Code generated by generate-inventory; DO NOT EDIT.

package sqlite

import (
	"context"
	"database/sql"
	"encoding/json"
	"fmt"
	"strings"

	"github.com/FuturFusion/operations-center/internal/domain"
	"github.com/FuturFusion/operations-center/internal/inventory"
	"github.com/FuturFusion/operations-center/internal/sqlite"
)

type storageBucket struct {
	db sqlite.DBTX
}

var _ inventory.StorageBucketRepo = &storageBucket{}

func NewStorageBucket(db sqlite.DBTX) *storageBucket {
	return &storageBucket{
		db: db,
	}
}

func (i storageBucket) Create(ctx context.Context, in inventory.StorageBucket) (inventory.StorageBucket, error) {
	const sqlStmt = `
WITH _server AS (
  SELECT cluster_id FROM servers WHERE server_id = :server_id
)
INSERT INTO storage_buckets (server_id, project_name, storage_pool_name, name, object, last_updated)
VALUES(:server_id, :project_name, :storage_pool_name, :name, :object, :last_updated)
RETURNING id, (SELECT cluster_id FROM _server) as cluster_id, server_id, project_name, storage_pool_name, name, object, last_updated;
`

	marshaledObject, err := json.Marshal(in.Object)
	if err != nil {
		return inventory.StorageBucket{}, err
	}

	row := i.db.QueryRowContext(ctx, sqlStmt,
		sql.Named("server_id", in.ServerID),
		sql.Named("project_name", in.ProjectName),
		sql.Named("storage_pool_name", in.StoragePoolName),
		sql.Named("name", in.Name),
		sql.Named("object", marshaledObject),
		sql.Named("last_updated", in.LastUpdated),
	)
	if row.Err() != nil {
		return inventory.StorageBucket{}, sqlite.MapErr(row.Err())
	}

	return scanStorageBucket(row)
}

func (i storageBucket) GetAllIDsWithFilter(ctx context.Context, filter inventory.StorageBucketFilter) ([]int, error) {
	const sqlStmt = `
SELECT storage_buckets.id
FROM storage_buckets
  INNER JOIN servers ON storage_buckets.server_id = servers.id
  INNER JOIN clusters ON servers.cluster_id = clusters.id
WHERE true
%s
ORDER BY storage_buckets.id
`

	var whereClause []string
	var args []any

	if filter.Cluster != nil {
		whereClause = append(whereClause, ` AND clusters.name = :cluster`)
		args = append(args, sql.Named("cluster", filter.Cluster))
	}

	if filter.Server != nil {
		whereClause = append(whereClause, ` AND servers.hostname = :server`)
		args = append(args, sql.Named("server", filter.Server))
	}

	if filter.Project != nil {
		whereClause = append(whereClause, ` AND storage_buckets.project_name = :project`)
		args = append(args, sql.Named("project", filter.Project))
	}

	sqlStmtComplete := fmt.Sprintf(sqlStmt, strings.Join(whereClause, " "))

	rows, err := i.db.QueryContext(ctx, sqlStmtComplete, args...)
	if err != nil {
		return nil, sqlite.MapErr(err)
	}

	defer func() { _ = rows.Close() }()

	var ids []int
	for rows.Next() {
		var id int
		err := rows.Scan(&id)
		if err != nil {
			return nil, sqlite.MapErr(err)
		}

		ids = append(ids, id)
	}

	if rows.Err() != nil {
		return nil, sqlite.MapErr(rows.Err())
	}

	return ids, nil
}

func (i storageBucket) GetByID(ctx context.Context, id int) (inventory.StorageBucket, error) {
	const sqlStmt = `
SELECT
  storage_buckets.id, servers.cluster_id as cluster_id, storage_buckets.server_id, storage_buckets.project_name, storage_buckets.storage_pool_name, storage_buckets.name, storage_buckets.object, storage_buckets.last_updated
FROM
  storage_buckets
  INNER JOIN servers ON storage_buckets.server_id = servers.id
WHERE storage_buckets.id=:id;
`

	row := i.db.QueryRowContext(ctx, sqlStmt, sql.Named("id", id))
	if row.Err() != nil {
		return inventory.StorageBucket{}, sqlite.MapErr(row.Err())
	}

	return scanStorageBucket(row)
}

func (i storageBucket) DeleteByServerID(ctx context.Context, serverID int) error {
	const sqlStmt = `DELETE FROM storage_buckets WHERE server_id=:serverID;`

	result, err := i.db.ExecContext(ctx, sqlStmt, sql.Named("serverID", serverID))
	if err != nil {
		return sqlite.MapErr(err)
	}

	affectedRows, err := result.RowsAffected()
	if err != nil {
		return sqlite.MapErr(err)
	}

	if affectedRows == 0 {
		return domain.ErrNotFound
	}

	return nil
}

func (i storageBucket) UpdateByID(ctx context.Context, in inventory.StorageBucket) (inventory.StorageBucket, error) {
	const sqlStmt = `
WITH _server AS (
  SELECT cluster_id FROM servers WHERE server_id = :server_id
)
UPDATE storage_buckets SET server_id=:server_id, project_name=:project_name, storage_pool_name=:storage_pool_name, name=:name, object=:object, last_updated=:last_updated
WHERE id=:id
RETURNING id, (SELECT cluster_id FROM _server) as cluster_id, server_id, project_name, storage_pool_name, name, object, last_updated;
`

	marshaledObject, err := json.Marshal(in.Object)
	if err != nil {
		return inventory.StorageBucket{}, err
	}

	row := i.db.QueryRowContext(ctx, sqlStmt,
		sql.Named("id", in.ID),
		sql.Named("server_id", in.ServerID),
		sql.Named("project_name", in.ProjectName),
		sql.Named("storage_pool_name", in.StoragePoolName),
		sql.Named("name", in.Name),
		sql.Named("object", marshaledObject),
		sql.Named("last_updated", in.LastUpdated),
	)
	if row.Err() != nil {
		return inventory.StorageBucket{}, sqlite.MapErr(row.Err())
	}

	return scanStorageBucket(row)
}

func scanStorageBucket(row interface{ Scan(dest ...any) error }) (inventory.StorageBucket, error) {
	var object []byte
	var storageBucket inventory.StorageBucket

	err := row.Scan(
		&storageBucket.ID,
		&storageBucket.ClusterID,
		&storageBucket.ServerID,
		&storageBucket.ProjectName,
		&storageBucket.StoragePoolName,
		&storageBucket.Name,
		&object,
		&storageBucket.LastUpdated,
	)
	if err != nil {
		return inventory.StorageBucket{}, sqlite.MapErr(err)
	}

	err = json.Unmarshal(object, &storageBucket.Object)
	if err != nil {
		return inventory.StorageBucket{}, err
	}

	return storageBucket, nil
}
