// Code generated by generate-inventory; DO NOT EDIT.

package sqlite

import (
	"context"
	"database/sql"
	"encoding/json"
	"fmt"
	"strings"

	"github.com/FuturFusion/operations-center/internal/domain"
	"github.com/FuturFusion/operations-center/internal/inventory"
	"github.com/FuturFusion/operations-center/internal/sqlite"
)

type storagePool struct {
	db sqlite.DBTX
}

var _ inventory.StoragePoolRepo = &storagePool{}

func NewStoragePool(db sqlite.DBTX) *storagePool {
	return &storagePool{
		db: db,
	}
}

func (r storagePool) Create(ctx context.Context, in inventory.StoragePool) (inventory.StoragePool, error) {
	const sqlStmt = `
INSERT INTO storage_pools (cluster_id, name, object, last_updated)
VALUES(:cluster_id, :name, :object, :last_updated)
RETURNING id, cluster_id, name, object, last_updated;
`

	marshaledObject, err := json.Marshal(in.Object)
	if err != nil {
		return inventory.StoragePool{}, err
	}

	row := r.db.QueryRowContext(ctx, sqlStmt,
		sql.Named("cluster_id", in.ClusterID),
		sql.Named("name", in.Name),
		sql.Named("object", marshaledObject),
		sql.Named("last_updated", in.LastUpdated),
	)
	if row.Err() != nil {
		return inventory.StoragePool{}, sqlite.MapErr(row.Err())
	}

	return scanStoragePool(row)
}

func (r storagePool) GetAllIDsWithFilter(ctx context.Context, filter inventory.StoragePoolFilter) ([]int, error) {
	const sqlStmt = `
SELECT storage_pools.id
FROM storage_pools
  INNER JOIN clusters ON storage_pools.cluster_id = clusters.id
WHERE true
%s
ORDER BY storage_pools.id
`

	var whereClause []string
	var args []any

	if filter.Cluster != nil {
		whereClause = append(whereClause, ` AND clusters.name = :cluster`)
		args = append(args, sql.Named("cluster", filter.Cluster))
	}

	sqlStmtComplete := fmt.Sprintf(sqlStmt, strings.Join(whereClause, " "))

	rows, err := r.db.QueryContext(ctx, sqlStmtComplete, args...)
	if err != nil {
		return nil, sqlite.MapErr(err)
	}

	defer func() { _ = rows.Close() }()

	var ids []int
	for rows.Next() {
		var id int
		err := rows.Scan(&id)
		if err != nil {
			return nil, sqlite.MapErr(err)
		}

		ids = append(ids, id)
	}

	if rows.Err() != nil {
		return nil, sqlite.MapErr(rows.Err())
	}

	return ids, nil
}

func (r storagePool) GetByID(ctx context.Context, id int) (inventory.StoragePool, error) {
	const sqlStmt = `
SELECT
  id, cluster_id, name, object, last_updated
FROM
  storage_pools
WHERE id=:id;
`

	row := r.db.QueryRowContext(ctx, sqlStmt, sql.Named("id", id))
	if row.Err() != nil {
		return inventory.StoragePool{}, sqlite.MapErr(row.Err())
	}

	return scanStoragePool(row)
}

func (r storagePool) DeleteByID(ctx context.Context, id int) error {
	const sqlStmt = `DELETE FROM storage_pools WHERE id=:id;`

	result, err := r.db.ExecContext(ctx, sqlStmt, sql.Named("id", id))
	if err != nil {
		return sqlite.MapErr(err)
	}

	affectedRows, err := result.RowsAffected()
	if err != nil {
		return sqlite.MapErr(err)
	}

	if affectedRows == 0 {
		return domain.ErrNotFound
	}

	return nil
}

func (r storagePool) DeleteByClusterID(ctx context.Context, clusterID int) error {
	const sqlStmt = `DELETE FROM storage_pools WHERE cluster_id=:clusterID;`

	result, err := r.db.ExecContext(ctx, sqlStmt, sql.Named("clusterID", clusterID))
	if err != nil {
		return sqlite.MapErr(err)
	}

	affectedRows, err := result.RowsAffected()
	if err != nil {
		return sqlite.MapErr(err)
	}

	if affectedRows == 0 {
		return domain.ErrNotFound
	}

	return nil
}

func (r storagePool) UpdateByID(ctx context.Context, in inventory.StoragePool) (inventory.StoragePool, error) {
	const sqlStmt = `
UPDATE storage_pools SET cluster_id=:cluster_id, name=:name, object=:object, last_updated=:last_updated
WHERE id=:id
RETURNING id, cluster_id, name, object, last_updated;
`

	marshaledObject, err := json.Marshal(in.Object)
	if err != nil {
		return inventory.StoragePool{}, err
	}

	row := r.db.QueryRowContext(ctx, sqlStmt,
		sql.Named("id", in.ID),
		sql.Named("cluster_id", in.ClusterID),
		sql.Named("name", in.Name),
		sql.Named("object", marshaledObject),
		sql.Named("last_updated", in.LastUpdated),
	)
	if row.Err() != nil {
		return inventory.StoragePool{}, sqlite.MapErr(row.Err())
	}

	return scanStoragePool(row)
}

func scanStoragePool(row interface{ Scan(dest ...any) error }) (inventory.StoragePool, error) {
	var object []byte
	var storagePool inventory.StoragePool

	err := row.Scan(
		&storagePool.ID,
		&storagePool.ClusterID,
		&storagePool.Name,
		&object,
		&storagePool.LastUpdated,
	)
	if err != nil {
		return inventory.StoragePool{}, sqlite.MapErr(err)
	}

	err = json.Unmarshal(object, &storagePool.Object)
	if err != nil {
		return inventory.StoragePool{}, err
	}

	return storagePool, nil
}
