// Code generated by generate-inventory; DO NOT EDIT.

package inventory

import (
	"encoding/json"
	"fmt"
	"strconv"

	"github.com/spf13/cobra"

	"github.com/FuturFusion/operations-center/cmd/operations-center/internal/client"
	"github.com/FuturFusion/operations-center/cmd/operations-center/internal/validate"
	"github.com/FuturFusion/operations-center/internal/inventory"
	"github.com/FuturFusion/operations-center/internal/ptr"
	"github.com/FuturFusion/operations-center/internal/render"
	"github.com/FuturFusion/operations-center/internal/sort"
)

type CmdNetworkZone struct{}

func (c *CmdNetworkZone) Command() *cobra.Command {
	cmd := &cobra.Command{}
	cmd.Use = "network_zone"
	cmd.Short = "Interact with network_zones"
	cmd.Long = `Description:
  Interact with network_zones

  Configure network_zones for use by operations center.
`

	// Workaround for subcommand usage errors. See: https://github.com/spf13/cobra/issues/706
	cmd.Args = cobra.NoArgs
	cmd.Run = func(cmd *cobra.Command, args []string) { _ = cmd.Usage() }

	// List
	networkZoneListCmd := cmdNetworkZoneList{}
	cmd.AddCommand(networkZoneListCmd.Command())

	// Show
	networkZoneShowCmd := cmdNetworkZoneShow{}
	cmd.AddCommand(networkZoneShowCmd.Command())

	return cmd
}

// List network_zones.
type cmdNetworkZoneList struct {
	flagFilterCluster    string
	flagFilterProject    string
	flagFilterExpression string

	flagFormat string
}

func (c *cmdNetworkZoneList) Command() *cobra.Command {
	cmd := &cobra.Command{}
	cmd.Use = "list"
	cmd.Short = "List available network_zones"
	cmd.Long = `Description:
  List the available network_zones
`

	cmd.RunE = c.Run

	cmd.Flags().StringVar(&c.flagFilterCluster, "cluster", "", "cluster name to filter for")
	cmd.Flags().StringVar(&c.flagFilterProject, "project", "", "project name to filter for")
	cmd.Flags().StringVar(&c.flagFilterExpression, "filter", "", "filter expression to apply")

	cmd.Flags().StringVarP(&c.flagFormat, "format", "f", "table", `Format (csv|json|table|yaml|compact), use suffix ",noheader" to disable headers and ",header" to enable if demanded, e.g. csv,header`)
	cmd.PreRunE = func(cmd *cobra.Command, _ []string) error {
		return validate.FormatFlag(cmd.Flag("format").Value.String())
	}

	return cmd
}

func (c *cmdNetworkZoneList) Run(cmd *cobra.Command, args []string) error {
	// Quick checks.
	exit, err := validate.Args(cmd, args, 0, 0)
	if exit {
		return err
	}

	var filter inventory.NetworkZoneFilter

	if c.flagFilterCluster != "" {
		filter.Cluster = ptr.To(c.flagFilterCluster)
	}

	if c.flagFilterProject != "" {
		filter.Project = ptr.To(c.flagFilterProject)
	}

	if c.flagFilterExpression != "" {
		filter.Expression = ptr.To(c.flagFilterExpression)
	}

	// Client call
	ocClient := client.New()

	networkZones, err := ocClient.GetWithFilterNetworkZones(filter)
	if err != nil {
		return err
	}

	// Render the table.
	header := []string{
		"ID",
		"Cluster",
		"Project Name",
		"Name",
		"Last Updated",
	}

	data := [][]string{}

	for _, networkZone := range networkZones {
		data = append(data, []string{
			strconv.FormatInt(int64(networkZone.ID), 10),
			networkZone.Cluster,
			networkZone.ProjectName,
			networkZone.Name,
			networkZone.LastUpdated.String(),
		})
	}

	sort.ColumnsNaturally(data)

	return render.Table(cmd.OutOrStdout(), c.flagFormat, header, data, networkZones)
}

// Show network_zone.
type cmdNetworkZoneShow struct{}

func (c *cmdNetworkZoneShow) Command() *cobra.Command {
	cmd := &cobra.Command{}
	cmd.Use = "show <name>"
	cmd.Short = "Show information about a network_zone"
	cmd.Long = `Description:
  Show information about a network_zone.
`

	cmd.RunE = c.Run

	return cmd
}

func (c *cmdNetworkZoneShow) Run(cmd *cobra.Command, args []string) error {
	// Quick checks.
	exit, err := validate.Args(cmd, args, 1, 1)
	if exit {
		return err
	}

	name := args[0]

	// Client call
	ocClient := client.New()

	networkZone, err := ocClient.GetNetworkZone(name)
	if err != nil {
		return err
	}

	objectJSON, err := json.MarshalIndent(networkZone.Object, "", "  ")
	if err != nil {
		return err
	}

	fmt.Printf("ID: %d\n", networkZone.ID)
	fmt.Printf("Cluster: %s\n", networkZone.Cluster)
	fmt.Printf("Project Name: %s\n", networkZone.ProjectName)
	fmt.Printf("Name: %s\n", networkZone.Name)
	fmt.Printf("Last Updated: %s\n", networkZone.LastUpdated.String())
	fmt.Printf("Object:\n%s\n", objectJSON)

	return nil
}
