// Code generated by generate-expr. DO NOT EDIT.

package provisioning

import (
	"time"

	"github.com/FuturFusion/operations-center/shared/api"
)

type ExprCluster struct {
	ID                    int64             `json:"-" expr:"-"`
	Name                  string            `json:"name"                    db:"primary=yes" expr:"name"`
	ConnectionURL         string            `json:"connection_url" expr:"connection_url"`
	Certificate           *string           `json:"certificate" expr:"certificate"`
	Fingerprint           string            `json:"fingerprint"             db:"ignore" expr:"fingerprint"`
	Status                api.ClusterStatus `json:"status" expr:"status"`
	ServerNames           []string          `json:"server_names"            db:"ignore" expr:"server_names"`
	ServerType            api.ServerType    `json:"server_type"             db:"ignore" expr:"server_type"`
	ServicesConfig        map[string]any    `json:"services_config"         db:"ignore" expr:"services_config"`
	ApplicationSeedConfig map[string]any    `json:"application_seed_config" db:"ignore" expr:"application_seed_config"`
	LastUpdated           time.Time         `json:"last_updated"            db:"update_timestamp" expr:"last_updated"`
}

func ToExprCluster(c Cluster) ExprCluster {
	return ExprCluster{
		ID:                    c.ID,
		Name:                  c.Name,
		ConnectionURL:         c.ConnectionURL,
		Certificate:           c.Certificate,
		Fingerprint:           c.Fingerprint,
		Status:                c.Status,
		ServerNames:           c.ServerNames,
		ServerType:            c.ServerType,
		ServicesConfig:        c.ServicesConfig,
		ApplicationSeedConfig: c.ApplicationSeedConfig,
		LastUpdated:           c.LastUpdated,
	}
}
