// Code generated by generate-expr. DO NOT EDIT.

package provisioning

import "time"

type ExprExposedchannel struct {
	ID          int64     `json:"-" expr:"-"`
	Name        string    `json:"name" db:"primary=yes" expr:"name"`
	Description string    `json:"description" expr:"description"`
	LastUpdated time.Time `json:"-" expr:"last_updated" db:"update_timestamp"`
}

func ToExprExposedchannel(e Exposedchannel) ExprExposedchannel {
	return ExprExposedchannel{
		ID:          e.ID,
		Name:        e.Name,
		Description: e.Description,
		LastUpdated: e.LastUpdated,
	}
}
