// Code generated by gowrap. DO NOT EDIT.
// template: ../../../logger/slog.gotmpl
// gowrap: http://github.com/hexdigest/gowrap

package middleware

import (
	"context"
	"log/slog"

	_sourceInventory "github.com/FuturFusion/operations-center/internal/inventory"
)

// NetworkPeerRepoWithSlog implements _sourceInventory.NetworkPeerRepo that is instrumented with slog logger
type NetworkPeerRepoWithSlog struct {
	_log  *slog.Logger
	_base _sourceInventory.NetworkPeerRepo
}

// NewNetworkPeerRepoWithSlog instruments an implementation of the _sourceInventory.NetworkPeerRepo with simple logging
func NewNetworkPeerRepoWithSlog(base _sourceInventory.NetworkPeerRepo, log *slog.Logger) NetworkPeerRepoWithSlog {
	return NetworkPeerRepoWithSlog{
		_base: base,
		_log:  log,
	}
}

// Create implements _sourceInventory.NetworkPeerRepo
func (_d NetworkPeerRepoWithSlog) Create(ctx context.Context, networkPeer _sourceInventory.NetworkPeer) (n1 _sourceInventory.NetworkPeer, err error) {
	_d._log.With(
		slog.Any("ctx", ctx),
		slog.Any("networkPeer", networkPeer),
	).Debug("NetworkPeerRepoWithSlog: calling Create")
	defer func() {
		log := _d._log.With(
			slog.Any("n1", n1),
			slog.Any("err", err),
		)
		if err != nil {
			log.Error("NetworkPeerRepoWithSlog: method Create returned an error")
		} else {
			log.Debug("NetworkPeerRepoWithSlog: method Create finished")
		}
	}()
	return _d._base.Create(ctx, networkPeer)
}

// DeleteByServerID implements _sourceInventory.NetworkPeerRepo
func (_d NetworkPeerRepoWithSlog) DeleteByServerID(ctx context.Context, serverID int) (err error) {
	_d._log.With(
		slog.Any("ctx", ctx),
		slog.Int("serverID", serverID),
	).Debug("NetworkPeerRepoWithSlog: calling DeleteByServerID")
	defer func() {
		log := _d._log.With(
			slog.Any("err", err),
		)
		if err != nil {
			log.Error("NetworkPeerRepoWithSlog: method DeleteByServerID returned an error")
		} else {
			log.Debug("NetworkPeerRepoWithSlog: method DeleteByServerID finished")
		}
	}()
	return _d._base.DeleteByServerID(ctx, serverID)
}

// GetAllIDs implements _sourceInventory.NetworkPeerRepo
func (_d NetworkPeerRepoWithSlog) GetAllIDs(ctx context.Context) (ia1 []int, err error) {
	_d._log.With(
		slog.Any("ctx", ctx),
	).Debug("NetworkPeerRepoWithSlog: calling GetAllIDs")
	defer func() {
		log := _d._log.With(
			slog.Any("ia1", ia1),
			slog.Any("err", err),
		)
		if err != nil {
			log.Error("NetworkPeerRepoWithSlog: method GetAllIDs returned an error")
		} else {
			log.Debug("NetworkPeerRepoWithSlog: method GetAllIDs finished")
		}
	}()
	return _d._base.GetAllIDs(ctx)
}

// GetByID implements _sourceInventory.NetworkPeerRepo
func (_d NetworkPeerRepoWithSlog) GetByID(ctx context.Context, id int) (n1 _sourceInventory.NetworkPeer, err error) {
	_d._log.With(
		slog.Any("ctx", ctx),
		slog.Int("id", id),
	).Debug("NetworkPeerRepoWithSlog: calling GetByID")
	defer func() {
		log := _d._log.With(
			slog.Any("n1", n1),
			slog.Any("err", err),
		)
		if err != nil {
			log.Error("NetworkPeerRepoWithSlog: method GetByID returned an error")
		} else {
			log.Debug("NetworkPeerRepoWithSlog: method GetByID finished")
		}
	}()
	return _d._base.GetByID(ctx, id)
}
