// Code generated by gowrap. DO NOT EDIT.
// template: ../../../logger/slog.gotmpl
// gowrap: http://github.com/hexdigest/gowrap

package middleware

import (
	"context"
	"log/slog"

	_sourceInventory "github.com/FuturFusion/operations-center/internal/inventory"
)

// NetworkACLRepoWithSlog implements _sourceInventory.NetworkACLRepo that is instrumented with slog logger
type NetworkACLRepoWithSlog struct {
	_log  *slog.Logger
	_base _sourceInventory.NetworkACLRepo
}

// NewNetworkACLRepoWithSlog instruments an implementation of the _sourceInventory.NetworkACLRepo with simple logging
func NewNetworkACLRepoWithSlog(base _sourceInventory.NetworkACLRepo, log *slog.Logger) NetworkACLRepoWithSlog {
	return NetworkACLRepoWithSlog{
		_base: base,
		_log:  log,
	}
}

// Create implements _sourceInventory.NetworkACLRepo
func (_d NetworkACLRepoWithSlog) Create(ctx context.Context, networkACL _sourceInventory.NetworkACL) (n1 _sourceInventory.NetworkACL, err error) {
	_d._log.With(
		slog.Any("ctx", ctx),
		slog.Any("networkACL", networkACL),
	).Debug("NetworkACLRepoWithSlog: calling Create")
	defer func() {
		log := _d._log.With(
			slog.Any("n1", n1),
			slog.Any("err", err),
		)
		if err != nil {
			log.Error("NetworkACLRepoWithSlog: method Create returned an error")
		} else {
			log.Debug("NetworkACLRepoWithSlog: method Create finished")
		}
	}()
	return _d._base.Create(ctx, networkACL)
}

// DeleteByServerID implements _sourceInventory.NetworkACLRepo
func (_d NetworkACLRepoWithSlog) DeleteByServerID(ctx context.Context, serverID int) (err error) {
	_d._log.With(
		slog.Any("ctx", ctx),
		slog.Int("serverID", serverID),
	).Debug("NetworkACLRepoWithSlog: calling DeleteByServerID")
	defer func() {
		log := _d._log.With(
			slog.Any("err", err),
		)
		if err != nil {
			log.Error("NetworkACLRepoWithSlog: method DeleteByServerID returned an error")
		} else {
			log.Debug("NetworkACLRepoWithSlog: method DeleteByServerID finished")
		}
	}()
	return _d._base.DeleteByServerID(ctx, serverID)
}

// GetAllIDsWithFilter implements _sourceInventory.NetworkACLRepo
func (_d NetworkACLRepoWithSlog) GetAllIDsWithFilter(ctx context.Context, filter _sourceInventory.NetworkACLFilter) (ia1 []int, err error) {
	_d._log.With(
		slog.Any("ctx", ctx),
		slog.Any("filter", filter),
	).Debug("NetworkACLRepoWithSlog: calling GetAllIDsWithFilter")
	defer func() {
		log := _d._log.With(
			slog.Any("ia1", ia1),
			slog.Any("err", err),
		)
		if err != nil {
			log.Error("NetworkACLRepoWithSlog: method GetAllIDsWithFilter returned an error")
		} else {
			log.Debug("NetworkACLRepoWithSlog: method GetAllIDsWithFilter finished")
		}
	}()
	return _d._base.GetAllIDsWithFilter(ctx, filter)
}

// GetByID implements _sourceInventory.NetworkACLRepo
func (_d NetworkACLRepoWithSlog) GetByID(ctx context.Context, id int) (n1 _sourceInventory.NetworkACL, err error) {
	_d._log.With(
		slog.Any("ctx", ctx),
		slog.Int("id", id),
	).Debug("NetworkACLRepoWithSlog: calling GetByID")
	defer func() {
		log := _d._log.With(
			slog.Any("n1", n1),
			slog.Any("err", err),
		)
		if err != nil {
			log.Error("NetworkACLRepoWithSlog: method GetByID returned an error")
		} else {
			log.Debug("NetworkACLRepoWithSlog: method GetByID finished")
		}
	}()
	return _d._base.GetByID(ctx, id)
}

// UpdateByID implements _sourceInventory.NetworkACLRepo
func (_d NetworkACLRepoWithSlog) UpdateByID(ctx context.Context, networkACL _sourceInventory.NetworkACL) (n1 _sourceInventory.NetworkACL, err error) {
	_d._log.With(
		slog.Any("ctx", ctx),
		slog.Any("networkACL", networkACL),
	).Debug("NetworkACLRepoWithSlog: calling UpdateByID")
	defer func() {
		log := _d._log.With(
			slog.Any("n1", n1),
			slog.Any("err", err),
		)
		if err != nil {
			log.Error("NetworkACLRepoWithSlog: method UpdateByID returned an error")
		} else {
			log.Debug("NetworkACLRepoWithSlog: method UpdateByID finished")
		}
	}()
	return _d._base.UpdateByID(ctx, networkACL)
}
