// Code generated by gowrap. DO NOT EDIT.
// template: ../../../logger/slog.gotmpl
// gowrap: http://github.com/hexdigest/gowrap

package middleware

import (
	"context"
	"log/slog"

	_sourceInventory "github.com/FuturFusion/operations-center/internal/inventory"
	"github.com/FuturFusion/operations-center/internal/logger"
)

// ProfileRepoWithSlog implements _sourceInventory.ProfileRepo that is instrumented with slog logger
type ProfileRepoWithSlog struct {
	_log  *slog.Logger
	_base _sourceInventory.ProfileRepo
}

// NewProfileRepoWithSlog instruments an implementation of the _sourceInventory.ProfileRepo with simple logging
func NewProfileRepoWithSlog(base _sourceInventory.ProfileRepo, log *slog.Logger) ProfileRepoWithSlog {
	return ProfileRepoWithSlog{
		_base: base,
		_log:  log,
	}
}

// Create implements _sourceInventory.ProfileRepo
func (_d ProfileRepoWithSlog) Create(ctx context.Context, profile _sourceInventory.Profile) (p1 _sourceInventory.Profile, err error) {
	log := _d._log.With()
	if _d._log.Enabled(ctx, logger.LevelTrace) {
		log.With(
			slog.Any("ctx", ctx),
			slog.Any("profile", profile),
		)
	}
	log.Debug("ProfileRepoWithSlog: calling Create")
	defer func() {
		log := _d._log.With()
		if _d._log.Enabled(ctx, logger.LevelTrace) {
			log = _d._log.With(
				slog.Any("p1", p1),
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = _d._log.With("err", err)
			}
		}
		if err != nil {
			log.Error("ProfileRepoWithSlog: method Create returned an error")
		} else {
			log.Debug("ProfileRepoWithSlog: method Create finished")
		}
	}()
	return _d._base.Create(ctx, profile)
}

// DeleteByClusterID implements _sourceInventory.ProfileRepo
func (_d ProfileRepoWithSlog) DeleteByClusterID(ctx context.Context, clusterID int) (err error) {
	log := _d._log.With()
	if _d._log.Enabled(ctx, logger.LevelTrace) {
		log.With(
			slog.Any("ctx", ctx),
			slog.Int("clusterID", clusterID),
		)
	}
	log.Debug("ProfileRepoWithSlog: calling DeleteByClusterID")
	defer func() {
		log := _d._log.With()
		if _d._log.Enabled(ctx, logger.LevelTrace) {
			log = _d._log.With(
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = _d._log.With("err", err)
			}
		}
		if err != nil {
			log.Error("ProfileRepoWithSlog: method DeleteByClusterID returned an error")
		} else {
			log.Debug("ProfileRepoWithSlog: method DeleteByClusterID finished")
		}
	}()
	return _d._base.DeleteByClusterID(ctx, clusterID)
}

// DeleteByID implements _sourceInventory.ProfileRepo
func (_d ProfileRepoWithSlog) DeleteByID(ctx context.Context, id int) (err error) {
	log := _d._log.With()
	if _d._log.Enabled(ctx, logger.LevelTrace) {
		log.With(
			slog.Any("ctx", ctx),
			slog.Int("id", id),
		)
	}
	log.Debug("ProfileRepoWithSlog: calling DeleteByID")
	defer func() {
		log := _d._log.With()
		if _d._log.Enabled(ctx, logger.LevelTrace) {
			log = _d._log.With(
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = _d._log.With("err", err)
			}
		}
		if err != nil {
			log.Error("ProfileRepoWithSlog: method DeleteByID returned an error")
		} else {
			log.Debug("ProfileRepoWithSlog: method DeleteByID finished")
		}
	}()
	return _d._base.DeleteByID(ctx, id)
}

// GetAllIDsWithFilter implements _sourceInventory.ProfileRepo
func (_d ProfileRepoWithSlog) GetAllIDsWithFilter(ctx context.Context, filter _sourceInventory.ProfileFilter) (ia1 []int, err error) {
	log := _d._log.With()
	if _d._log.Enabled(ctx, logger.LevelTrace) {
		log.With(
			slog.Any("ctx", ctx),
			slog.Any("filter", filter),
		)
	}
	log.Debug("ProfileRepoWithSlog: calling GetAllIDsWithFilter")
	defer func() {
		log := _d._log.With()
		if _d._log.Enabled(ctx, logger.LevelTrace) {
			log = _d._log.With(
				slog.Any("ia1", ia1),
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = _d._log.With("err", err)
			}
		}
		if err != nil {
			log.Error("ProfileRepoWithSlog: method GetAllIDsWithFilter returned an error")
		} else {
			log.Debug("ProfileRepoWithSlog: method GetAllIDsWithFilter finished")
		}
	}()
	return _d._base.GetAllIDsWithFilter(ctx, filter)
}

// GetByID implements _sourceInventory.ProfileRepo
func (_d ProfileRepoWithSlog) GetByID(ctx context.Context, id int) (p1 _sourceInventory.Profile, err error) {
	log := _d._log.With()
	if _d._log.Enabled(ctx, logger.LevelTrace) {
		log.With(
			slog.Any("ctx", ctx),
			slog.Int("id", id),
		)
	}
	log.Debug("ProfileRepoWithSlog: calling GetByID")
	defer func() {
		log := _d._log.With()
		if _d._log.Enabled(ctx, logger.LevelTrace) {
			log = _d._log.With(
				slog.Any("p1", p1),
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = _d._log.With("err", err)
			}
		}
		if err != nil {
			log.Error("ProfileRepoWithSlog: method GetByID returned an error")
		} else {
			log.Debug("ProfileRepoWithSlog: method GetByID finished")
		}
	}()
	return _d._base.GetByID(ctx, id)
}

// UpdateByID implements _sourceInventory.ProfileRepo
func (_d ProfileRepoWithSlog) UpdateByID(ctx context.Context, profile _sourceInventory.Profile) (p1 _sourceInventory.Profile, err error) {
	log := _d._log.With()
	if _d._log.Enabled(ctx, logger.LevelTrace) {
		log.With(
			slog.Any("ctx", ctx),
			slog.Any("profile", profile),
		)
	}
	log.Debug("ProfileRepoWithSlog: calling UpdateByID")
	defer func() {
		log := _d._log.With()
		if _d._log.Enabled(ctx, logger.LevelTrace) {
			log = _d._log.With(
				slog.Any("p1", p1),
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = _d._log.With("err", err)
			}
		}
		if err != nil {
			log.Error("ProfileRepoWithSlog: method UpdateByID returned an error")
		} else {
			log.Debug("ProfileRepoWithSlog: method UpdateByID finished")
		}
	}()
	return _d._base.UpdateByID(ctx, profile)
}
