// Code generated by generate-inventory; DO NOT EDIT.

package inventory

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"net/url"
	"strings"
	"time"

	"github.com/google/uuid"
	incusapi "github.com/lxc/incus/v6/shared/api"

	"github.com/FuturFusion/operations-center/internal/domain"
)

type IncusInstanceFullWrapper struct {
	incusapi.InstanceFull `json:"-"`
}

func (w IncusInstanceFullWrapper) Value() (driver.Value, error) {
	return json.Marshal(w.InstanceFull)
}

func (w *IncusInstanceFullWrapper) Scan(value interface{}) error {
	if value == nil {
		return fmt.Errorf("null is not a valid InstanceFull")
	}

	switch v := value.(type) {
	case string:
		return json.Unmarshal([]byte(v), &w.InstanceFull)
	case []byte:
		return json.Unmarshal(v, &w.InstanceFull)
	default:
		return fmt.Errorf("type %T is not supported for InstanceFull", value)
	}
}

//
//generate-expr: Instance

type Instance struct {
	ID          int                      `json:"-"`
	UUID        uuid.UUID                `json:"uuid"          db:"primary=yes"`
	Cluster     string                   `json:"cluster"       db:"leftjoin=clusters.name"`
	Server      string                   `json:"server"        db:"leftjoin=servers.name"`
	ProjectName string                   `json:"project"       db:"sql=instances.project_name"`
	Name        string                   `json:"name"`
	Object      IncusInstanceFullWrapper `json:"object"`
	LastUpdated time.Time                `json:"last_updated"  db:"update_timestamp"`
}

func (m *Instance) DeriveUUID() *Instance {
	identifier := strings.Join([]string{
		m.Cluster,
		m.ProjectName,
		m.Name,
	}, ":")

	m.UUID = uuid.NewSHA1(InventorySpaceUUID, []byte(identifier))

	return m
}

func (m Instance) Validate() error {
	if m.Cluster == "" {
		return domain.NewValidationErrf("Invalid Instance, cluster can not be empty")
	}

	if m.Server == "" {
		return domain.NewValidationErrf("Invalid Instance, server can not be empty")
	}

	if m.Name == "" {
		return domain.NewValidationErrf("Invalid Instance, name can not be empty")
	}

	if m.ProjectName == "" {
		return domain.NewValidationErrf("Invalid Instance, project name can not be empty")
	}

	clone := m
	clone.DeriveUUID()
	if clone.UUID != m.UUID {
		return domain.NewValidationErrf("Invalid UUID, does not match derived value")
	}

	return nil
}

type Instances []Instance

type InstanceFilter struct {
	UUID        *uuid.UUID
	Cluster     *string
	Server      *string
	ProjectName *string
	Name        *string
	Expression  *string `db:"ignore"`
}

func (f InstanceFilter) AppendToURLValues(query url.Values) url.Values {
	if f.UUID != nil {
		query.Add("uuid", f.UUID.String())
	}

	if f.Cluster != nil {
		query.Add("cluster", *f.Cluster)
	}

	if f.Server != nil {
		query.Add("server", *f.Server)
	}

	if f.ProjectName != nil {
		query.Add("project", *f.ProjectName)
	}

	if f.Name != nil {
		query.Add("name", *f.Name)
	}

	if f.Expression != nil {
		query.Add("filter", *f.Expression)
	}

	return query
}

func (f InstanceFilter) String() string {
	return f.AppendToURLValues(url.Values{}).Encode()
}
