// Code generated by generate-inventory; DO NOT EDIT.

package inventory_test

import (
	"context"
	"testing"
	"time"

	"github.com/google/uuid"
	incusapi "github.com/lxc/incus/v6/shared/api"
	"github.com/stretchr/testify/require"

	"github.com/FuturFusion/operations-center/internal/domain"
	"github.com/FuturFusion/operations-center/internal/inventory"
	serviceMock "github.com/FuturFusion/operations-center/internal/inventory/mock"
	repoMock "github.com/FuturFusion/operations-center/internal/inventory/repo/mock"
	serverMock "github.com/FuturFusion/operations-center/internal/inventory/server/mock"
	"github.com/FuturFusion/operations-center/internal/provisioning"
	"github.com/FuturFusion/operations-center/internal/ptr"
	"github.com/FuturFusion/operations-center/internal/testing/boom"
	"github.com/FuturFusion/operations-center/internal/testing/uuidgen"
)

func TestNetworkLoadBalancerService_GetAllWithFilter(t *testing.T) {
	tests := []struct {
		name                    string
		filterExpression        *string
		repoGetAllWithFilter    inventory.NetworkLoadBalancers
		repoGetAllWithFilterErr error

		assertErr require.ErrorAssertionFunc
		count     int
	}{
		{
			name: "success - no filter expression",
			repoGetAllWithFilter: inventory.NetworkLoadBalancers{
				inventory.NetworkLoadBalancer{
					Name: "one",
				},
				inventory.NetworkLoadBalancer{
					Name: "two",
				},
			},

			assertErr: require.NoError,
			count:     2,
		},
		{
			name:             "success - with filter expression",
			filterExpression: ptr.To(`name == "one"`),
			repoGetAllWithFilter: inventory.NetworkLoadBalancers{
				inventory.NetworkLoadBalancer{
					Name: "one",
				},
				inventory.NetworkLoadBalancer{
					Name: "two",
				},
			},

			assertErr: require.NoError,
			count:     1,
		},
		{
			name:             "error - invalid filter expression",
			filterExpression: ptr.To(``), // the empty expression is an invalid expression.
			repoGetAllWithFilter: inventory.NetworkLoadBalancers{
				inventory.NetworkLoadBalancer{
					Name: "one",
				},
			},

			assertErr: require.Error,
			count:     0,
		},
		{
			name:             "error - filter expression run",
			filterExpression: ptr.To(`fromBase64("~invalid")`), // invalid, returns runtime error during evauluation of the expression.
			repoGetAllWithFilter: inventory.NetworkLoadBalancers{
				inventory.NetworkLoadBalancer{
					Name: "one",
				},
			},

			assertErr: require.Error,
			count:     0,
		},
		{
			name:             "error - non bool expression",
			filterExpression: ptr.To(`"string"`), // invalid, does evaluate to string instead of boolean.
			repoGetAllWithFilter: inventory.NetworkLoadBalancers{
				inventory.NetworkLoadBalancer{
					Name: "one",
				},
			},

			assertErr: func(tt require.TestingT, err error, a ...any) {
				require.ErrorContains(tt, err, "does not evaluate to boolean result")
			},
			count: 0,
		},
		{
			name:                    "error - repo",
			repoGetAllWithFilterErr: boom.Error,

			assertErr: boom.ErrorIs,
			count:     0,
		},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			// Setup
			repo := &repoMock.NetworkLoadBalancerRepoMock{
				GetAllWithFilterFunc: func(ctx context.Context, filter inventory.NetworkLoadBalancerFilter) (inventory.NetworkLoadBalancers, error) {
					return tc.repoGetAllWithFilter, tc.repoGetAllWithFilterErr
				},
			}

			networkLoadBalancerSvc := inventory.NewNetworkLoadBalancerService(repo, nil, nil, nil, inventory.NetworkLoadBalancerWithNow(func() time.Time {
				return time.Date(2025, 2, 26, 8, 54, 35, 123, time.UTC)
			}))

			// Run test
			networkLoadBalancer, err := networkLoadBalancerSvc.GetAllWithFilter(context.Background(), inventory.NetworkLoadBalancerFilter{
				Expression: tc.filterExpression,
			})

			// Assert
			tc.assertErr(t, err)
			require.Len(t, networkLoadBalancer, tc.count)
		})
	}
}

func TestNetworkLoadBalancerService_GetAllUUIDsWithFilter(t *testing.T) {
	tests := []struct {
		name                         string
		filterExpression             *string
		repoGetAllUUIDsWithFilter    []uuid.UUID
		repoGetAllUUIDsWithFilterErr error

		assertErr require.ErrorAssertionFunc
		count     int
	}{
		{
			name: "success - no filter expression",
			repoGetAllUUIDsWithFilter: []uuid.UUID{
				uuidgen.FromPattern(t, "1"),
				uuidgen.FromPattern(t, "2"),
			},

			assertErr: require.NoError,
			count:     2,
		},
		{
			name:             "success - with filter expression",
			filterExpression: ptr.To(`uuid == "11111111-1111-1111-1111-111111111111"`),
			repoGetAllUUIDsWithFilter: []uuid.UUID{
				uuidgen.FromPattern(t, "1"),
				uuidgen.FromPattern(t, "2"),
			},

			assertErr: require.NoError,
			count:     1,
		},
		{
			name:             "error - invalid filter expression",
			filterExpression: ptr.To(``), // the empty expression is an invalid expression.
			repoGetAllUUIDsWithFilter: []uuid.UUID{
				uuidgen.FromPattern(t, "1"),
			},

			assertErr: require.Error,
			count:     0,
		},
		{
			name:             "error - filter expression run",
			filterExpression: ptr.To(`fromBase64("~invalid")`), // invalid, returns runtime error during evauluation of the expression.
			repoGetAllUUIDsWithFilter: []uuid.UUID{
				uuidgen.FromPattern(t, "1"),
			},

			assertErr: require.Error,
			count:     0,
		},
		{
			name:             "error - non bool expression",
			filterExpression: ptr.To(`"string"`), // invalid, does evaluate to string instead of boolean.
			repoGetAllUUIDsWithFilter: []uuid.UUID{
				uuidgen.FromPattern(t, "1"),
			},

			assertErr: func(tt require.TestingT, err error, a ...any) {
				require.ErrorContains(tt, err, "does not evaluate to boolean result")
			},
			count: 0,
		},
		{
			name:                         "error - repo",
			repoGetAllUUIDsWithFilterErr: boom.Error,

			assertErr: boom.ErrorIs,
			count:     0,
		},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			// Setup
			repo := &repoMock.NetworkLoadBalancerRepoMock{
				GetAllUUIDsWithFilterFunc: func(ctx context.Context, filter inventory.NetworkLoadBalancerFilter) ([]uuid.UUID, error) {
					return tc.repoGetAllUUIDsWithFilter, tc.repoGetAllUUIDsWithFilterErr
				},
			}

			networkLoadBalancerSvc := inventory.NewNetworkLoadBalancerService(repo, nil, nil, nil, inventory.NetworkLoadBalancerWithNow(func() time.Time {
				return time.Date(2025, 2, 26, 8, 54, 35, 123, time.UTC)
			}))

			// Run test
			networkLoadBalancerUUIDs, err := networkLoadBalancerSvc.GetAllUUIDsWithFilter(context.Background(), inventory.NetworkLoadBalancerFilter{
				Expression: tc.filterExpression,
			})

			// Assert
			tc.assertErr(t, err)
			require.Len(t, networkLoadBalancerUUIDs, tc.count)
		})
	}
}

func TestNetworkLoadBalancerService_GetByUUID(t *testing.T) {
	tests := []struct {
		name                             string
		idArg                            uuid.UUID
		repoGetByUUIDNetworkLoadBalancer inventory.NetworkLoadBalancer
		repoGetByUUIDErr                 error

		assertErr require.ErrorAssertionFunc
	}{
		{
			name:  "success",
			idArg: uuidgen.FromPattern(t, "1"),
			repoGetByUUIDNetworkLoadBalancer: inventory.NetworkLoadBalancer{
				UUID:        uuidgen.FromPattern(t, "1"),
				Cluster:     "one",
				NetworkName: "parent one",
				Name:        "one",
				Object:      incusapi.NetworkLoadBalancer{},
				LastUpdated: time.Now(),
			},

			assertErr: require.NoError,
		},
		{
			name:             "error - repo",
			idArg:            uuidgen.FromPattern(t, "1"),
			repoGetByUUIDErr: boom.Error,

			assertErr: boom.ErrorIs,
		},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			// Setup
			repo := &repoMock.NetworkLoadBalancerRepoMock{
				GetByUUIDFunc: func(ctx context.Context, id uuid.UUID) (inventory.NetworkLoadBalancer, error) {
					return tc.repoGetByUUIDNetworkLoadBalancer, tc.repoGetByUUIDErr
				},
			}

			networkLoadBalancerSvc := inventory.NewNetworkLoadBalancerService(repo, nil, nil, nil, inventory.NetworkLoadBalancerWithNow(func() time.Time {
				return time.Date(2025, 2, 26, 8, 54, 35, 123, time.UTC)
			}))

			// Run test
			networkLoadBalancer, err := networkLoadBalancerSvc.GetByUUID(context.Background(), tc.idArg)

			// Assert
			tc.assertErr(t, err)
			require.Equal(t, tc.repoGetByUUIDNetworkLoadBalancer, networkLoadBalancer)
		})
	}
}

func TestNetworkLoadBalancerService_ResyncByUUID(t *testing.T) {
	tests := []struct {
		name                                                     string
		clusterSvcGetEndpoint                                    provisioning.Endpoint
		clusterSvcGetEndpointErr                                 error
		networkLoadBalancerClientGetNetworkLoadBalancerByName    incusapi.NetworkLoadBalancer
		networkLoadBalancerClientGetNetworkLoadBalancerByNameErr error
		repoGetByUUIDNetworkLoadBalancer                         inventory.NetworkLoadBalancer
		repoGetByUUIDErr                                         error
		repoUpdateByUUIDErr                                      error
		repoDeleteByUUIDErr                                      error

		assertErr require.ErrorAssertionFunc
	}{
		{
			name: "success",
			repoGetByUUIDNetworkLoadBalancer: inventory.NetworkLoadBalancer{
				UUID:        uuidgen.FromPattern(t, "1"),
				Cluster:     "one",
				Name:        "one",
				NetworkName: "network",
			},
			clusterSvcGetEndpoint: provisioning.ClusterEndpoint{
				{
					ConnectionURL:      "https://server-one/",
					Certificate:        "cert",
					ClusterCertificate: ptr.To("cluster-cert"),
				},
			},
			networkLoadBalancerClientGetNetworkLoadBalancerByName: incusapi.NetworkLoadBalancer{
				ListenAddress: "networkLoadBalancer one",
			},

			assertErr: require.NoError,
		},
		{
			name: "success - networkLoadBalancer get by name - not found",
			repoGetByUUIDNetworkLoadBalancer: inventory.NetworkLoadBalancer{
				UUID:        uuidgen.FromPattern(t, "1"),
				Cluster:     "one",
				Name:        "one",
				NetworkName: "network",
			},
			clusterSvcGetEndpoint: provisioning.ClusterEndpoint{
				{
					ConnectionURL:      "https://server-one/",
					Certificate:        "cert",
					ClusterCertificate: ptr.To("cluster-cert"),
				},
			},
			networkLoadBalancerClientGetNetworkLoadBalancerByNameErr: domain.ErrNotFound,

			assertErr: require.NoError,
		},
		{
			name:             "error - networkLoadBalancer get by UUID",
			repoGetByUUIDErr: boom.Error,

			assertErr: boom.ErrorIs,
		},
		{
			name: "error - cluster get by ID",
			repoGetByUUIDNetworkLoadBalancer: inventory.NetworkLoadBalancer{
				UUID:        uuidgen.FromPattern(t, "1"),
				Cluster:     "one",
				Name:        "one",
				NetworkName: "network",
			},
			clusterSvcGetEndpointErr: boom.Error,

			assertErr: boom.ErrorIs,
		},
		{
			name: "error - networkLoadBalancer get by name",
			repoGetByUUIDNetworkLoadBalancer: inventory.NetworkLoadBalancer{
				UUID:        uuidgen.FromPattern(t, "1"),
				Cluster:     "one",
				Name:        "one",
				NetworkName: "network",
			},
			clusterSvcGetEndpoint: provisioning.ClusterEndpoint{
				{
					ConnectionURL:      "https://server-one/",
					Certificate:        "cert",
					ClusterCertificate: ptr.To("cluster-cert"),
				},
			},
			networkLoadBalancerClientGetNetworkLoadBalancerByNameErr: boom.Error,

			assertErr: boom.ErrorIs,
		},
		{
			name: "error - networkLoadBalancer get by name - not found - delete by uuid",
			repoGetByUUIDNetworkLoadBalancer: inventory.NetworkLoadBalancer{
				UUID:        uuidgen.FromPattern(t, "1"),
				Cluster:     "one",
				Name:        "one",
				NetworkName: "network",
			},
			clusterSvcGetEndpoint: provisioning.ClusterEndpoint{
				{
					ConnectionURL:      "https://server-one/",
					Certificate:        "cert",
					ClusterCertificate: ptr.To("cluster-cert"),
				},
			},
			networkLoadBalancerClientGetNetworkLoadBalancerByNameErr: domain.ErrNotFound,
			repoDeleteByUUIDErr: boom.Error,

			assertErr: boom.ErrorIs,
		},
		{
			name: "error - validate",
			repoGetByUUIDNetworkLoadBalancer: inventory.NetworkLoadBalancer{
				UUID:        uuidgen.FromPattern(t, "1"),
				Cluster:     "one",
				Name:        "", // invalid
				NetworkName: "network",
			},
			clusterSvcGetEndpoint: provisioning.ClusterEndpoint{
				{
					ConnectionURL:      "https://server-one/",
					Certificate:        "cert",
					ClusterCertificate: ptr.To("cluster-cert"),
				},
			},
			networkLoadBalancerClientGetNetworkLoadBalancerByName: incusapi.NetworkLoadBalancer{
				ListenAddress: "networkLoadBalancer one",
			},

			assertErr: func(tt require.TestingT, err error, a ...any) {
				var verr domain.ErrValidation
				require.ErrorAs(tt, err, &verr, a...)
			},
		},
		{
			name: "error - update by UUID",
			repoGetByUUIDNetworkLoadBalancer: inventory.NetworkLoadBalancer{
				UUID:        uuidgen.FromPattern(t, "1"),
				Cluster:     "one",
				Name:        "one",
				NetworkName: "network",
			},
			clusterSvcGetEndpoint: provisioning.ClusterEndpoint{
				{
					ConnectionURL:      "https://server-one/",
					Certificate:        "cert",
					ClusterCertificate: ptr.To("cluster-cert"),
				},
			},
			networkLoadBalancerClientGetNetworkLoadBalancerByName: incusapi.NetworkLoadBalancer{
				ListenAddress: "networkLoadBalancer one",
			},
			repoUpdateByUUIDErr: boom.Error,

			assertErr: boom.ErrorIs,
		},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			// Setup
			repo := &repoMock.NetworkLoadBalancerRepoMock{
				GetByUUIDFunc: func(ctx context.Context, id uuid.UUID) (inventory.NetworkLoadBalancer, error) {
					return tc.repoGetByUUIDNetworkLoadBalancer, tc.repoGetByUUIDErr
				},
				UpdateByUUIDFunc: func(ctx context.Context, networkLoadBalancer inventory.NetworkLoadBalancer) (inventory.NetworkLoadBalancer, error) {
					require.Equal(t, time.Date(2025, 2, 26, 8, 54, 35, 123, time.UTC), networkLoadBalancer.LastUpdated)
					return inventory.NetworkLoadBalancer{}, tc.repoUpdateByUUIDErr
				},
				DeleteByUUIDFunc: func(ctx context.Context, id uuid.UUID) error {
					return tc.repoDeleteByUUIDErr
				},
			}

			clusterSvc := &serviceMock.ProvisioningClusterServiceMock{
				GetEndpointFunc: func(ctx context.Context, name string) (provisioning.Endpoint, error) {
					require.Equal(t, "one", name)
					return tc.clusterSvcGetEndpoint, tc.clusterSvcGetEndpointErr
				},
			}

			networkLoadBalancerClient := &serverMock.NetworkLoadBalancerServerClientMock{
				GetNetworkLoadBalancerByNameFunc: func(ctx context.Context, endpoint provisioning.Endpoint, networkName string, networkLoadBalancerName string) (incusapi.NetworkLoadBalancer, error) {
					require.Equal(t, tc.repoGetByUUIDNetworkLoadBalancer.Name, networkLoadBalancerName)
					require.Equal(t, "network", networkName)
					return tc.networkLoadBalancerClientGetNetworkLoadBalancerByName, tc.networkLoadBalancerClientGetNetworkLoadBalancerByNameErr
				},
			}

			networkLoadBalancerSvc := inventory.NewNetworkLoadBalancerService(repo, clusterSvc, networkLoadBalancerClient, nil, inventory.NetworkLoadBalancerWithNow(func() time.Time {
				return time.Date(2025, 2, 26, 8, 54, 35, 123, time.UTC)
			}))

			// Run test
			err := networkLoadBalancerSvc.ResyncByUUID(context.Background(), uuidgen.FromPattern(t, "1"))

			// Assert
			tc.assertErr(t, err)
		})
	}
}

func TestNetworkLoadBalancerService_ResyncByName(t *testing.T) {
	tests := []struct {
		name                                                     string
		argClusterName                                           string
		argLifecycleEvent                                        domain.LifecycleEvent
		repoGetAllUUIDsWithFilterUUIDs                           []uuid.UUID
		repoGetAllUUIDsWithFilterErr                             error
		clusterSvcGetEndpoint                                    provisioning.Endpoint
		clusterSvcGetEndpointErr                                 error
		networkLoadBalancerClientGetNetworkLoadBalancerByName    incusapi.NetworkLoadBalancer
		networkLoadBalancerClientGetNetworkLoadBalancerByNameErr error
		serviceOptions                                           []inventory.NetworkLoadBalancerServiceOption
		repoCreateErr                                            error
		repoGetByUUIDNetworkLoadBalancer                         inventory.NetworkLoadBalancer
		repoGetByUUIDErr                                         error
		repoDeleteByUUIDErr                                      error

		assertErr require.ErrorAssertionFunc
	}{
		{
			name:           "success - not responsible",
			argClusterName: "cluster",
			argLifecycleEvent: domain.LifecycleEvent{
				ResourceType: "invalid",
			},

			assertErr: require.NoError,
		},
		{
			name:           "success - create",
			argClusterName: "cluster",
			argLifecycleEvent: domain.LifecycleEvent{
				ResourceType: "network-load-balancer",
				Operation:    domain.LifecycleOperationCreate,
				Source: domain.LifecycleSource{
					ParentName: "network",
					Name:       "network_load_balancer",
				},
			},
			repoGetAllUUIDsWithFilterUUIDs: []uuid.UUID{},
			clusterSvcGetEndpoint: provisioning.ClusterEndpoint{
				{
					ConnectionURL:        "https://server01/",
					Certificate:          "cert",
					Cluster:              ptr.To("cluster"),
					ClusterConnectionURL: ptr.To("https://cluster/"),
					ClusterCertificate:   ptr.To("cluster-cert"),
				},
			},
			networkLoadBalancerClientGetNetworkLoadBalancerByName: incusapi.NetworkLoadBalancer{
				ListenAddress: "network_load_balancer",
			},

			assertErr: require.NoError,
		},
		{
			name:           "success - delete existing",
			argClusterName: "cluster",
			argLifecycleEvent: domain.LifecycleEvent{
				ResourceType: "network-load-balancer",
				Operation:    domain.LifecycleOperationDelete,
				Source: domain.LifecycleSource{
					ParentName: "network",
					Name:       "network_load_balancer",
				},
			},
			repoGetAllUUIDsWithFilterUUIDs: []uuid.UUID{
				uuidgen.FromPattern(t, "1"),
			},

			assertErr: require.NoError,
		},
		{
			name:           "success - rename",
			argClusterName: "cluster",
			argLifecycleEvent: domain.LifecycleEvent{
				ResourceType: "network-load-balancer",
				Operation:    domain.LifecycleOperationRename,
				Source: domain.LifecycleSource{
					ParentName: "network",
					Name:       "network_load_balancer-new",
					OldName:    "network_load_balancer",
				},
			},
			repoGetAllUUIDsWithFilterUUIDs: []uuid.UUID{
				uuidgen.FromPattern(t, "1"),
			},
			clusterSvcGetEndpoint: provisioning.ClusterEndpoint{
				{
					ConnectionURL:        "https://server01/",
					Certificate:          "cert",
					Cluster:              ptr.To("cluster"),
					ClusterConnectionURL: ptr.To("https://cluster/"),
					ClusterCertificate:   ptr.To("cluster-cert"),
				},
			},
			networkLoadBalancerClientGetNetworkLoadBalancerByName: incusapi.NetworkLoadBalancer{
				ListenAddress: "network_load_balancer-new",
			},

			assertErr: require.NoError,
		},
		{
			name:           "success - update of non existing element",
			argClusterName: "cluster",
			argLifecycleEvent: domain.LifecycleEvent{
				ResourceType: "network-load-balancer",
				Operation:    domain.LifecycleOperationUpdate,
				Source: domain.LifecycleSource{
					ParentName: "network",
					Name:       "network_load_balancer",
				},
			},
			repoGetAllUUIDsWithFilterUUIDs: []uuid.UUID{},
			clusterSvcGetEndpoint: provisioning.ClusterEndpoint{
				{
					ConnectionURL:        "https://server01/",
					Certificate:          "cert",
					Cluster:              ptr.To("cluster"),
					ClusterConnectionURL: ptr.To("https://cluster/"),
					ClusterCertificate:   ptr.To("cluster-cert"),
				},
			},
			networkLoadBalancerClientGetNetworkLoadBalancerByName: incusapi.NetworkLoadBalancer{
				ListenAddress: "network_load_balancer filtered", // matches filter
			},
			serviceOptions: []inventory.NetworkLoadBalancerServiceOption{
				inventory.NetworkLoadBalancerWithSyncFilter(func(networkLoadBalancer inventory.NetworkLoadBalancer) bool {
					return networkLoadBalancer.Name == "network_load_balancer filtered"
				}),
			},

			assertErr: require.NoError,
		},
		{
			name:           "success - update existing",
			argClusterName: "cluster",
			argLifecycleEvent: domain.LifecycleEvent{
				ResourceType: "network-load-balancer",
				Operation:    domain.LifecycleOperationUpdate,
				Source: domain.LifecycleSource{
					ParentName: "network",
					Name:       "network_load_balancer",
				},
			},
			repoGetAllUUIDsWithFilterUUIDs: []uuid.UUID{
				uuidgen.FromPattern(t, "1"),
			},
			repoGetByUUIDNetworkLoadBalancer: inventory.NetworkLoadBalancer{
				UUID:        uuidgen.FromPattern(t, "1"),
				Cluster:     "cluster",
				Name:        "network_load_balancer",
				NetworkName: "network",
			},
			clusterSvcGetEndpoint: provisioning.ClusterEndpoint{
				{
					ConnectionURL:        "https://server01/",
					Certificate:          "cert",
					Cluster:              ptr.To("cluster"),
					ClusterConnectionURL: ptr.To("https://cluster/"),
					ClusterCertificate:   ptr.To("cluster-cert"),
				},
			},
			networkLoadBalancerClientGetNetworkLoadBalancerByName: incusapi.NetworkLoadBalancer{
				ListenAddress: "network_load_balancer",
			},

			assertErr: require.NoError,
		},
		{
			name:           "error - invalid lifecycle operation",
			argClusterName: "cluster",
			argLifecycleEvent: domain.LifecycleEvent{
				ResourceType: "network-load-balancer",
				Operation:    domain.LifecycleOperation("invalid"), // invalid
			},

			assertErr: func(tt require.TestingT, err error, i ...interface{}) {
				require.ErrorContains(tt, err, "Invalid lifecycle operation")
			},
		},
		{
			name:           "error - create - clusterSvc.GetEndpoint",
			argClusterName: "cluster",
			argLifecycleEvent: domain.LifecycleEvent{
				ResourceType: "network-load-balancer",
				Operation:    domain.LifecycleOperationCreate,
				Source: domain.LifecycleSource{
					ParentName: "network",
					Name:       "network_load_balancer",
				},
			},
			clusterSvcGetEndpointErr: boom.Error,

			assertErr: boom.ErrorIs,
		},
		{
			name:           "error - create - client.GetNetworkLoadBalancerByName",
			argClusterName: "cluster",
			argLifecycleEvent: domain.LifecycleEvent{
				ResourceType: "network-load-balancer",
				Operation:    domain.LifecycleOperationCreate,
				Source: domain.LifecycleSource{
					ParentName: "network",
					Name:       "network_load_balancer",
				},
			},
			clusterSvcGetEndpoint: provisioning.ClusterEndpoint{
				{
					ConnectionURL:        "https://server01/",
					Certificate:          "cert",
					Cluster:              ptr.To("cluster"),
					ClusterConnectionURL: ptr.To("https://cluster/"),
					ClusterCertificate:   ptr.To("cluster-cert"),
				},
			},
			networkLoadBalancerClientGetNetworkLoadBalancerByNameErr: boom.Error,

			assertErr: boom.ErrorIs,
		},
		{
			name:           "error - create - validate",
			argClusterName: "cluster",
			argLifecycleEvent: domain.LifecycleEvent{
				ResourceType: "network-load-balancer",
				Operation:    domain.LifecycleOperationCreate,
				Source: domain.LifecycleSource{
					ParentName: "network",
					Name:       "network_load_balancer",
				},
			},
			clusterSvcGetEndpoint: provisioning.ClusterEndpoint{
				{
					ConnectionURL:        "https://server01/",
					Certificate:          "cert",
					Cluster:              ptr.To("cluster"),
					ClusterConnectionURL: ptr.To("https://cluster/"),
					ClusterCertificate:   ptr.To("cluster-cert"),
				},
			},
			networkLoadBalancerClientGetNetworkLoadBalancerByName: incusapi.NetworkLoadBalancer{
				ListenAddress: "", // invalid
			},

			assertErr: func(tt require.TestingT, err error, a ...any) {
				var verr domain.ErrValidation
				require.ErrorAs(tt, err, &verr, a...)
			},
		},
		{
			name:           "error - create - repo.Create",
			argClusterName: "cluster",
			argLifecycleEvent: domain.LifecycleEvent{
				ResourceType: "network-load-balancer",
				Operation:    domain.LifecycleOperationCreate,
				Source: domain.LifecycleSource{
					ParentName: "network",
					Name:       "network_load_balancer",
				},
			},
			clusterSvcGetEndpoint: provisioning.ClusterEndpoint{
				{
					ConnectionURL:        "https://server01/",
					Certificate:          "cert",
					Cluster:              ptr.To("cluster"),
					ClusterConnectionURL: ptr.To("https://cluster/"),
					ClusterCertificate:   ptr.To("cluster-cert"),
				},
			},
			networkLoadBalancerClientGetNetworkLoadBalancerByName: incusapi.NetworkLoadBalancer{
				ListenAddress: "network_load_balancer",
			},
			repoCreateErr: boom.Error,

			assertErr: boom.ErrorIs,
		},
		{
			name:           "error - delete - repo.GetAllUUIDsWithFilter",
			argClusterName: "cluster",
			argLifecycleEvent: domain.LifecycleEvent{
				ResourceType: "network-load-balancer",
				Operation:    domain.LifecycleOperationDelete,
				Source: domain.LifecycleSource{
					ParentName: "network",
					Name:       "network_load_balancer",
				},
			},
			repoGetAllUUIDsWithFilterErr: boom.Error,

			assertErr: boom.ErrorIs,
		},
		{
			name:           "error - delete - repo.GetAllUUIDsWithFilter - not found",
			argClusterName: "cluster",
			argLifecycleEvent: domain.LifecycleEvent{
				ResourceType: "network-load-balancer",
				Operation:    domain.LifecycleOperationDelete,
				Source: domain.LifecycleSource{
					ParentName: "network",
					Name:       "network_load_balancer",
				},
			},
			repoGetAllUUIDsWithFilterErr: domain.ErrNotFound,

			assertErr: require.NoError,
		},
		{
			name:           "error - delete - DeleteByUUID",
			argClusterName: "cluster",
			argLifecycleEvent: domain.LifecycleEvent{
				ResourceType: "network-load-balancer",
				Operation:    domain.LifecycleOperationDelete,
				Source: domain.LifecycleSource{
					ParentName: "network",
					Name:       "network_load_balancer",
				},
			},
			repoGetAllUUIDsWithFilterUUIDs: []uuid.UUID{
				uuidgen.FromPattern(t, "1"),
			},
			repoDeleteByUUIDErr: boom.Error,

			assertErr: boom.ErrorIs,
		},
		{
			name:           "error - rename",
			argClusterName: "cluster",
			argLifecycleEvent: domain.LifecycleEvent{
				ResourceType: "network-load-balancer",
				Operation:    domain.LifecycleOperationRename,
				Source: domain.LifecycleSource{
					ParentName: "network",
					Name:       "network_load_balancer-new",
					OldName:    "network_load_balancer",
				},
			},
			repoGetAllUUIDsWithFilterUUIDs: []uuid.UUID{
				uuidgen.FromPattern(t, "1"),
			},
			clusterSvcGetEndpoint: provisioning.ClusterEndpoint{
				{
					ConnectionURL:        "https://server01/",
					Certificate:          "cert",
					Cluster:              ptr.To("cluster"),
					ClusterConnectionURL: ptr.To("https://cluster/"),
					ClusterCertificate:   ptr.To("cluster-cert"),
				},
			},
			networkLoadBalancerClientGetNetworkLoadBalancerByName: incusapi.NetworkLoadBalancer{
				ListenAddress: "network_load_balancer-new",
			},
			repoDeleteByUUIDErr: boom.Error,

			assertErr: boom.ErrorIs,
		},
		{
			name:           "error - update - repo.GetAllUUIDsWithFilter",
			argClusterName: "cluster",
			argLifecycleEvent: domain.LifecycleEvent{
				ResourceType: "network-load-balancer",
				Operation:    domain.LifecycleOperationUpdate,
				Source: domain.LifecycleSource{
					ParentName: "network",
					Name:       "network_load_balancer",
				},
			},
			repoGetAllUUIDsWithFilterErr: boom.Error,

			assertErr: require.Error,
		},
		{
			name:           "error - update - ResyncByUUID",
			argClusterName: "cluster",
			argLifecycleEvent: domain.LifecycleEvent{
				ResourceType: "network-load-balancer",
				Operation:    domain.LifecycleOperationUpdate,
				Source: domain.LifecycleSource{
					ParentName: "network",
					Name:       "network_load_balancer",
				},
			},
			repoGetAllUUIDsWithFilterUUIDs: []uuid.UUID{
				uuidgen.FromPattern(t, "1"),
			},
			repoGetByUUIDErr: boom.Error,

			assertErr: boom.ErrorIs,
		},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			// Setup
			repo := &repoMock.NetworkLoadBalancerRepoMock{
				GetAllUUIDsWithFilterFunc: func(ctx context.Context, filter inventory.NetworkLoadBalancerFilter) ([]uuid.UUID, error) {
					require.Equal(t, tc.argClusterName, *filter.Cluster)
					require.Equal(t, tc.argLifecycleEvent.Source.ParentName, *filter.NetworkName)
					require.Contains(t, tc.argLifecycleEvent.Source.Name, *filter.Name)
					return tc.repoGetAllUUIDsWithFilterUUIDs, tc.repoGetAllUUIDsWithFilterErr
				},
				CreateFunc: func(ctx context.Context, networkLoadBalancer inventory.NetworkLoadBalancer) (inventory.NetworkLoadBalancer, error) {
					require.Equal(t, tc.argClusterName, networkLoadBalancer.Cluster)
					require.Equal(t, tc.argLifecycleEvent.Source.ParentName, networkLoadBalancer.NetworkName)
					require.Equal(t, tc.argLifecycleEvent.Source.Name, networkLoadBalancer.Name)
					return inventory.NetworkLoadBalancer{}, tc.repoCreateErr
				},
				GetByUUIDFunc: func(ctx context.Context, id uuid.UUID) (inventory.NetworkLoadBalancer, error) {
					return tc.repoGetByUUIDNetworkLoadBalancer, tc.repoGetByUUIDErr
				},
				UpdateByUUIDFunc: func(ctx context.Context, networkLoadBalancer inventory.NetworkLoadBalancer) (inventory.NetworkLoadBalancer, error) {
					require.Equal(t, time.Date(2025, 2, 26, 8, 54, 35, 123, time.UTC), networkLoadBalancer.LastUpdated)
					return inventory.NetworkLoadBalancer{}, nil
				},
				DeleteByUUIDFunc: func(ctx context.Context, id uuid.UUID) error {
					return tc.repoDeleteByUUIDErr
				},
			}

			clusterSvc := &serviceMock.ProvisioningClusterServiceMock{
				GetEndpointFunc: func(ctx context.Context, name string) (provisioning.Endpoint, error) {
					require.Equal(t, tc.argClusterName, name)
					return tc.clusterSvcGetEndpoint, tc.clusterSvcGetEndpointErr
				},
			}

			networkLoadBalancerClient := &serverMock.NetworkLoadBalancerServerClientMock{
				GetNetworkLoadBalancerByNameFunc: func(ctx context.Context, endpoint provisioning.Endpoint, networkName string, networkLoadBalancerName string) (incusapi.NetworkLoadBalancer, error) {
					clusterName, err := endpoint.GetServerName()
					require.NoError(t, err)
					require.Equal(t, tc.argClusterName, clusterName)
					require.Equal(t, tc.argLifecycleEvent.Source.ParentName, networkName)
					require.Equal(t, tc.argLifecycleEvent.Source.Name, networkLoadBalancerName)
					return tc.networkLoadBalancerClientGetNetworkLoadBalancerByName, tc.networkLoadBalancerClientGetNetworkLoadBalancerByNameErr
				},
			}

			networkLoadBalancerSvc := inventory.NewNetworkLoadBalancerService(repo, clusterSvc, networkLoadBalancerClient, nil,
				append(tc.serviceOptions,
					inventory.NetworkLoadBalancerWithNow(func() time.Time {
						return time.Date(2025, 2, 26, 8, 54, 35, 123, time.UTC)
					}),
				)...,
			)

			// Run test
			err := networkLoadBalancerSvc.ResyncByName(context.Background(), tc.argClusterName, tc.argLifecycleEvent)

			// Assert
			tc.assertErr(t, err)
		})
	}
}

func TestNetworkLoadBalancerService_SyncAll(t *testing.T) {
	// Includes also SyncCluster
	tests := []struct {
		name                                                string
		clusterSvcGetEndpoint                               provisioning.Endpoint
		clusterSvcGetEndpointErr                            error
		networkClientGetNetworks                            []incusapi.Network
		networkClientGetNetworksErr                         error
		networkLoadBalancerClientGetNetworkLoadBalancers    []incusapi.NetworkLoadBalancer
		networkLoadBalancerClientGetNetworkLoadBalancersErr error
		repoDeleteWithFilterErr                             error
		repoCreateErr                                       error
		serviceOptions                                      []inventory.NetworkLoadBalancerServiceOption

		assertErr require.ErrorAssertionFunc
	}{
		{
			name: "success",
			clusterSvcGetEndpoint: provisioning.ClusterEndpoint{
				{
					ConnectionURL:      "https://server-one/",
					Certificate:        "cert",
					ClusterCertificate: ptr.To("cluster-cert"),
				},
			},
			networkClientGetNetworks: []incusapi.Network{
				{
					Name: "network one",
				},
			},
			networkLoadBalancerClientGetNetworkLoadBalancers: []incusapi.NetworkLoadBalancer{
				{
					ListenAddress: "networkLoadBalancer one",
				},
			},

			assertErr: require.NoError,
		},
		{
			name: "success - with parent filter",
			clusterSvcGetEndpoint: provisioning.ClusterEndpoint{
				{
					ConnectionURL:      "https://server-one/",
					Certificate:        "cert",
					ClusterCertificate: ptr.To("cluster-cert"),
				},
			},
			networkClientGetNetworks: []incusapi.Network{
				{
					Name: "network one",
				},
				{
					Name: "filtered",
				},
			},
			networkLoadBalancerClientGetNetworkLoadBalancers: []incusapi.NetworkLoadBalancer{
				{
					ListenAddress: "networkLoadBalancer one",
				},
			},
			serviceOptions: []inventory.NetworkLoadBalancerServiceOption{
				inventory.NetworkLoadBalancerWithParentFilter(func(parent incusapi.Network) bool {
					return parent.Name == "filtered"
				}),
			},

			assertErr: require.NoError,
		},
		{
			name: "success - with sync filter",
			clusterSvcGetEndpoint: provisioning.ClusterEndpoint{
				{
					ConnectionURL:      "https://server-one/",
					Certificate:        "cert",
					ClusterCertificate: ptr.To("cluster-cert"),
				},
			},
			networkClientGetNetworks: []incusapi.Network{
				{
					Name: "network one",
				},
			},
			networkLoadBalancerClientGetNetworkLoadBalancers: []incusapi.NetworkLoadBalancer{
				{
					ListenAddress: "networkLoadBalancer one",
				},
				{
					ListenAddress: "networkLoadBalancer filtered",
				},
			},
			serviceOptions: []inventory.NetworkLoadBalancerServiceOption{
				inventory.NetworkLoadBalancerWithSyncFilter(func(networkLoadBalancer inventory.NetworkLoadBalancer) bool {
					return networkLoadBalancer.Name == "networkLoadBalancer filtered"
				}),
			},

			assertErr: require.NoError,
		},
		{
			name:                     "error - cluster service get by ID",
			clusterSvcGetEndpointErr: boom.Error,

			assertErr: boom.ErrorIs,
		},
		{
			name: "error - network client get Networks",
			clusterSvcGetEndpoint: provisioning.ClusterEndpoint{
				{
					ConnectionURL:      "https://server-one/",
					Certificate:        "cert",
					ClusterCertificate: ptr.To("cluster-cert"),
				},
			},
			networkClientGetNetworksErr: boom.Error,

			assertErr: boom.ErrorIs,
		},
		{
			name: "error - networkLoadBalancer client get NetworkLoadBalancers",
			clusterSvcGetEndpoint: provisioning.ClusterEndpoint{
				{
					ConnectionURL:      "https://server-one/",
					Certificate:        "cert",
					ClusterCertificate: ptr.To("cluster-cert"),
				},
			},
			networkClientGetNetworks: []incusapi.Network{
				{
					Name: "network one",
				},
			},
			networkLoadBalancerClientGetNetworkLoadBalancersErr: boom.Error,

			assertErr: boom.ErrorIs,
		},
		{
			name: "error - network_load_balancers delete by cluster ID",
			clusterSvcGetEndpoint: provisioning.ClusterEndpoint{
				{
					ConnectionURL:      "https://server-one/",
					Certificate:        "cert",
					ClusterCertificate: ptr.To("cluster-cert"),
				},
			},
			networkClientGetNetworks: []incusapi.Network{
				{
					Name: "network one",
				},
			},
			networkLoadBalancerClientGetNetworkLoadBalancers: []incusapi.NetworkLoadBalancer{
				{
					ListenAddress: "networkLoadBalancer one",
				},
			},
			repoDeleteWithFilterErr: boom.Error,

			assertErr: boom.ErrorIs,
		},
		{
			name: "error - validate",
			clusterSvcGetEndpoint: provisioning.ClusterEndpoint{
				{
					ConnectionURL:      "https://server-one/",
					Certificate:        "cert",
					ClusterCertificate: ptr.To("cluster-cert"),
				},
			},
			networkClientGetNetworks: []incusapi.Network{
				{
					Name: "network one",
				},
			},
			networkLoadBalancerClientGetNetworkLoadBalancers: []incusapi.NetworkLoadBalancer{
				{
					ListenAddress: "", // invalid
				},
			},

			assertErr: func(tt require.TestingT, err error, a ...any) {
				var verr domain.ErrValidation
				require.ErrorAs(tt, err, &verr, a...)
			},
		},
		{
			name: "error - networkLoadBalancer create",
			clusterSvcGetEndpoint: provisioning.ClusterEndpoint{
				{
					ConnectionURL:      "https://server-one/",
					Certificate:        "cert",
					ClusterCertificate: ptr.To("cluster-cert"),
				},
			},
			networkClientGetNetworks: []incusapi.Network{
				{
					Name: "network one",
				},
			},
			networkLoadBalancerClientGetNetworkLoadBalancers: []incusapi.NetworkLoadBalancer{
				{
					ListenAddress: "networkLoadBalancer one",
				},
			},
			repoCreateErr: boom.Error,

			assertErr: boom.ErrorIs,
		},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			// Setup
			repo := &repoMock.NetworkLoadBalancerRepoMock{
				DeleteWithFilterFunc: func(ctx context.Context, filter inventory.NetworkLoadBalancerFilter) error {
					return tc.repoDeleteWithFilterErr
				},
				CreateFunc: func(ctx context.Context, networkLoadBalancer inventory.NetworkLoadBalancer) (inventory.NetworkLoadBalancer, error) {
					return inventory.NetworkLoadBalancer{}, tc.repoCreateErr
				},
			}

			clusterSvc := &serviceMock.ProvisioningClusterServiceMock{
				GetEndpointFunc: func(ctx context.Context, name string) (provisioning.Endpoint, error) {
					return tc.clusterSvcGetEndpoint, tc.clusterSvcGetEndpointErr
				},
			}

			networkClient := &serverMock.NetworkServerClientMock{
				GetNetworksFunc: func(ctx context.Context, endpoint provisioning.Endpoint) ([]incusapi.Network, error) {
					return tc.networkClientGetNetworks, tc.networkClientGetNetworksErr
				},
			}

			networkLoadBalancerClient := &serverMock.NetworkLoadBalancerServerClientMock{
				GetNetworkLoadBalancersFunc: func(ctx context.Context, endpoint provisioning.Endpoint, networkName string) ([]incusapi.NetworkLoadBalancer, error) {
					return tc.networkLoadBalancerClientGetNetworkLoadBalancers, tc.networkLoadBalancerClientGetNetworkLoadBalancersErr
				},
			}

			networkLoadBalancerSvc := inventory.NewNetworkLoadBalancerService(repo, clusterSvc, networkLoadBalancerClient, networkClient,
				append(
					tc.serviceOptions,
					inventory.NetworkLoadBalancerWithNow(func() time.Time {
						return time.Date(2025, 2, 26, 8, 54, 35, 123, time.UTC)
					}),
				)...,
			)

			// Run test
			err := networkLoadBalancerSvc.SyncCluster(context.Background(), "one")

			// Assert
			tc.assertErr(t, err)
		})
	}
}
