// Code generated by generate-inventory; DO NOT EDIT.

package inventory

import (
	"context"
	"errors"
	"fmt"
	"time"

	"github.com/expr-lang/expr"
	"github.com/expr-lang/expr/vm"
	"github.com/google/uuid"

	"github.com/FuturFusion/operations-center/internal/domain"
	"github.com/FuturFusion/operations-center/internal/transaction"
)

type networkIntegrationService struct {
	repo                     NetworkIntegrationRepo
	clusterSvc               ProvisioningClusterService
	networkIntegrationClient NetworkIntegrationServerClient

	clusterSyncFilterFunc func(networkIntegration NetworkIntegration) bool

	now func() time.Time
}

var _ NetworkIntegrationService = &networkIntegrationService{}

type NetworkIntegrationServiceOption func(s *networkIntegrationService)

func NetworkIntegrationWithSyncFilter(clusterSyncFilterFunc func(networkIntegration NetworkIntegration) bool) NetworkIntegrationServiceOption {
	return func(s *networkIntegrationService) {
		s.clusterSyncFilterFunc = clusterSyncFilterFunc
	}
}

func NewNetworkIntegrationService(repo NetworkIntegrationRepo, clusterSvc ProvisioningClusterService, client NetworkIntegrationServerClient, opts ...NetworkIntegrationServiceOption) networkIntegrationService {
	networkIntegrationSvc := networkIntegrationService{
		repo:                     repo,
		clusterSvc:               clusterSvc,
		networkIntegrationClient: client,

		clusterSyncFilterFunc: func(networkIntegration NetworkIntegration) bool {
			return false
		},

		now: time.Now,
	}

	for _, opt := range opts {
		opt(&networkIntegrationSvc)
	}

	return networkIntegrationSvc
}

func (s networkIntegrationService) GetAllWithFilter(ctx context.Context, filter NetworkIntegrationFilter) (NetworkIntegrations, error) {
	var filterExpression *vm.Program
	var err error

	if filter.Expression != nil {
		filterExpression, err = expr.Compile(*filter.Expression, []expr.Option{expr.Env(ToExprNetworkIntegration(NetworkIntegration{}))}...)
		if err != nil {
			return nil, err
		}
	}

	networkIntegrations, err := s.repo.GetAllWithFilter(ctx, filter)
	if err != nil {
		return nil, err
	}

	var filteredNetworkIntegrations NetworkIntegrations
	if filter.Expression != nil {
		for _, networkIntegration := range networkIntegrations {
			output, err := expr.Run(filterExpression, ToExprNetworkIntegration(networkIntegration))
			if err != nil {
				return nil, err
			}

			result, ok := output.(bool)
			if !ok {
				return nil, fmt.Errorf("Filter expression %q does not evaluate to boolean result: %v", *filter.Expression, output)
			}

			if result {
				filteredNetworkIntegrations = append(filteredNetworkIntegrations, networkIntegration)
			}
		}

		return filteredNetworkIntegrations, nil
	}

	return networkIntegrations, nil
}

func (s networkIntegrationService) GetAllUUIDsWithFilter(ctx context.Context, filter NetworkIntegrationFilter) ([]uuid.UUID, error) {
	var filterExpression *vm.Program
	var err error

	type Env struct {
		UUID string `expr:"uuid"`
	}

	if filter.Expression != nil {
		filterExpression, err = expr.Compile(*filter.Expression, []expr.Option{expr.Env(Env{})}...)
		if err != nil {
			return nil, err
		}
	}

	networkIntegrationsUUIDs, err := s.repo.GetAllUUIDsWithFilter(ctx, filter)
	if err != nil {
		return nil, err
	}

	var filteredNetworkIntegrationsUUIDs []uuid.UUID
	if filter.Expression != nil {
		for _, networkIntegrationUUID := range networkIntegrationsUUIDs {
			output, err := expr.Run(filterExpression, Env{networkIntegrationUUID.String()})
			if err != nil {
				return nil, err
			}

			result, ok := output.(bool)
			if !ok {
				return nil, fmt.Errorf("Filter expression %q does not evaluate to boolean result: %v", *filter.Expression, output)
			}

			if result {
				filteredNetworkIntegrationsUUIDs = append(filteredNetworkIntegrationsUUIDs, networkIntegrationUUID)
			}
		}

		return filteredNetworkIntegrationsUUIDs, nil
	}

	return networkIntegrationsUUIDs, nil
}

func (s networkIntegrationService) GetByUUID(ctx context.Context, id uuid.UUID) (NetworkIntegration, error) {
	return s.repo.GetByUUID(ctx, id)
}

func (s networkIntegrationService) ResyncByUUID(ctx context.Context, id uuid.UUID) error {
	err := transaction.Do(ctx, func(ctx context.Context) error {
		networkIntegration, err := s.repo.GetByUUID(ctx, id)
		if err != nil {
			return err
		}

		endpoint, err := s.clusterSvc.GetEndpoint(ctx, networkIntegration.Cluster)
		if err != nil {
			return err
		}

		retrievedNetworkIntegration, err := s.networkIntegrationClient.GetNetworkIntegrationByName(ctx, endpoint, networkIntegration.Name)
		if errors.Is(err, domain.ErrNotFound) {
			err = s.repo.DeleteByUUID(ctx, networkIntegration.UUID)
			if err != nil {
				return fmt.Errorf(`Failed to delete network_integration %q from cluster %q: %w`, networkIntegration.UUID.String(), networkIntegration.Cluster, err)
			}

			return nil
		}

		if err != nil {
			return err
		}

		networkIntegration.Object = IncusNetworkIntegrationWrapper{retrievedNetworkIntegration}
		networkIntegration.LastUpdated = s.now()
		networkIntegration.DeriveUUID()

		err = networkIntegration.Validate()
		if err != nil {
			return err
		}

		_, err = s.repo.UpdateByUUID(ctx, networkIntegration)
		if err != nil {
			return fmt.Errorf(`Failed to update network_integration %q for cluster %q: %w`, networkIntegration.UUID.String(), networkIntegration.Cluster, err)
		}

		return nil
	})
	if err != nil {
		return err
	}

	return nil
}

func (s networkIntegrationService) ResyncByName(ctx context.Context, clusterName string, event domain.LifecycleEvent) error {
	if event.ResourceType != domain.ResourceTypeNetworkIntegration {
		return nil
	}

	var err error
	switch event.Operation {
	case domain.LifecycleOperationCreate:
		err = s.handleCreateEvent(ctx, clusterName, event)

	case domain.LifecycleOperationDelete:
		err = s.handleDeleteEvent(ctx, clusterName, event)

	case domain.LifecycleOperationRename:
		err = s.handleRenameEvent(ctx, clusterName, event)

	case domain.LifecycleOperationUpdate:
		err = s.handleUpdateEvent(ctx, clusterName, event)

	default:
		err = fmt.Errorf("Invalid lifecycle operation %q", event.Operation)
	}

	if err != nil {
		if errors.Is(err, domain.ErrNotFound) {
			// Ignore "not found" errors.
			return nil
		}

		return fmt.Errorf("Failed to handle lifecycle event: %w", err)
	}

	return nil
}

func (s networkIntegrationService) handleCreateEvent(ctx context.Context, clusterName string, event domain.LifecycleEvent) error {
	endpoint, err := s.clusterSvc.GetEndpoint(ctx, clusterName)
	if err != nil {
		return err
	}

	retrievedNetworkIntegration, err := s.networkIntegrationClient.GetNetworkIntegrationByName(ctx, endpoint, event.Source.Name)
	if err != nil {
		return err
	}

	networkIntegration := NetworkIntegration{
		Cluster:     clusterName,
		Name:        retrievedNetworkIntegration.Name,
		Object:      IncusNetworkIntegrationWrapper{retrievedNetworkIntegration},
		LastUpdated: s.now(),
	}

	networkIntegration.DeriveUUID()

	if s.clusterSyncFilterFunc(networkIntegration) {
		return nil
	}

	err = networkIntegration.Validate()
	if err != nil {
		return err
	}

	_, err = s.repo.Create(ctx, networkIntegration)
	if err != nil {
		return fmt.Errorf(`Failed to create network_integration %q for cluster %q: %w`, networkIntegration.UUID.String(), networkIntegration.Cluster, err)
	}

	return nil
}

func (s networkIntegrationService) handleDeleteEvent(ctx context.Context, clusterName string, event domain.LifecycleEvent) error {
	UUIDs, err := s.repo.GetAllUUIDsWithFilter(ctx, NetworkIntegrationFilter{
		Cluster: &clusterName,
		Name:    &event.Source.Name,
	})
	if err != nil {
		return err
	}

	var errs []error
	for _, UUID := range UUIDs {
		err = s.repo.DeleteByUUID(ctx, UUID)
		if err != nil {
			err = fmt.Errorf(`Failed to delete network_integration %q from cluster %q: %w`, UUID.String(), clusterName, err)
			errs = append(errs, err)
		}
	}

	err = errors.Join(errs...)
	if err != nil {
		return fmt.Errorf("Failed to remove network_integration by name: %w", errors.Join(errs...))
	}

	return nil
}

func (s networkIntegrationService) handleRenameEvent(ctx context.Context, clusterName string, event domain.LifecycleEvent) error {
	deleteEvent := event
	deleteEvent.Source.Name = deleteEvent.Source.OldName

	var errs []error
	err := s.handleDeleteEvent(ctx, clusterName, deleteEvent)
	if err != nil {
		errs = append(errs,
			fmt.Errorf(`Failed to delete network_integration %q from cluster %q: %w`, deleteEvent.Source.Name, clusterName, err),
		)
	}

	err = s.handleCreateEvent(ctx, clusterName, event)
	if err != nil {
		errs = append(errs,
			fmt.Errorf(`Failed to create network_integration %q for cluster %q: %w`, event.Source.Name, clusterName, err),
		)
	}

	err = errors.Join(errs...)
	if err != nil {
		return err
	}

	return nil
}

func (s networkIntegrationService) handleUpdateEvent(ctx context.Context, clusterName string, event domain.LifecycleEvent) error {
	UUIDs, err := s.repo.GetAllUUIDsWithFilter(ctx, NetworkIntegrationFilter{
		Cluster: &clusterName,
		Name:    &event.Source.Name,
	})
	if err != nil {
		return err
	}

	if len(UUIDs) == 0 {
		return s.handleCreateEvent(ctx, clusterName, event)
	}

	var errs []error
	for _, UUID := range UUIDs {
		err := s.ResyncByUUID(ctx, UUID)
		if err != nil {
			err = fmt.Errorf(`Failed to resync network_integration %q for cluster %q: %w`, UUID.String(), clusterName, err)
			errs = append(errs, err)
		}
	}

	err = errors.Join(errs...)
	if err != nil {
		return fmt.Errorf("Failed to resync network_integration by name: %w", errors.Join(errs...))
	}

	return nil
}

func (s networkIntegrationService) SyncCluster(ctx context.Context, name string) error {
	endpoint, err := s.clusterSvc.GetEndpoint(ctx, name)
	if err != nil {
		return err
	}

	retrievedNetworkIntegrations, err := s.networkIntegrationClient.GetNetworkIntegrations(ctx, endpoint)
	if err != nil {
		return err
	}

	err = transaction.Do(ctx, func(ctx context.Context) error {
		err = s.repo.DeleteWithFilter(ctx, NetworkIntegrationFilter{
			Cluster: &name,
		})
		if err != nil && !errors.Is(err, domain.ErrNotFound) {
			return fmt.Errorf(`Failed to delete "network_integration" from cluster %q: %w`, name, err)
		}

		for _, retrievedNetworkIntegration := range retrievedNetworkIntegrations {
			networkIntegration := NetworkIntegration{
				Cluster:     name,
				Name:        retrievedNetworkIntegration.Name,
				Object:      IncusNetworkIntegrationWrapper{retrievedNetworkIntegration},
				LastUpdated: s.now(),
			}

			networkIntegration.DeriveUUID()

			if s.clusterSyncFilterFunc(networkIntegration) {
				continue
			}

			err = networkIntegration.Validate()
			if err != nil {
				return err
			}

			_, err := s.repo.Create(ctx, networkIntegration)
			if err != nil {
				return fmt.Errorf(`Failed to create network_integration %q for cluster %q: %w`, networkIntegration.UUID.String(), name, err)
			}
		}

		return nil
	})
	if err != nil {
		return err
	}

	return nil
}
