// Code generated by generate-inventory; DO NOT EDIT.

package inventory_test

import (
	"testing"

	"github.com/stretchr/testify/require"

	"github.com/FuturFusion/operations-center/internal/domain"
	"github.com/FuturFusion/operations-center/internal/inventory"
	"github.com/FuturFusion/operations-center/internal/ptr"
)

func TestNetworkLoadBalancer_Validate(t *testing.T) {
	tests := []struct {
		name  string
		image inventory.NetworkLoadBalancer

		assertErr require.ErrorAssertionFunc
	}{
		{
			name: "valid",
			image: inventory.NetworkLoadBalancer{
				ID:          1,
				Cluster:     "one",
				NetworkName: "network one",
				Name:        "one",
			},

			assertErr: require.NoError,
		},
		{
			name: "error - invalid cluster ID",
			image: inventory.NetworkLoadBalancer{
				ID:          1,
				Cluster:     "", // invalid
				NetworkName: "network one",
				Name:        "one",
			},

			assertErr: func(tt require.TestingT, err error, a ...any) {
				var verr domain.ErrValidation
				require.ErrorAs(tt, err, &verr, a...)
			},
		},
		{
			name: "error - invalid project name",
			image: inventory.NetworkLoadBalancer{
				ID:          1,
				Cluster:     "one",
				NetworkName: "", // invalid
				Name:        "one",
			},

			assertErr: func(tt require.TestingT, err error, a ...any) {
				var verr domain.ErrValidation
				require.ErrorAs(tt, err, &verr, a...)
			},
		},
		{
			name: "error - invalid name",
			image: inventory.NetworkLoadBalancer{
				ID:          1,
				Cluster:     "one",
				NetworkName: "network one",
				Name:        "", // invalid
			},

			assertErr: func(tt require.TestingT, err error, a ...any) {
				var verr domain.ErrValidation
				require.ErrorAs(tt, err, &verr, a...)
			},
		},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			err := tc.image.Validate()

			tc.assertErr(t, err)
		})
	}
}

func TestNetworkLoadBalancer_Filter(t *testing.T) {
	tests := []struct {
		name   string
		filter inventory.NetworkLoadBalancerFilter

		want string
	}{
		{
			name:   "empty filter",
			filter: inventory.NetworkLoadBalancerFilter{},

			want: ``,
		},
		{
			name: "complete filter",
			filter: inventory.NetworkLoadBalancerFilter{
				Cluster:    ptr.To("cluster"),
				Expression: ptr.To("true"),
			},

			want: `cluster=cluster&filter=true`,
		},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			require.Equal(t, tc.want, tc.filter.String())
		})
	}
}
