// Code generated by generate-inventory; DO NOT EDIT.

package inventory_test

import (
	"context"
	"testing"
	"time"

	"github.com/google/uuid"
	incusapi "github.com/lxc/incus/v6/shared/api"
	"github.com/stretchr/testify/require"

	"github.com/FuturFusion/operations-center/internal/domain"
	"github.com/FuturFusion/operations-center/internal/inventory"
	serviceMock "github.com/FuturFusion/operations-center/internal/inventory/mock"
	repoMock "github.com/FuturFusion/operations-center/internal/inventory/repo/mock"
	serverMock "github.com/FuturFusion/operations-center/internal/inventory/server/mock"
	"github.com/FuturFusion/operations-center/internal/provisioning"
	"github.com/FuturFusion/operations-center/internal/ptr"
	"github.com/FuturFusion/operations-center/internal/testing/boom"
)

func TestNetworkIntegrationService_GetAllWithFilter(t *testing.T) {
	tests := []struct {
		name                    string
		filterExpression        *string
		repoGetAllWithFilter    inventory.NetworkIntegrations
		repoGetAllWithFilterErr error

		assertErr require.ErrorAssertionFunc
		count     int
	}{
		{
			name: "success - no filter expression",
			repoGetAllWithFilter: inventory.NetworkIntegrations{
				inventory.NetworkIntegration{
					Name: "one",
				},
				inventory.NetworkIntegration{
					Name: "two",
				},
			},

			assertErr: require.NoError,
			count:     2,
		},
		{
			name:             "success - with filter expression",
			filterExpression: ptr.To(`Name == "one"`),
			repoGetAllWithFilter: inventory.NetworkIntegrations{
				inventory.NetworkIntegration{
					Name: "one",
				},
				inventory.NetworkIntegration{
					Name: "two",
				},
			},

			assertErr: require.NoError,
			count:     1,
		},
		{
			name:             "error - invalid filter expression",
			filterExpression: ptr.To(``), // the empty expression is an invalid expression.
			repoGetAllWithFilter: inventory.NetworkIntegrations{
				inventory.NetworkIntegration{
					Name: "one",
				},
			},

			assertErr: require.Error,
			count:     0,
		},
		{
			name:             "error - filter expression run",
			filterExpression: ptr.To(`fromBase64("~invalid")`), // invalid, returns runtime error during evauluation of the expression.
			repoGetAllWithFilter: inventory.NetworkIntegrations{
				inventory.NetworkIntegration{
					Name: "one",
				},
			},

			assertErr: require.Error,
			count:     0,
		},
		{
			name:             "error - non bool expression",
			filterExpression: ptr.To(`"string"`), // invalid, does evaluate to string instead of boolean.
			repoGetAllWithFilter: inventory.NetworkIntegrations{
				inventory.NetworkIntegration{
					Name: "one",
				},
			},

			assertErr: func(tt require.TestingT, err error, i ...any) {
				require.ErrorContains(tt, err, "does not evaluate to boolean result")
			},
			count: 0,
		},
		{
			name:                    "error - repo",
			repoGetAllWithFilterErr: boom.Error,

			assertErr: boom.ErrorIs,
			count:     0,
		},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			// Setup
			repo := &repoMock.NetworkIntegrationRepoMock{
				GetAllWithFilterFunc: func(ctx context.Context, filter inventory.NetworkIntegrationFilter) (inventory.NetworkIntegrations, error) {
					return tc.repoGetAllWithFilter, tc.repoGetAllWithFilterErr
				},
			}

			networkIntegrationSvc := inventory.NewNetworkIntegrationService(repo, nil, nil, inventory.NetworkIntegrationWithNow(func() time.Time {
				return time.Date(2025, 2, 26, 8, 54, 35, 123, time.UTC)
			}))

			// Run test
			networkIntegration, err := networkIntegrationSvc.GetAllWithFilter(context.Background(), inventory.NetworkIntegrationFilter{
				Expression: tc.filterExpression,
			})

			// Assert
			tc.assertErr(t, err)
			require.Len(t, networkIntegration, tc.count)
		})
	}
}

func TestNetworkIntegrationService_GetAllUUIDsWithFilter(t *testing.T) {
	tests := []struct {
		name                         string
		filterExpression             *string
		repoGetAllUUIDsWithFilter    []uuid.UUID
		repoGetAllUUIDsWithFilterErr error

		assertErr require.ErrorAssertionFunc
		count     int
	}{
		{
			name: "success - no filter expression",
			repoGetAllUUIDsWithFilter: []uuid.UUID{
				uuid.MustParse(`6c652183-8d93-4c7d-9510-cd2ae54f31fd`),
				uuid.MustParse(`56d0823e-5c6d-45ff-ac6d-a9ae61026a4e`),
			},

			assertErr: require.NoError,
			count:     2,
		},
		{
			name:             "success - with filter expression",
			filterExpression: ptr.To(`UUID == "6c652183-8d93-4c7d-9510-cd2ae54f31fd"`),
			repoGetAllUUIDsWithFilter: []uuid.UUID{
				uuid.MustParse(`6c652183-8d93-4c7d-9510-cd2ae54f31fd`),
				uuid.MustParse(`56d0823e-5c6d-45ff-ac6d-a9ae61026a4e`),
			},

			assertErr: require.NoError,
			count:     1,
		},
		{
			name:             "error - invalid filter expression",
			filterExpression: ptr.To(``), // the empty expression is an invalid expression.
			repoGetAllUUIDsWithFilter: []uuid.UUID{
				uuid.MustParse(`6c652183-8d93-4c7d-9510-cd2ae54f31fd`),
			},

			assertErr: require.Error,
			count:     0,
		},
		{
			name:             "error - filter expression run",
			filterExpression: ptr.To(`fromBase64("~invalid")`), // invalid, returns runtime error during evauluation of the expression.
			repoGetAllUUIDsWithFilter: []uuid.UUID{
				uuid.MustParse(`6c652183-8d93-4c7d-9510-cd2ae54f31fd`),
			},

			assertErr: require.Error,
			count:     0,
		},
		{
			name:             "error - non bool expression",
			filterExpression: ptr.To(`"string"`), // invalid, does evaluate to string instead of boolean.
			repoGetAllUUIDsWithFilter: []uuid.UUID{
				uuid.MustParse(`6c652183-8d93-4c7d-9510-cd2ae54f31fd`),
			},

			assertErr: func(tt require.TestingT, err error, i ...any) {
				require.ErrorContains(tt, err, "does not evaluate to boolean result")
			},
			count: 0,
		},
		{
			name:                         "error - repo",
			repoGetAllUUIDsWithFilterErr: boom.Error,

			assertErr: boom.ErrorIs,
			count:     0,
		},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			// Setup
			repo := &repoMock.NetworkIntegrationRepoMock{
				GetAllUUIDsWithFilterFunc: func(ctx context.Context, filter inventory.NetworkIntegrationFilter) ([]uuid.UUID, error) {
					return tc.repoGetAllUUIDsWithFilter, tc.repoGetAllUUIDsWithFilterErr
				},
			}

			networkIntegrationSvc := inventory.NewNetworkIntegrationService(repo, nil, nil, inventory.NetworkIntegrationWithNow(func() time.Time {
				return time.Date(2025, 2, 26, 8, 54, 35, 123, time.UTC)
			}))

			// Run test
			networkIntegrationUUIDs, err := networkIntegrationSvc.GetAllUUIDsWithFilter(context.Background(), inventory.NetworkIntegrationFilter{
				Expression: tc.filterExpression,
			})

			// Assert
			tc.assertErr(t, err)
			require.Len(t, networkIntegrationUUIDs, tc.count)
		})
	}
}

func TestNetworkIntegrationService_GetByUUID(t *testing.T) {
	tests := []struct {
		name                            string
		idArg                           uuid.UUID
		repoGetByUUIDNetworkIntegration inventory.NetworkIntegration
		repoGetByUUIDErr                error

		assertErr require.ErrorAssertionFunc
	}{
		{
			name:  "success",
			idArg: uuid.MustParse(`8df91697-be30-464a-bd26-55d1bbe4b07f`),
			repoGetByUUIDNetworkIntegration: inventory.NetworkIntegration{
				UUID:        uuid.MustParse(`8df91697-be30-464a-bd26-55d1bbe4b07f`),
				Cluster:     "one",
				Name:        "one",
				Object:      incusapi.NetworkIntegration{},
				LastUpdated: time.Now(),
			},

			assertErr: require.NoError,
		},
		{
			name:             "error - repo",
			idArg:            uuid.MustParse(`8df91697-be30-464a-bd26-55d1bbe4b07f`),
			repoGetByUUIDErr: boom.Error,

			assertErr: boom.ErrorIs,
		},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			// Setup
			repo := &repoMock.NetworkIntegrationRepoMock{
				GetByUUIDFunc: func(ctx context.Context, id uuid.UUID) (inventory.NetworkIntegration, error) {
					return tc.repoGetByUUIDNetworkIntegration, tc.repoGetByUUIDErr
				},
			}

			networkIntegrationSvc := inventory.NewNetworkIntegrationService(repo, nil, nil, inventory.NetworkIntegrationWithNow(func() time.Time {
				return time.Date(2025, 2, 26, 8, 54, 35, 123, time.UTC)
			}))

			// Run test
			networkIntegration, err := networkIntegrationSvc.GetByUUID(context.Background(), tc.idArg)

			// Assert
			tc.assertErr(t, err)
			require.Equal(t, tc.repoGetByUUIDNetworkIntegration, networkIntegration)
		})
	}
}

func TestNetworkIntegrationService_ResyncByUUID(t *testing.T) {
	tests := []struct {
		name                                                   string
		clusterSvcGetByIDCluster                               provisioning.Cluster
		clusterSvcGetByIDErr                                   error
		networkIntegrationClientGetNetworkIntegrationByName    incusapi.NetworkIntegration
		networkIntegrationClientGetNetworkIntegrationByNameErr error
		repoGetByUUIDNetworkIntegration                        inventory.NetworkIntegration
		repoGetByUUIDErr                                       error
		repoUpdateByUUIDErr                                    error
		repoDeleteByUUIDErr                                    error

		assertErr require.ErrorAssertionFunc
	}{
		{
			name: "success",
			repoGetByUUIDNetworkIntegration: inventory.NetworkIntegration{
				UUID:    uuid.MustParse(`8df91697-be30-464a-bd26-55d1bbe4b07f`),
				Cluster: "one",
				Name:    "one",
			},
			clusterSvcGetByIDCluster: provisioning.Cluster{
				Name: "cluster-one",
			},
			networkIntegrationClientGetNetworkIntegrationByName: incusapi.NetworkIntegration{
				Name: "networkIntegration one",
			},

			assertErr: require.NoError,
		},
		{
			name: "success - networkIntegration get by name - not found",
			repoGetByUUIDNetworkIntegration: inventory.NetworkIntegration{
				UUID:    uuid.MustParse(`8df91697-be30-464a-bd26-55d1bbe4b07f`),
				Cluster: "one",
				Name:    "one",
			},
			clusterSvcGetByIDCluster: provisioning.Cluster{
				Name: "cluster-one",
			},
			networkIntegrationClientGetNetworkIntegrationByNameErr: domain.ErrNotFound,

			assertErr: require.NoError,
		},
		{
			name:             "error - networkIntegration get by UUID",
			repoGetByUUIDErr: boom.Error,

			assertErr: boom.ErrorIs,
		},
		{
			name: "error - cluster get by ID",
			repoGetByUUIDNetworkIntegration: inventory.NetworkIntegration{
				UUID:    uuid.MustParse(`8df91697-be30-464a-bd26-55d1bbe4b07f`),
				Cluster: "one",
				Name:    "one",
			},
			clusterSvcGetByIDErr: boom.Error,

			assertErr: boom.ErrorIs,
		},
		{
			name: "error - networkIntegration get by name",
			repoGetByUUIDNetworkIntegration: inventory.NetworkIntegration{
				UUID:    uuid.MustParse(`8df91697-be30-464a-bd26-55d1bbe4b07f`),
				Cluster: "one",
				Name:    "one",
			},
			clusterSvcGetByIDCluster: provisioning.Cluster{
				Name: "cluster-one",
			},
			networkIntegrationClientGetNetworkIntegrationByNameErr: boom.Error,

			assertErr: boom.ErrorIs,
		},
		{
			name: "error - networkIntegration get by name - not found - delete by uuid",
			repoGetByUUIDNetworkIntegration: inventory.NetworkIntegration{
				UUID:    uuid.MustParse(`8df91697-be30-464a-bd26-55d1bbe4b07f`),
				Cluster: "one",
				Name:    "one",
			},
			clusterSvcGetByIDCluster: provisioning.Cluster{
				Name: "cluster-one",
			},
			networkIntegrationClientGetNetworkIntegrationByNameErr: domain.ErrNotFound,
			repoDeleteByUUIDErr: boom.Error,

			assertErr: boom.ErrorIs,
		},
		{
			name: "error - validate",
			repoGetByUUIDNetworkIntegration: inventory.NetworkIntegration{
				UUID:    uuid.MustParse(`8df91697-be30-464a-bd26-55d1bbe4b07f`),
				Cluster: "one",
				Name:    "", // invalid
			},
			clusterSvcGetByIDCluster: provisioning.Cluster{
				Name: "cluster-one",
			},
			networkIntegrationClientGetNetworkIntegrationByName: incusapi.NetworkIntegration{
				Name: "networkIntegration one",
			},

			assertErr: func(tt require.TestingT, err error, a ...any) {
				var verr domain.ErrValidation
				require.ErrorAs(tt, err, &verr, a...)
			},
		},
		{
			name: "error - update by UUID",
			repoGetByUUIDNetworkIntegration: inventory.NetworkIntegration{
				UUID:    uuid.MustParse(`8df91697-be30-464a-bd26-55d1bbe4b07f`),
				Cluster: "one",
				Name:    "one",
			},
			clusterSvcGetByIDCluster: provisioning.Cluster{
				Name: "cluster-one",
			},
			networkIntegrationClientGetNetworkIntegrationByName: incusapi.NetworkIntegration{
				Name: "networkIntegration one",
			},
			repoUpdateByUUIDErr: boom.Error,

			assertErr: boom.ErrorIs,
		},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			// Setup
			repo := &repoMock.NetworkIntegrationRepoMock{
				GetByUUIDFunc: func(ctx context.Context, id uuid.UUID) (inventory.NetworkIntegration, error) {
					return tc.repoGetByUUIDNetworkIntegration, tc.repoGetByUUIDErr
				},
				UpdateByUUIDFunc: func(ctx context.Context, networkIntegration inventory.NetworkIntegration) (inventory.NetworkIntegration, error) {
					require.Equal(t, time.Date(2025, 2, 26, 8, 54, 35, 123, time.UTC), networkIntegration.LastUpdated)
					return inventory.NetworkIntegration{}, tc.repoUpdateByUUIDErr
				},
				DeleteByUUIDFunc: func(ctx context.Context, id uuid.UUID) error {
					return tc.repoDeleteByUUIDErr
				},
			}

			clusterSvc := &serviceMock.ProvisioningClusterServiceMock{
				GetByNameFunc: func(ctx context.Context, name string) (*provisioning.Cluster, error) {
					require.Equal(t, "one", name)
					return &tc.clusterSvcGetByIDCluster, tc.clusterSvcGetByIDErr
				},
			}

			networkIntegrationClient := &serverMock.NetworkIntegrationServerClientMock{
				GetNetworkIntegrationByNameFunc: func(ctx context.Context, connectionURL string, networkIntegrationName string) (incusapi.NetworkIntegration, error) {
					require.Equal(t, tc.repoGetByUUIDNetworkIntegration.Name, networkIntegrationName)
					return tc.networkIntegrationClientGetNetworkIntegrationByName, tc.networkIntegrationClientGetNetworkIntegrationByNameErr
				},
			}

			networkIntegrationSvc := inventory.NewNetworkIntegrationService(repo, clusterSvc, networkIntegrationClient, inventory.NetworkIntegrationWithNow(func() time.Time {
				return time.Date(2025, 2, 26, 8, 54, 35, 123, time.UTC)
			}))

			// Run test
			err := networkIntegrationSvc.ResyncByUUID(context.Background(), uuid.MustParse(`8df91697-be30-464a-bd26-55d1bbe4b07f`))

			// Assert
			tc.assertErr(t, err)
		})
	}
}

func TestNetworkIntegrationService_SyncAll(t *testing.T) {
	// Includes also SyncCluster
	tests := []struct {
		name                                              string
		clusterSvcGetByIDCluster                          provisioning.Cluster
		clusterSvcGetByIDErr                              error
		networkIntegrationClientGetNetworkIntegrations    []incusapi.NetworkIntegration
		networkIntegrationClientGetNetworkIntegrationsErr error
		repoDeleteByClusterNameErr                        error
		repoCreateErr                                     error
		serviceOptions                                    []inventory.NetworkIntegrationServiceOption

		assertErr require.ErrorAssertionFunc
	}{
		{
			name: "success",
			clusterSvcGetByIDCluster: provisioning.Cluster{
				Name: "cluster-one",
			},
			networkIntegrationClientGetNetworkIntegrations: []incusapi.NetworkIntegration{
				{
					Name: "networkIntegration one",
				},
			},

			assertErr: require.NoError,
		},
		{
			name: "success - with sync filter",
			clusterSvcGetByIDCluster: provisioning.Cluster{
				Name: "cluster-one",
			},
			networkIntegrationClientGetNetworkIntegrations: []incusapi.NetworkIntegration{
				{
					Name: "networkIntegration one",
				},
				{
					Name: "networkIntegration filtered",
				},
			},
			serviceOptions: []inventory.NetworkIntegrationServiceOption{
				inventory.NetworkIntegrationWithSyncFilter(func(networkIntegration inventory.NetworkIntegration) bool {
					return networkIntegration.Name == "networkIntegration filtered"
				}),
			},

			assertErr: require.NoError,
		},
		{
			name:                 "error - cluster service get by ID",
			clusterSvcGetByIDErr: boom.Error,

			assertErr: boom.ErrorIs,
		},
		{
			name: "error - networkIntegration client get NetworkIntegrations",
			clusterSvcGetByIDCluster: provisioning.Cluster{
				Name: "cluster-one",
			},
			networkIntegrationClientGetNetworkIntegrationsErr: boom.Error,

			assertErr: boom.ErrorIs,
		},
		{
			name: "error - network_integrations delete by cluster ID",
			clusterSvcGetByIDCluster: provisioning.Cluster{
				Name: "cluster-one",
			},
			networkIntegrationClientGetNetworkIntegrations: []incusapi.NetworkIntegration{
				{
					Name: "networkIntegration one",
				},
			},
			repoDeleteByClusterNameErr: boom.Error,

			assertErr: boom.ErrorIs,
		},
		{
			name: "error - validate",
			clusterSvcGetByIDCluster: provisioning.Cluster{
				Name: "cluster-one",
			},
			networkIntegrationClientGetNetworkIntegrations: []incusapi.NetworkIntegration{
				{
					Name: "", // invalid
				},
			},

			assertErr: func(tt require.TestingT, err error, a ...any) {
				var verr domain.ErrValidation
				require.ErrorAs(tt, err, &verr, a...)
			},
		},
		{
			name: "error - networkIntegration create",
			clusterSvcGetByIDCluster: provisioning.Cluster{
				Name: "cluster-one",
			},
			networkIntegrationClientGetNetworkIntegrations: []incusapi.NetworkIntegration{
				{
					Name: "networkIntegration one",
				},
			},
			repoCreateErr: boom.Error,

			assertErr: boom.ErrorIs,
		},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			// Setup
			repo := &repoMock.NetworkIntegrationRepoMock{
				DeleteByClusterNameFunc: func(ctx context.Context, clusterName string) error {
					return tc.repoDeleteByClusterNameErr
				},
				CreateFunc: func(ctx context.Context, networkIntegration inventory.NetworkIntegration) (inventory.NetworkIntegration, error) {
					return inventory.NetworkIntegration{}, tc.repoCreateErr
				},
			}

			clusterSvc := &serviceMock.ProvisioningClusterServiceMock{
				GetByNameFunc: func(ctx context.Context, name string) (*provisioning.Cluster, error) {
					return &tc.clusterSvcGetByIDCluster, tc.clusterSvcGetByIDErr
				},
			}

			networkIntegrationClient := &serverMock.NetworkIntegrationServerClientMock{
				GetNetworkIntegrationsFunc: func(ctx context.Context, connectionURL string) ([]incusapi.NetworkIntegration, error) {
					return tc.networkIntegrationClientGetNetworkIntegrations, tc.networkIntegrationClientGetNetworkIntegrationsErr
				},
			}

			networkIntegrationSvc := inventory.NewNetworkIntegrationService(repo, clusterSvc, networkIntegrationClient,
				append(
					tc.serviceOptions,
					inventory.NetworkIntegrationWithNow(func() time.Time {
						return time.Date(2025, 2, 26, 8, 54, 35, 123, time.UTC)
					}),
				)...,
			)

			// Run test
			err := networkIntegrationSvc.SyncCluster(context.Background(), "one")

			// Assert
			tc.assertErr(t, err)
		})
	}
}
