// Code generated by generate-inventory; DO NOT EDIT.

package inventory

import (
	"time"

	incusapi "github.com/lxc/incus/v6/shared/api"

	"github.com/FuturFusion/operations-center/internal/domain"
)

type Network struct {
	ID          int
	ClusterID   int
	ServerID    int
	ProjectName string
	Name        string
	Object      incusapi.Network
	LastUpdated time.Time
}

func (m Network) Validate() error {
	if m.ServerID < 1 {
		return domain.NewValidationErrf("Invalid Network, server id can not be less than 1")
	}

	if m.Name == "" {
		return domain.NewValidationErrf("Invalid Network, name can not be empty")
	}

	if m.ProjectName == "" {
		return domain.NewValidationErrf("Invalid Network, project name can not be empty")
	}

	return nil
}

type Networks []Network

type NetworkFilter struct {
	Cluster *string
	Server  *string
	Project *string
}
