// Code generated by generate-inventory; DO NOT EDIT.

package inventory

import (
	"context"

	incusapi "github.com/lxc/incus/v6/shared/api"
)

type NetworkIntegrationService interface {
	GetAllIDsWithFilter(ctx context.Context, filter NetworkIntegrationFilter) ([]int, error)
	GetByID(ctx context.Context, id int) (NetworkIntegration, error)
	ResyncByID(ctx context.Context, id int) error
	SyncCluster(ctx context.Context, cluster string) error
}

type NetworkIntegrationRepo interface {
	GetAllIDsWithFilter(ctx context.Context, filter NetworkIntegrationFilter) ([]int, error)
	GetByID(ctx context.Context, id int) (NetworkIntegration, error)
	Create(ctx context.Context, networkIntegration NetworkIntegration) (NetworkIntegration, error)
	DeleteByID(ctx context.Context, id int) error
	DeleteByClusterName(ctx context.Context, cluster string) error
	UpdateByID(ctx context.Context, networkIntegration NetworkIntegration) (NetworkIntegration, error)
}

type NetworkIntegrationServerClient interface {
	GetNetworkIntegrations(ctx context.Context, connectionURL string) ([]incusapi.NetworkIntegration, error)
	GetNetworkIntegrationByName(ctx context.Context, connectionURL string, networkIntegrationName string) (incusapi.NetworkIntegration, error)
}
