// Code generated by generate-inventory; DO NOT EDIT.

package inventory_test

import (
	"testing"

	"github.com/stretchr/testify/require"

	"github.com/FuturFusion/operations-center/internal/domain"
	"github.com/FuturFusion/operations-center/internal/inventory"
)

func TestNetworkZone_Validate(t *testing.T) {
	tests := []struct {
		name  string
		image inventory.NetworkZone

		assertErr require.ErrorAssertionFunc
	}{
		{
			name: "valid",
			image: inventory.NetworkZone{
				ID:          1,
				Cluster:     "cluster-one",
				ProjectName: "project one",
				Name:        "one",
			},

			assertErr: require.NoError,
		},
		{
			name: "error - invalid cluster Name",
			image: inventory.NetworkZone{
				ID:          1,
				Cluster:     "", // invalid
				ProjectName: "project one",
				Name:        "one",
			},

			assertErr: func(tt require.TestingT, err error, a ...any) {
				var verr domain.ErrValidation
				require.ErrorAs(tt, err, &verr, a...)
			},
		},
		{
			name: "error - invalid project name",
			image: inventory.NetworkZone{
				ID:          1,
				Cluster:     "cluster-one",
				ProjectName: "", // invalid
				Name:        "one",
			},

			assertErr: func(tt require.TestingT, err error, a ...any) {
				var verr domain.ErrValidation
				require.ErrorAs(tt, err, &verr, a...)
			},
		},
		{
			name: "error - invalid name",
			image: inventory.NetworkZone{
				ID:          1,
				Cluster:     "cluster-one",
				ProjectName: "project one",
				Name:        "", // invalid
			},

			assertErr: func(tt require.TestingT, err error, a ...any) {
				var verr domain.ErrValidation
				require.ErrorAs(tt, err, &verr, a...)
			},
		},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			err := tc.image.Validate()

			tc.assertErr(t, err)
		})
	}
}
