// Code generated by generate-inventory; DO NOT EDIT.

package inventory

import (
	"net/url"
	"strings"
	"time"

	"github.com/google/uuid"
	incusapi "github.com/lxc/incus/v6/shared/api"

	"github.com/FuturFusion/operations-center/internal/domain"
)

type Network struct {
	ID          int
	UUID        uuid.UUID
	Cluster     string
	ProjectName string
	Name        string
	Object      incusapi.Network
	LastUpdated time.Time
}

func (m *Network) DeriveUUID() *Network {
	identifier := strings.Join([]string{
		m.Cluster,
		m.ProjectName,
		m.Name,
	}, ":")

	m.UUID = uuid.NewSHA1(InventorySpaceUUID, []byte(identifier))

	return m
}

func (m Network) Validate() error {
	if m.Cluster == "" {
		return domain.NewValidationErrf("Invalid Network, cluster can not be empty")
	}

	if m.Name == "" {
		return domain.NewValidationErrf("Invalid Network, name can not be empty")
	}

	if m.ProjectName == "" {
		return domain.NewValidationErrf("Invalid Network, project name can not be empty")
	}

	clone := m
	clone.DeriveUUID()
	if clone.UUID != m.UUID {
		return domain.NewValidationErrf("Invalid UUID, does not match derived value")
	}

	return nil
}

type Networks []Network

type NetworkFilter struct {
	Cluster    *string
	Project    *string
	Expression *string
}

func (f NetworkFilter) AppendToURLValues(query url.Values) url.Values {
	if f.Cluster != nil {
		query.Add("cluster", *f.Cluster)
	}

	if f.Project != nil {
		query.Add("project", *f.Project)
	}

	if f.Expression != nil {
		query.Add("filter", *f.Expression)
	}

	return query
}

func (f NetworkFilter) String() string {
	return f.AppendToURLValues(url.Values{}).Encode()
}
