// Code generated by generate-inventory; DO NOT EDIT.

package inventory

import (
	"context"

	incusapi "github.com/lxc/incus/v6/shared/api"
)

type NetworkForwardService interface {
	GetAllIDsWithFilter(ctx context.Context, filter NetworkForwardFilter) ([]int, error)
	GetByID(ctx context.Context, id int) (NetworkForward, error)
	ResyncByID(ctx context.Context, id int) error
	SyncCluster(ctx context.Context, clusterID int) error
}

type NetworkForwardRepo interface {
	GetAllIDsWithFilter(ctx context.Context, filter NetworkForwardFilter) ([]int, error)
	GetByID(ctx context.Context, id int) (NetworkForward, error)
	Create(ctx context.Context, networkForward NetworkForward) (NetworkForward, error)
	DeleteByID(ctx context.Context, id int) error
	DeleteByClusterID(ctx context.Context, clusterID int) error
	UpdateByID(ctx context.Context, networkForward NetworkForward) (NetworkForward, error)
}

type NetworkForwardServerClient interface {
	GetNetworkForwards(ctx context.Context, connectionURL string, networkName string) ([]incusapi.NetworkForward, error)
	GetNetworkForwardByName(ctx context.Context, connectionURL string, networkName string, networkForwardName string) (incusapi.NetworkForward, error)
}
