// Code generated by generate-inventory; DO NOT EDIT.

package inventory

import (
	"time"

	incusapi "github.com/lxc/incus/v6/shared/api"
)

type Project struct {
	ID          int
	ClusterID   int
	ServerID    int
	Name        string
	Object      incusapi.Project
	LastUpdated time.Time
}

func (s Project) Validate() error {
	return nil
}

type Projects []Project

type ProjectFilter struct {
	Cluster *string
	Server  *string
}
