// Code generated by generate-inventory; DO NOT EDIT.

package inventory_test

import (
	"context"
	"testing"
	"time"

	"github.com/google/uuid"
	incusapi "github.com/lxc/incus/v6/shared/api"
	"github.com/stretchr/testify/require"

	"github.com/FuturFusion/operations-center/internal/domain"
	"github.com/FuturFusion/operations-center/internal/inventory"
	serviceMock "github.com/FuturFusion/operations-center/internal/inventory/mock"
	repoMock "github.com/FuturFusion/operations-center/internal/inventory/repo/mock"
	serverMock "github.com/FuturFusion/operations-center/internal/inventory/server/mock"
	"github.com/FuturFusion/operations-center/internal/provisioning"
	"github.com/FuturFusion/operations-center/internal/ptr"
	"github.com/FuturFusion/operations-center/internal/testing/boom"
)

func TestStorageBucketService_GetAllWithFilter(t *testing.T) {
	tests := []struct {
		name                    string
		filterExpression        *string
		repoGetAllWithFilter    inventory.StorageBuckets
		repoGetAllWithFilterErr error

		assertErr require.ErrorAssertionFunc
		count     int
	}{
		{
			name: "success - no filter expression",
			repoGetAllWithFilter: inventory.StorageBuckets{
				inventory.StorageBucket{
					Name: "one",
				},
				inventory.StorageBucket{
					Name: "two",
				},
			},

			assertErr: require.NoError,
			count:     2,
		},
		{
			name:             "success - with filter expression",
			filterExpression: ptr.To(`Name == "one"`),
			repoGetAllWithFilter: inventory.StorageBuckets{
				inventory.StorageBucket{
					Name: "one",
				},
				inventory.StorageBucket{
					Name: "two",
				},
			},

			assertErr: require.NoError,
			count:     1,
		},
		{
			name:             "error - invalid filter expression",
			filterExpression: ptr.To(``), // the empty expression is an invalid expression.
			repoGetAllWithFilter: inventory.StorageBuckets{
				inventory.StorageBucket{
					Name: "one",
				},
			},

			assertErr: require.Error,
			count:     0,
		},
		{
			name:             "error - filter expression run",
			filterExpression: ptr.To(`fromBase64("~invalid")`), // invalid, returns runtime error during evauluation of the expression.
			repoGetAllWithFilter: inventory.StorageBuckets{
				inventory.StorageBucket{
					Name: "one",
				},
			},

			assertErr: require.Error,
			count:     0,
		},
		{
			name:             "error - non bool expression",
			filterExpression: ptr.To(`"string"`), // invalid, does evaluate to string instead of boolean.
			repoGetAllWithFilter: inventory.StorageBuckets{
				inventory.StorageBucket{
					Name: "one",
				},
			},

			assertErr: func(tt require.TestingT, err error, i ...any) {
				require.ErrorContains(tt, err, "does not evaluate to boolean result")
			},
			count: 0,
		},
		{
			name:                    "error - repo",
			repoGetAllWithFilterErr: boom.Error,

			assertErr: boom.ErrorIs,
			count:     0,
		},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			// Setup
			repo := &repoMock.StorageBucketRepoMock{
				GetAllWithFilterFunc: func(ctx context.Context, filter inventory.StorageBucketFilter) (inventory.StorageBuckets, error) {
					return tc.repoGetAllWithFilter, tc.repoGetAllWithFilterErr
				},
			}

			storageBucketSvc := inventory.NewStorageBucketService(repo, nil, nil, nil, inventory.StorageBucketWithNow(func() time.Time {
				return time.Date(2025, 2, 26, 8, 54, 35, 123, time.UTC)
			}))

			// Run test
			storageBucket, err := storageBucketSvc.GetAllWithFilter(context.Background(), inventory.StorageBucketFilter{
				Expression: tc.filterExpression,
			})

			// Assert
			tc.assertErr(t, err)
			require.Len(t, storageBucket, tc.count)
		})
	}
}

func TestStorageBucketService_GetAllUUIDsWithFilter(t *testing.T) {
	tests := []struct {
		name                         string
		filterExpression             *string
		repoGetAllUUIDsWithFilter    []uuid.UUID
		repoGetAllUUIDsWithFilterErr error

		assertErr require.ErrorAssertionFunc
		count     int
	}{
		{
			name: "success - no filter expression",
			repoGetAllUUIDsWithFilter: []uuid.UUID{
				uuid.MustParse(`6c652183-8d93-4c7d-9510-cd2ae54f31fd`),
				uuid.MustParse(`56d0823e-5c6d-45ff-ac6d-a9ae61026a4e`),
			},

			assertErr: require.NoError,
			count:     2,
		},
		{
			name:             "success - with filter expression",
			filterExpression: ptr.To(`UUID == "6c652183-8d93-4c7d-9510-cd2ae54f31fd"`),
			repoGetAllUUIDsWithFilter: []uuid.UUID{
				uuid.MustParse(`6c652183-8d93-4c7d-9510-cd2ae54f31fd`),
				uuid.MustParse(`56d0823e-5c6d-45ff-ac6d-a9ae61026a4e`),
			},

			assertErr: require.NoError,
			count:     1,
		},
		{
			name:             "error - invalid filter expression",
			filterExpression: ptr.To(``), // the empty expression is an invalid expression.
			repoGetAllUUIDsWithFilter: []uuid.UUID{
				uuid.MustParse(`6c652183-8d93-4c7d-9510-cd2ae54f31fd`),
			},

			assertErr: require.Error,
			count:     0,
		},
		{
			name:             "error - filter expression run",
			filterExpression: ptr.To(`fromBase64("~invalid")`), // invalid, returns runtime error during evauluation of the expression.
			repoGetAllUUIDsWithFilter: []uuid.UUID{
				uuid.MustParse(`6c652183-8d93-4c7d-9510-cd2ae54f31fd`),
			},

			assertErr: require.Error,
			count:     0,
		},
		{
			name:             "error - non bool expression",
			filterExpression: ptr.To(`"string"`), // invalid, does evaluate to string instead of boolean.
			repoGetAllUUIDsWithFilter: []uuid.UUID{
				uuid.MustParse(`6c652183-8d93-4c7d-9510-cd2ae54f31fd`),
			},

			assertErr: func(tt require.TestingT, err error, i ...any) {
				require.ErrorContains(tt, err, "does not evaluate to boolean result")
			},
			count: 0,
		},
		{
			name:                         "error - repo",
			repoGetAllUUIDsWithFilterErr: boom.Error,

			assertErr: boom.ErrorIs,
			count:     0,
		},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			// Setup
			repo := &repoMock.StorageBucketRepoMock{
				GetAllUUIDsWithFilterFunc: func(ctx context.Context, filter inventory.StorageBucketFilter) ([]uuid.UUID, error) {
					return tc.repoGetAllUUIDsWithFilter, tc.repoGetAllUUIDsWithFilterErr
				},
			}

			storageBucketSvc := inventory.NewStorageBucketService(repo, nil, nil, nil, inventory.StorageBucketWithNow(func() time.Time {
				return time.Date(2025, 2, 26, 8, 54, 35, 123, time.UTC)
			}))

			// Run test
			storageBucketUUIDs, err := storageBucketSvc.GetAllUUIDsWithFilter(context.Background(), inventory.StorageBucketFilter{
				Expression: tc.filterExpression,
			})

			// Assert
			tc.assertErr(t, err)
			require.Len(t, storageBucketUUIDs, tc.count)
		})
	}
}

func TestStorageBucketService_GetByUUID(t *testing.T) {
	tests := []struct {
		name                       string
		idArg                      uuid.UUID
		repoGetByUUIDStorageBucket inventory.StorageBucket
		repoGetByUUIDErr           error

		assertErr require.ErrorAssertionFunc
	}{
		{
			name:  "success",
			idArg: uuid.MustParse(`8df91697-be30-464a-bd26-55d1bbe4b07f`),
			repoGetByUUIDStorageBucket: inventory.StorageBucket{
				UUID:            uuid.MustParse(`8df91697-be30-464a-bd26-55d1bbe4b07f`),
				Cluster:         "one",
				ProjectName:     "one",
				StoragePoolName: "parent one",
				Name:            "one",
				Object:          incusapi.StorageBucket{},
				LastUpdated:     time.Now(),
			},

			assertErr: require.NoError,
		},
		{
			name:             "error - repo",
			idArg:            uuid.MustParse(`8df91697-be30-464a-bd26-55d1bbe4b07f`),
			repoGetByUUIDErr: boom.Error,

			assertErr: boom.ErrorIs,
		},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			// Setup
			repo := &repoMock.StorageBucketRepoMock{
				GetByUUIDFunc: func(ctx context.Context, id uuid.UUID) (inventory.StorageBucket, error) {
					return tc.repoGetByUUIDStorageBucket, tc.repoGetByUUIDErr
				},
			}

			storageBucketSvc := inventory.NewStorageBucketService(repo, nil, nil, nil, inventory.StorageBucketWithNow(func() time.Time {
				return time.Date(2025, 2, 26, 8, 54, 35, 123, time.UTC)
			}))

			// Run test
			storageBucket, err := storageBucketSvc.GetByUUID(context.Background(), tc.idArg)

			// Assert
			tc.assertErr(t, err)
			require.Equal(t, tc.repoGetByUUIDStorageBucket, storageBucket)
		})
	}
}

func TestStorageBucketService_ResyncByUUID(t *testing.T) {
	tests := []struct {
		name                                         string
		clusterSvcGetEndpoint                        provisioning.Endpoint
		clusterSvcGetEndpointErr                     error
		storageBucketClientGetStorageBucketByName    incusapi.StorageBucket
		storageBucketClientGetStorageBucketByNameErr error
		repoGetByUUIDStorageBucket                   inventory.StorageBucket
		repoGetByUUIDErr                             error
		repoUpdateByUUIDErr                          error
		repoDeleteByUUIDErr                          error

		assertErr require.ErrorAssertionFunc
	}{
		{
			name: "success",
			repoGetByUUIDStorageBucket: inventory.StorageBucket{
				UUID:            uuid.MustParse(`8df91697-be30-464a-bd26-55d1bbe4b07f`),
				Cluster:         "one",
				Name:            "one",
				StoragePoolName: "storage_pool",
			},
			clusterSvcGetEndpoint: provisioning.ClusterEndpoint{
				{
					ConnectionURL:      "https://server-one/",
					Certificate:        "cert",
					ClusterCertificate: ptr.To("cluster-cert"),
				},
			},
			storageBucketClientGetStorageBucketByName: incusapi.StorageBucket{
				Name:     "storageBucket one",
				Location: "one",
				Project:  "project one",
			},

			assertErr: require.NoError,
		},
		{
			name: "success - storageBucket get by name - not found",
			repoGetByUUIDStorageBucket: inventory.StorageBucket{
				UUID:            uuid.MustParse(`8df91697-be30-464a-bd26-55d1bbe4b07f`),
				Cluster:         "one",
				Name:            "one",
				StoragePoolName: "storage_pool",
			},
			clusterSvcGetEndpoint: provisioning.ClusterEndpoint{
				{
					ConnectionURL:      "https://server-one/",
					Certificate:        "cert",
					ClusterCertificate: ptr.To("cluster-cert"),
				},
			},
			storageBucketClientGetStorageBucketByNameErr: domain.ErrNotFound,

			assertErr: require.NoError,
		},
		{
			name:             "error - storageBucket get by UUID",
			repoGetByUUIDErr: boom.Error,

			assertErr: boom.ErrorIs,
		},
		{
			name: "error - cluster get by ID",
			repoGetByUUIDStorageBucket: inventory.StorageBucket{
				UUID:            uuid.MustParse(`8df91697-be30-464a-bd26-55d1bbe4b07f`),
				Cluster:         "one",
				Name:            "one",
				StoragePoolName: "storage_pool",
			},
			clusterSvcGetEndpointErr: boom.Error,

			assertErr: boom.ErrorIs,
		},
		{
			name: "error - storageBucket get by name",
			repoGetByUUIDStorageBucket: inventory.StorageBucket{
				UUID:            uuid.MustParse(`8df91697-be30-464a-bd26-55d1bbe4b07f`),
				Cluster:         "one",
				Name:            "one",
				StoragePoolName: "storage_pool",
			},
			clusterSvcGetEndpoint: provisioning.ClusterEndpoint{
				{
					ConnectionURL:      "https://server-one/",
					Certificate:        "cert",
					ClusterCertificate: ptr.To("cluster-cert"),
				},
			},
			storageBucketClientGetStorageBucketByNameErr: boom.Error,

			assertErr: boom.ErrorIs,
		},
		{
			name: "error - storageBucket get by name - not found - delete by uuid",
			repoGetByUUIDStorageBucket: inventory.StorageBucket{
				UUID:            uuid.MustParse(`8df91697-be30-464a-bd26-55d1bbe4b07f`),
				Cluster:         "one",
				Name:            "one",
				StoragePoolName: "storage_pool",
			},
			clusterSvcGetEndpoint: provisioning.ClusterEndpoint{
				{
					ConnectionURL:      "https://server-one/",
					Certificate:        "cert",
					ClusterCertificate: ptr.To("cluster-cert"),
				},
			},
			storageBucketClientGetStorageBucketByNameErr: domain.ErrNotFound,
			repoDeleteByUUIDErr:                          boom.Error,

			assertErr: boom.ErrorIs,
		},
		{
			name: "error - validate",
			repoGetByUUIDStorageBucket: inventory.StorageBucket{
				UUID:            uuid.MustParse(`8df91697-be30-464a-bd26-55d1bbe4b07f`),
				Cluster:         "one",
				Name:            "", // invalid
				StoragePoolName: "storage_pool",
			},
			clusterSvcGetEndpoint: provisioning.ClusterEndpoint{
				{
					ConnectionURL:      "https://server-one/",
					Certificate:        "cert",
					ClusterCertificate: ptr.To("cluster-cert"),
				},
			},
			storageBucketClientGetStorageBucketByName: incusapi.StorageBucket{
				Name:     "storageBucket one",
				Location: "one",
				Project:  "project one",
			},

			assertErr: func(tt require.TestingT, err error, a ...any) {
				var verr domain.ErrValidation
				require.ErrorAs(tt, err, &verr, a...)
			},
		},
		{
			name: "error - update by UUID",
			repoGetByUUIDStorageBucket: inventory.StorageBucket{
				UUID:            uuid.MustParse(`8df91697-be30-464a-bd26-55d1bbe4b07f`),
				Cluster:         "one",
				Name:            "one",
				StoragePoolName: "storage_pool",
			},
			clusterSvcGetEndpoint: provisioning.ClusterEndpoint{
				{
					ConnectionURL:      "https://server-one/",
					Certificate:        "cert",
					ClusterCertificate: ptr.To("cluster-cert"),
				},
			},
			storageBucketClientGetStorageBucketByName: incusapi.StorageBucket{
				Name:     "storageBucket one",
				Location: "one",
				Project:  "project one",
			},
			repoUpdateByUUIDErr: boom.Error,

			assertErr: boom.ErrorIs,
		},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			// Setup
			repo := &repoMock.StorageBucketRepoMock{
				GetByUUIDFunc: func(ctx context.Context, id uuid.UUID) (inventory.StorageBucket, error) {
					return tc.repoGetByUUIDStorageBucket, tc.repoGetByUUIDErr
				},
				UpdateByUUIDFunc: func(ctx context.Context, storageBucket inventory.StorageBucket) (inventory.StorageBucket, error) {
					require.Equal(t, time.Date(2025, 2, 26, 8, 54, 35, 123, time.UTC), storageBucket.LastUpdated)
					return inventory.StorageBucket{}, tc.repoUpdateByUUIDErr
				},
				DeleteByUUIDFunc: func(ctx context.Context, id uuid.UUID) error {
					return tc.repoDeleteByUUIDErr
				},
			}

			clusterSvc := &serviceMock.ProvisioningClusterServiceMock{
				GetEndpointFunc: func(ctx context.Context, name string) (provisioning.Endpoint, error) {
					require.Equal(t, "one", name)
					return tc.clusterSvcGetEndpoint, tc.clusterSvcGetEndpointErr
				},
			}

			storageBucketClient := &serverMock.StorageBucketServerClientMock{
				GetStorageBucketByNameFunc: func(ctx context.Context, endpoint provisioning.Endpoint, storagePoolName string, storageBucketName string) (incusapi.StorageBucket, error) {
					require.Equal(t, tc.repoGetByUUIDStorageBucket.Name, storageBucketName)
					require.Equal(t, "storage_pool", storagePoolName)
					return tc.storageBucketClientGetStorageBucketByName, tc.storageBucketClientGetStorageBucketByNameErr
				},
			}

			storageBucketSvc := inventory.NewStorageBucketService(repo, clusterSvc, storageBucketClient, nil, inventory.StorageBucketWithNow(func() time.Time {
				return time.Date(2025, 2, 26, 8, 54, 35, 123, time.UTC)
			}))

			// Run test
			err := storageBucketSvc.ResyncByUUID(context.Background(), uuid.MustParse(`8df91697-be30-464a-bd26-55d1bbe4b07f`))

			// Assert
			tc.assertErr(t, err)
		})
	}
}

func TestStorageBucketService_SyncAll(t *testing.T) {
	// Includes also SyncCluster
	tests := []struct {
		name                                    string
		clusterSvcGetEndpoint                   provisioning.Endpoint
		clusterSvcGetEndpointErr                error
		storagePoolClientGetStoragePools        []incusapi.StoragePool
		storagePoolClientGetStoragePoolsErr     error
		storageBucketClientGetStorageBuckets    []incusapi.StorageBucket
		storageBucketClientGetStorageBucketsErr error
		repoDeleteByClusterNameErr              error
		repoCreateErr                           error
		serviceOptions                          []inventory.StorageBucketServiceOption

		assertErr require.ErrorAssertionFunc
	}{
		{
			name: "success",
			clusterSvcGetEndpoint: provisioning.ClusterEndpoint{
				{
					ConnectionURL:      "https://server-one/",
					Certificate:        "cert",
					ClusterCertificate: ptr.To("cluster-cert"),
				},
			},
			storagePoolClientGetStoragePools: []incusapi.StoragePool{
				{
					Name: "storagePool one",
				},
			},
			storageBucketClientGetStorageBuckets: []incusapi.StorageBucket{
				{
					Name:     "storageBucket one",
					Location: "one",
					Project:  "project one",
				},
			},

			assertErr: require.NoError,
		},
		{
			name: "success - with parent filter",
			clusterSvcGetEndpoint: provisioning.ClusterEndpoint{
				{
					ConnectionURL:      "https://server-one/",
					Certificate:        "cert",
					ClusterCertificate: ptr.To("cluster-cert"),
				},
			},
			storagePoolClientGetStoragePools: []incusapi.StoragePool{
				{
					Name: "storagePool one",
				},
				{
					Name: "filtered",
				},
			},
			storageBucketClientGetStorageBuckets: []incusapi.StorageBucket{
				{
					Name:     "storageBucket one",
					Location: "one",
					Project:  "project one",
				},
			},
			serviceOptions: []inventory.StorageBucketServiceOption{
				inventory.StorageBucketWithParentFilter(func(parent incusapi.StoragePool) bool {
					return parent.Name == "filtered"
				}),
			},

			assertErr: require.NoError,
		},
		{
			name: "success - with sync filter",
			clusterSvcGetEndpoint: provisioning.ClusterEndpoint{
				{
					ConnectionURL:      "https://server-one/",
					Certificate:        "cert",
					ClusterCertificate: ptr.To("cluster-cert"),
				},
			},
			storagePoolClientGetStoragePools: []incusapi.StoragePool{
				{
					Name: "storagePool one",
				},
			},
			storageBucketClientGetStorageBuckets: []incusapi.StorageBucket{
				{
					Name:     "storageBucket one",
					Location: "one",
					Project:  "project one",
				},
				{
					Name:     "storageBucket filtered",
					Location: "one",
					Project:  "project one",
				},
			},
			serviceOptions: []inventory.StorageBucketServiceOption{
				inventory.StorageBucketWithSyncFilter(func(storageBucket inventory.StorageBucket) bool {
					return storageBucket.Name == "storageBucket filtered"
				}),
			},

			assertErr: require.NoError,
		},
		{
			name:                     "error - cluster service get by ID",
			clusterSvcGetEndpointErr: boom.Error,

			assertErr: boom.ErrorIs,
		},
		{
			name: "error - storagePool client get StoragePools",
			clusterSvcGetEndpoint: provisioning.ClusterEndpoint{
				{
					ConnectionURL:      "https://server-one/",
					Certificate:        "cert",
					ClusterCertificate: ptr.To("cluster-cert"),
				},
			},
			storagePoolClientGetStoragePoolsErr: boom.Error,

			assertErr: boom.ErrorIs,
		},
		{
			name: "error - storageBucket client get StorageBuckets",
			clusterSvcGetEndpoint: provisioning.ClusterEndpoint{
				{
					ConnectionURL:      "https://server-one/",
					Certificate:        "cert",
					ClusterCertificate: ptr.To("cluster-cert"),
				},
			},
			storagePoolClientGetStoragePools: []incusapi.StoragePool{
				{
					Name: "storagePool one",
				},
			},
			storageBucketClientGetStorageBucketsErr: boom.Error,

			assertErr: boom.ErrorIs,
		},
		{
			name: "error - storage_buckets delete by cluster ID",
			clusterSvcGetEndpoint: provisioning.ClusterEndpoint{
				{
					ConnectionURL:      "https://server-one/",
					Certificate:        "cert",
					ClusterCertificate: ptr.To("cluster-cert"),
				},
			},
			storagePoolClientGetStoragePools: []incusapi.StoragePool{
				{
					Name: "storagePool one",
				},
			},
			storageBucketClientGetStorageBuckets: []incusapi.StorageBucket{
				{
					Name:     "storageBucket one",
					Location: "one",
					Project:  "project one",
				},
			},
			repoDeleteByClusterNameErr: boom.Error,

			assertErr: boom.ErrorIs,
		},
		{
			name: "error - validate",
			clusterSvcGetEndpoint: provisioning.ClusterEndpoint{
				{
					ConnectionURL:      "https://server-one/",
					Certificate:        "cert",
					ClusterCertificate: ptr.To("cluster-cert"),
				},
			},
			storagePoolClientGetStoragePools: []incusapi.StoragePool{
				{
					Name: "storagePool one",
				},
			},
			storageBucketClientGetStorageBuckets: []incusapi.StorageBucket{
				{
					Name:     "", // invalid
					Location: "one",
					Project:  "project one",
				},
			},

			assertErr: func(tt require.TestingT, err error, a ...any) {
				var verr domain.ErrValidation
				require.ErrorAs(tt, err, &verr, a...)
			},
		},
		{
			name: "error - storageBucket create",
			clusterSvcGetEndpoint: provisioning.ClusterEndpoint{
				{
					ConnectionURL:      "https://server-one/",
					Certificate:        "cert",
					ClusterCertificate: ptr.To("cluster-cert"),
				},
			},
			storagePoolClientGetStoragePools: []incusapi.StoragePool{
				{
					Name: "storagePool one",
				},
			},
			storageBucketClientGetStorageBuckets: []incusapi.StorageBucket{
				{
					Name:     "storageBucket one",
					Location: "one",
					Project:  "project one",
				},
			},
			repoCreateErr: boom.Error,

			assertErr: boom.ErrorIs,
		},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			// Setup
			repo := &repoMock.StorageBucketRepoMock{
				DeleteByClusterNameFunc: func(ctx context.Context, clusterName string) error {
					return tc.repoDeleteByClusterNameErr
				},
				CreateFunc: func(ctx context.Context, storageBucket inventory.StorageBucket) (inventory.StorageBucket, error) {
					return inventory.StorageBucket{}, tc.repoCreateErr
				},
			}

			clusterSvc := &serviceMock.ProvisioningClusterServiceMock{
				GetEndpointFunc: func(ctx context.Context, name string) (provisioning.Endpoint, error) {
					return tc.clusterSvcGetEndpoint, tc.clusterSvcGetEndpointErr
				},
			}

			storagePoolClient := &serverMock.StoragePoolServerClientMock{
				GetStoragePoolsFunc: func(ctx context.Context, endpoint provisioning.Endpoint) ([]incusapi.StoragePool, error) {
					return tc.storagePoolClientGetStoragePools, tc.storagePoolClientGetStoragePoolsErr
				},
			}

			storageBucketClient := &serverMock.StorageBucketServerClientMock{
				GetStorageBucketsFunc: func(ctx context.Context, endpoint provisioning.Endpoint, storagePoolName string) ([]incusapi.StorageBucket, error) {
					return tc.storageBucketClientGetStorageBuckets, tc.storageBucketClientGetStorageBucketsErr
				},
			}

			storageBucketSvc := inventory.NewStorageBucketService(repo, clusterSvc, storageBucketClient, storagePoolClient,
				append(
					tc.serviceOptions,
					inventory.StorageBucketWithNow(func() time.Time {
						return time.Date(2025, 2, 26, 8, 54, 35, 123, time.UTC)
					}),
				)...,
			)

			// Run test
			err := storageBucketSvc.SyncCluster(context.Background(), "one")

			// Assert
			tc.assertErr(t, err)
		})
	}
}
