// Code generated by generate-inventory; DO NOT EDIT.

package inventory

import (
	"context"

	incusapi "github.com/lxc/incus/v6/shared/api"
)

type StorageBucketService interface {
	GetAllIDsWithFilter(ctx context.Context, filter StorageBucketFilter) ([]int, error)
	GetByID(ctx context.Context, id int) (StorageBucket, error)
	ResyncByID(ctx context.Context, id int) error
	SyncAll(ctx context.Context) error
	SyncCluster(ctx context.Context, clusterID int) error
	SyncServer(ctx context.Context, serverID int) error
}

//go:generate go run github.com/matryer/moq -fmt goimports -pkg mock -out repo/mock/storage_bucket_repo_mock_gen.go -rm . StorageBucketRepo
//go:generate go run github.com/hexdigest/gowrap/cmd/gowrap gen -g -i StorageBucketRepo -t ../logger/slog.gotmpl -o ./repo/middleware/storage_bucket_slog_gen.go
// disabled go:generate go run github.com/hexdigest/gowrap/cmd/gowrap gen -g -i StorageBucketRepo -t prometheus -o ./repo/middleware/storage_bucket_prometheus_gen.go

type StorageBucketRepo interface {
	GetAllIDsWithFilter(ctx context.Context, filter StorageBucketFilter) ([]int, error)
	GetByID(ctx context.Context, id int) (StorageBucket, error)
	Create(ctx context.Context, storageBucket StorageBucket) (StorageBucket, error)
	DeleteByServerID(ctx context.Context, serverID int) error
	UpdateByID(ctx context.Context, storageBucket StorageBucket) (StorageBucket, error)
}

//go:generate go run github.com/matryer/moq -fmt goimports -pkg mock -out mock/storage_bucket_server_client_mock_gen.go -rm . StorageBucketServerClient

type StorageBucketServerClient interface {
	GetStorageBuckets(ctx context.Context, connectionURL string, storagePoolName string) ([]incusapi.StorageBucket, error)
	GetStorageBucketByName(ctx context.Context, connectionURL string, storagePoolName string, storageBucketName string) (incusapi.StorageBucket, error)
}
