// Code generated by mockery. DO NOT EDIT.
// template: github.com/FuturFusion/operations-center/internal/util/logger/slog.gotmpl

package middleware

import (
	"context"
	"log/slog"

	"github.com/FuturFusion/operations-center/internal/util/logger"
	"github.com/FuturFusion/operations-center/internal/warning"
	"github.com/FuturFusion/operations-center/shared/api"
	"github.com/google/uuid"
)

// WarningServiceWithSlog implements warning.WarningService that is instrumented with slog logger.
type WarningServiceWithSlog struct {
	_base                 warning.WarningService
	_isInformativeErrFunc func(error) bool
}

type WarningServiceWithSlogOption func(s *WarningServiceWithSlog)

func WarningServiceWithSlogWithInformativeErrFunc(isInformativeErrFunc func(error) bool) WarningServiceWithSlogOption {
	return func(_base *WarningServiceWithSlog) {
		_base._isInformativeErrFunc = isInformativeErrFunc
	}
}

// NewWarningServiceWithSlog instruments an implementation of the warning.WarningService with simple logging.
func NewWarningServiceWithSlog(base warning.WarningService, opts ...WarningServiceWithSlogOption) WarningServiceWithSlog {
	this := WarningServiceWithSlog{
		_base:                 base,
		_isInformativeErrFunc: func(error) bool { return false },
	}

	for _, opt := range opts {
		opt(&this)
	}

	return this
}

// DeleteByUUID implements warning.WarningService.
func (_d WarningServiceWithSlog) DeleteByUUID(ctx context.Context, id uuid.UUID) (err error) {
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.Any("id", id),
		)
	}
	log.DebugContext(ctx, "=> calling DeleteByUUID")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			if _d._isInformativeErrFunc(err) {
				log.DebugContext(ctx, "<= method DeleteByUUID returned an informative error")
			} else {
				log.ErrorContext(ctx, "<= method DeleteByUUID returned an error")
			}
		} else {
			log.DebugContext(ctx, "<= method DeleteByUUID finished")
		}
	}()
	return _d._base.DeleteByUUID(ctx, id)
}

// Emit implements warning.WarningService.
func (_d WarningServiceWithSlog) Emit(ctx context.Context, w warning.Warning) {
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.Any("w", w),
		)
	}
	log.DebugContext(ctx, "=> calling Emit")
	defer func() {
		log := slog.With()
		log.DebugContext(ctx, "<= method Emit finished")
	}()
	_d._base.Emit(ctx, w)
}

// GetAll implements warning.WarningService.
func (_d WarningServiceWithSlog) GetAll(ctx context.Context) (warnings warning.Warnings, err error) {
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
		)
	}
	log.DebugContext(ctx, "=> calling GetAll")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("warnings", warnings),
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			if _d._isInformativeErrFunc(err) {
				log.DebugContext(ctx, "<= method GetAll returned an informative error")
			} else {
				log.ErrorContext(ctx, "<= method GetAll returned an error")
			}
		} else {
			log.DebugContext(ctx, "<= method GetAll finished")
		}
	}()
	return _d._base.GetAll(ctx)
}

// GetByScopeAndType implements warning.WarningService.
func (_d WarningServiceWithSlog) GetByScopeAndType(ctx context.Context, scope api.WarningScope, wType api.WarningType) (warnings warning.Warnings, err error) {
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.Any("scope", scope),
			slog.Any("wType", wType),
		)
	}
	log.DebugContext(ctx, "=> calling GetByScopeAndType")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("warnings", warnings),
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			if _d._isInformativeErrFunc(err) {
				log.DebugContext(ctx, "<= method GetByScopeAndType returned an informative error")
			} else {
				log.ErrorContext(ctx, "<= method GetByScopeAndType returned an error")
			}
		} else {
			log.DebugContext(ctx, "<= method GetByScopeAndType finished")
		}
	}()
	return _d._base.GetByScopeAndType(ctx, scope, wType)
}

// GetByUUID implements warning.WarningService.
func (_d WarningServiceWithSlog) GetByUUID(ctx context.Context, id uuid.UUID) (warning1 *warning.Warning, err error) {
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.Any("id", id),
		)
	}
	log.DebugContext(ctx, "=> calling GetByUUID")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("warning1", warning1),
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			if _d._isInformativeErrFunc(err) {
				log.DebugContext(ctx, "<= method GetByUUID returned an informative error")
			} else {
				log.ErrorContext(ctx, "<= method GetByUUID returned an error")
			}
		} else {
			log.DebugContext(ctx, "<= method GetByUUID finished")
		}
	}()
	return _d._base.GetByUUID(ctx, id)
}

// RemoveStale implements warning.WarningService.
func (_d WarningServiceWithSlog) RemoveStale(ctx context.Context, scope api.WarningScope, newWarnings warning.Warnings) {
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.Any("scope", scope),
			slog.Any("newWarnings", newWarnings),
		)
	}
	log.DebugContext(ctx, "=> calling RemoveStale")
	defer func() {
		log := slog.With()
		log.DebugContext(ctx, "<= method RemoveStale finished")
	}()
	_d._base.RemoveStale(ctx, scope, newWarnings)
}

// UpdateStatusByUUID implements warning.WarningService.
func (_d WarningServiceWithSlog) UpdateStatusByUUID(ctx context.Context, id uuid.UUID, status api.WarningStatus) (warning1 *warning.Warning, err error) {
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.Any("id", id),
			slog.Any("status", status),
		)
	}
	log.DebugContext(ctx, "=> calling UpdateStatusByUUID")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("warning1", warning1),
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			if _d._isInformativeErrFunc(err) {
				log.DebugContext(ctx, "<= method UpdateStatusByUUID returned an informative error")
			} else {
				log.ErrorContext(ctx, "<= method UpdateStatusByUUID returned an error")
			}
		} else {
			log.DebugContext(ctx, "<= method UpdateStatusByUUID finished")
		}
	}()
	return _d._base.UpdateStatusByUUID(ctx, id, status)
}
