// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery

package mock

import (
	"context"
	"sync"

	"github.com/FuturFusion/operations-center/internal/provisioning"
)

// Ensure, that ClusterServiceMock does implement provisioning.ClusterService.
// If this is not the case, regenerate this file with moq.
var _ provisioning.ClusterService = &ClusterServiceMock{}

// ClusterServiceMock is a mock implementation of provisioning.ClusterService.
//
//	func TestSomethingThatUsesClusterService(t *testing.T) {
//
//		// make and configure a mocked provisioning.ClusterService
//		mockedClusterService := &ClusterServiceMock{
//			CreateFunc: func(ctx context.Context, cluster provisioning.Cluster) (provisioning.Cluster, error) {
//				panic("mock out the Create method")
//			},
//			DeleteByNameFunc: func(ctx context.Context, name string) error {
//				panic("mock out the DeleteByName method")
//			},
//			GetAllFunc: func(ctx context.Context) (provisioning.Clusters, error) {
//				panic("mock out the GetAll method")
//			},
//			GetAllNamesFunc: func(ctx context.Context) ([]string, error) {
//				panic("mock out the GetAllNames method")
//			},
//			GetByIDFunc: func(ctx context.Context, id int) (provisioning.Cluster, error) {
//				panic("mock out the GetByID method")
//			},
//			GetByNameFunc: func(ctx context.Context, name string) (provisioning.Cluster, error) {
//				panic("mock out the GetByName method")
//			},
//			RenameByNameFunc: func(ctx context.Context, name string, cluster provisioning.Cluster) (provisioning.Cluster, error) {
//				panic("mock out the RenameByName method")
//			},
//			ResyncInventoryByNameFunc: func(ctx context.Context, name string) error {
//				panic("mock out the ResyncInventoryByName method")
//			},
//			UpdateByNameFunc: func(ctx context.Context, name string, cluster provisioning.Cluster) (provisioning.Cluster, error) {
//				panic("mock out the UpdateByName method")
//			},
//		}
//
//		// use mockedClusterService in code that requires provisioning.ClusterService
//		// and then make assertions.
//
//	}
type ClusterServiceMock struct {
	// CreateFunc mocks the Create method.
	CreateFunc func(ctx context.Context, cluster provisioning.Cluster) (provisioning.Cluster, error)

	// DeleteByNameFunc mocks the DeleteByName method.
	DeleteByNameFunc func(ctx context.Context, name string) error

	// GetAllFunc mocks the GetAll method.
	GetAllFunc func(ctx context.Context) (provisioning.Clusters, error)

	// GetAllNamesFunc mocks the GetAllNames method.
	GetAllNamesFunc func(ctx context.Context) ([]string, error)

	// GetByIDFunc mocks the GetByID method.
	GetByIDFunc func(ctx context.Context, id int) (provisioning.Cluster, error)

	// GetByNameFunc mocks the GetByName method.
	GetByNameFunc func(ctx context.Context, name string) (provisioning.Cluster, error)

	// RenameByNameFunc mocks the RenameByName method.
	RenameByNameFunc func(ctx context.Context, name string, cluster provisioning.Cluster) (provisioning.Cluster, error)

	// ResyncInventoryByNameFunc mocks the ResyncInventoryByName method.
	ResyncInventoryByNameFunc func(ctx context.Context, name string) error

	// UpdateByNameFunc mocks the UpdateByName method.
	UpdateByNameFunc func(ctx context.Context, name string, cluster provisioning.Cluster) (provisioning.Cluster, error)

	// calls tracks calls to the methods.
	calls struct {
		// Create holds details about calls to the Create method.
		Create []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Cluster is the cluster argument value.
			Cluster provisioning.Cluster
		}
		// DeleteByName holds details about calls to the DeleteByName method.
		DeleteByName []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Name is the name argument value.
			Name string
		}
		// GetAll holds details about calls to the GetAll method.
		GetAll []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// GetAllNames holds details about calls to the GetAllNames method.
		GetAllNames []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// GetByID holds details about calls to the GetByID method.
		GetByID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID int
		}
		// GetByName holds details about calls to the GetByName method.
		GetByName []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Name is the name argument value.
			Name string
		}
		// RenameByName holds details about calls to the RenameByName method.
		RenameByName []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Name is the name argument value.
			Name string
			// Cluster is the cluster argument value.
			Cluster provisioning.Cluster
		}
		// ResyncInventoryByName holds details about calls to the ResyncInventoryByName method.
		ResyncInventoryByName []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Name is the name argument value.
			Name string
		}
		// UpdateByName holds details about calls to the UpdateByName method.
		UpdateByName []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Name is the name argument value.
			Name string
			// Cluster is the cluster argument value.
			Cluster provisioning.Cluster
		}
	}
	lockCreate                sync.RWMutex
	lockDeleteByName          sync.RWMutex
	lockGetAll                sync.RWMutex
	lockGetAllNames           sync.RWMutex
	lockGetByID               sync.RWMutex
	lockGetByName             sync.RWMutex
	lockRenameByName          sync.RWMutex
	lockResyncInventoryByName sync.RWMutex
	lockUpdateByName          sync.RWMutex
}

// Create calls CreateFunc.
func (mock *ClusterServiceMock) Create(ctx context.Context, cluster provisioning.Cluster) (provisioning.Cluster, error) {
	if mock.CreateFunc == nil {
		panic("ClusterServiceMock.CreateFunc: method is nil but ClusterService.Create was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Cluster provisioning.Cluster
	}{
		Ctx:     ctx,
		Cluster: cluster,
	}
	mock.lockCreate.Lock()
	mock.calls.Create = append(mock.calls.Create, callInfo)
	mock.lockCreate.Unlock()
	return mock.CreateFunc(ctx, cluster)
}

// CreateCalls gets all the calls that were made to Create.
// Check the length with:
//
//	len(mockedClusterService.CreateCalls())
func (mock *ClusterServiceMock) CreateCalls() []struct {
	Ctx     context.Context
	Cluster provisioning.Cluster
} {
	var calls []struct {
		Ctx     context.Context
		Cluster provisioning.Cluster
	}
	mock.lockCreate.RLock()
	calls = mock.calls.Create
	mock.lockCreate.RUnlock()
	return calls
}

// DeleteByName calls DeleteByNameFunc.
func (mock *ClusterServiceMock) DeleteByName(ctx context.Context, name string) error {
	if mock.DeleteByNameFunc == nil {
		panic("ClusterServiceMock.DeleteByNameFunc: method is nil but ClusterService.DeleteByName was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Name string
	}{
		Ctx:  ctx,
		Name: name,
	}
	mock.lockDeleteByName.Lock()
	mock.calls.DeleteByName = append(mock.calls.DeleteByName, callInfo)
	mock.lockDeleteByName.Unlock()
	return mock.DeleteByNameFunc(ctx, name)
}

// DeleteByNameCalls gets all the calls that were made to DeleteByName.
// Check the length with:
//
//	len(mockedClusterService.DeleteByNameCalls())
func (mock *ClusterServiceMock) DeleteByNameCalls() []struct {
	Ctx  context.Context
	Name string
} {
	var calls []struct {
		Ctx  context.Context
		Name string
	}
	mock.lockDeleteByName.RLock()
	calls = mock.calls.DeleteByName
	mock.lockDeleteByName.RUnlock()
	return calls
}

// GetAll calls GetAllFunc.
func (mock *ClusterServiceMock) GetAll(ctx context.Context) (provisioning.Clusters, error) {
	if mock.GetAllFunc == nil {
		panic("ClusterServiceMock.GetAllFunc: method is nil but ClusterService.GetAll was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockGetAll.Lock()
	mock.calls.GetAll = append(mock.calls.GetAll, callInfo)
	mock.lockGetAll.Unlock()
	return mock.GetAllFunc(ctx)
}

// GetAllCalls gets all the calls that were made to GetAll.
// Check the length with:
//
//	len(mockedClusterService.GetAllCalls())
func (mock *ClusterServiceMock) GetAllCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockGetAll.RLock()
	calls = mock.calls.GetAll
	mock.lockGetAll.RUnlock()
	return calls
}

// GetAllNames calls GetAllNamesFunc.
func (mock *ClusterServiceMock) GetAllNames(ctx context.Context) ([]string, error) {
	if mock.GetAllNamesFunc == nil {
		panic("ClusterServiceMock.GetAllNamesFunc: method is nil but ClusterService.GetAllNames was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockGetAllNames.Lock()
	mock.calls.GetAllNames = append(mock.calls.GetAllNames, callInfo)
	mock.lockGetAllNames.Unlock()
	return mock.GetAllNamesFunc(ctx)
}

// GetAllNamesCalls gets all the calls that were made to GetAllNames.
// Check the length with:
//
//	len(mockedClusterService.GetAllNamesCalls())
func (mock *ClusterServiceMock) GetAllNamesCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockGetAllNames.RLock()
	calls = mock.calls.GetAllNames
	mock.lockGetAllNames.RUnlock()
	return calls
}

// GetByID calls GetByIDFunc.
func (mock *ClusterServiceMock) GetByID(ctx context.Context, id int) (provisioning.Cluster, error) {
	if mock.GetByIDFunc == nil {
		panic("ClusterServiceMock.GetByIDFunc: method is nil but ClusterService.GetByID was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  int
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockGetByID.Lock()
	mock.calls.GetByID = append(mock.calls.GetByID, callInfo)
	mock.lockGetByID.Unlock()
	return mock.GetByIDFunc(ctx, id)
}

// GetByIDCalls gets all the calls that were made to GetByID.
// Check the length with:
//
//	len(mockedClusterService.GetByIDCalls())
func (mock *ClusterServiceMock) GetByIDCalls() []struct {
	Ctx context.Context
	ID  int
} {
	var calls []struct {
		Ctx context.Context
		ID  int
	}
	mock.lockGetByID.RLock()
	calls = mock.calls.GetByID
	mock.lockGetByID.RUnlock()
	return calls
}

// GetByName calls GetByNameFunc.
func (mock *ClusterServiceMock) GetByName(ctx context.Context, name string) (provisioning.Cluster, error) {
	if mock.GetByNameFunc == nil {
		panic("ClusterServiceMock.GetByNameFunc: method is nil but ClusterService.GetByName was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Name string
	}{
		Ctx:  ctx,
		Name: name,
	}
	mock.lockGetByName.Lock()
	mock.calls.GetByName = append(mock.calls.GetByName, callInfo)
	mock.lockGetByName.Unlock()
	return mock.GetByNameFunc(ctx, name)
}

// GetByNameCalls gets all the calls that were made to GetByName.
// Check the length with:
//
//	len(mockedClusterService.GetByNameCalls())
func (mock *ClusterServiceMock) GetByNameCalls() []struct {
	Ctx  context.Context
	Name string
} {
	var calls []struct {
		Ctx  context.Context
		Name string
	}
	mock.lockGetByName.RLock()
	calls = mock.calls.GetByName
	mock.lockGetByName.RUnlock()
	return calls
}

// RenameByName calls RenameByNameFunc.
func (mock *ClusterServiceMock) RenameByName(ctx context.Context, name string, cluster provisioning.Cluster) (provisioning.Cluster, error) {
	if mock.RenameByNameFunc == nil {
		panic("ClusterServiceMock.RenameByNameFunc: method is nil but ClusterService.RenameByName was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Name    string
		Cluster provisioning.Cluster
	}{
		Ctx:     ctx,
		Name:    name,
		Cluster: cluster,
	}
	mock.lockRenameByName.Lock()
	mock.calls.RenameByName = append(mock.calls.RenameByName, callInfo)
	mock.lockRenameByName.Unlock()
	return mock.RenameByNameFunc(ctx, name, cluster)
}

// RenameByNameCalls gets all the calls that were made to RenameByName.
// Check the length with:
//
//	len(mockedClusterService.RenameByNameCalls())
func (mock *ClusterServiceMock) RenameByNameCalls() []struct {
	Ctx     context.Context
	Name    string
	Cluster provisioning.Cluster
} {
	var calls []struct {
		Ctx     context.Context
		Name    string
		Cluster provisioning.Cluster
	}
	mock.lockRenameByName.RLock()
	calls = mock.calls.RenameByName
	mock.lockRenameByName.RUnlock()
	return calls
}

// ResyncInventoryByName calls ResyncInventoryByNameFunc.
func (mock *ClusterServiceMock) ResyncInventoryByName(ctx context.Context, name string) error {
	if mock.ResyncInventoryByNameFunc == nil {
		panic("ClusterServiceMock.ResyncInventoryByNameFunc: method is nil but ClusterService.ResyncInventoryByName was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Name string
	}{
		Ctx:  ctx,
		Name: name,
	}
	mock.lockResyncInventoryByName.Lock()
	mock.calls.ResyncInventoryByName = append(mock.calls.ResyncInventoryByName, callInfo)
	mock.lockResyncInventoryByName.Unlock()
	return mock.ResyncInventoryByNameFunc(ctx, name)
}

// ResyncInventoryByNameCalls gets all the calls that were made to ResyncInventoryByName.
// Check the length with:
//
//	len(mockedClusterService.ResyncInventoryByNameCalls())
func (mock *ClusterServiceMock) ResyncInventoryByNameCalls() []struct {
	Ctx  context.Context
	Name string
} {
	var calls []struct {
		Ctx  context.Context
		Name string
	}
	mock.lockResyncInventoryByName.RLock()
	calls = mock.calls.ResyncInventoryByName
	mock.lockResyncInventoryByName.RUnlock()
	return calls
}

// UpdateByName calls UpdateByNameFunc.
func (mock *ClusterServiceMock) UpdateByName(ctx context.Context, name string, cluster provisioning.Cluster) (provisioning.Cluster, error) {
	if mock.UpdateByNameFunc == nil {
		panic("ClusterServiceMock.UpdateByNameFunc: method is nil but ClusterService.UpdateByName was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Name    string
		Cluster provisioning.Cluster
	}{
		Ctx:     ctx,
		Name:    name,
		Cluster: cluster,
	}
	mock.lockUpdateByName.Lock()
	mock.calls.UpdateByName = append(mock.calls.UpdateByName, callInfo)
	mock.lockUpdateByName.Unlock()
	return mock.UpdateByNameFunc(ctx, name, cluster)
}

// UpdateByNameCalls gets all the calls that were made to UpdateByName.
// Check the length with:
//
//	len(mockedClusterService.UpdateByNameCalls())
func (mock *ClusterServiceMock) UpdateByNameCalls() []struct {
	Ctx     context.Context
	Name    string
	Cluster provisioning.Cluster
} {
	var calls []struct {
		Ctx     context.Context
		Name    string
		Cluster provisioning.Cluster
	}
	mock.lockUpdateByName.RLock()
	calls = mock.calls.UpdateByName
	mock.lockUpdateByName.RUnlock()
	return calls
}
