// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery

package mock

import (
	"context"
	"sync"

	"github.com/FuturFusion/operations-center/internal/provisioning"
)

// Ensure, that InventorySyncerMock does implement provisioning.InventorySyncer.
// If this is not the case, regenerate this file with moq.
var _ provisioning.InventorySyncer = &InventorySyncerMock{}

// InventorySyncerMock is a mock implementation of provisioning.InventorySyncer.
//
//	func TestSomethingThatUsesInventorySyncer(t *testing.T) {
//
//		// make and configure a mocked provisioning.InventorySyncer
//		mockedInventorySyncer := &InventorySyncerMock{
//			SyncClusterFunc: func(ctx context.Context, clusterID int) error {
//				panic("mock out the SyncCluster method")
//			},
//		}
//
//		// use mockedInventorySyncer in code that requires provisioning.InventorySyncer
//		// and then make assertions.
//
//	}
type InventorySyncerMock struct {
	// SyncClusterFunc mocks the SyncCluster method.
	SyncClusterFunc func(ctx context.Context, clusterID int) error

	// calls tracks calls to the methods.
	calls struct {
		// SyncCluster holds details about calls to the SyncCluster method.
		SyncCluster []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ClusterID is the clusterID argument value.
			ClusterID int
		}
	}
	lockSyncCluster sync.RWMutex
}

// SyncCluster calls SyncClusterFunc.
func (mock *InventorySyncerMock) SyncCluster(ctx context.Context, clusterID int) error {
	if mock.SyncClusterFunc == nil {
		panic("InventorySyncerMock.SyncClusterFunc: method is nil but InventorySyncer.SyncCluster was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		ClusterID int
	}{
		Ctx:       ctx,
		ClusterID: clusterID,
	}
	mock.lockSyncCluster.Lock()
	mock.calls.SyncCluster = append(mock.calls.SyncCluster, callInfo)
	mock.lockSyncCluster.Unlock()
	return mock.SyncClusterFunc(ctx, clusterID)
}

// SyncClusterCalls gets all the calls that were made to SyncCluster.
// Check the length with:
//
//	len(mockedInventorySyncer.SyncClusterCalls())
func (mock *InventorySyncerMock) SyncClusterCalls() []struct {
	Ctx       context.Context
	ClusterID int
} {
	var calls []struct {
		Ctx       context.Context
		ClusterID int
	}
	mock.lockSyncCluster.RLock()
	calls = mock.calls.SyncCluster
	mock.lockSyncCluster.RUnlock()
	return calls
}
