// Code generated by generate-inventory; DO NOT EDIT.

package incus_test

import (
	"context"
	"net/http"
	"testing"

	incusapi "github.com/lxc/incus/v6/shared/api"
	"github.com/stretchr/testify/require"

	"github.com/FuturFusion/operations-center/internal/inventory"
	"github.com/FuturFusion/operations-center/internal/provisioning"
	"github.com/FuturFusion/operations-center/internal/testing/queue"
	"github.com/FuturFusion/operations-center/shared/api"
)

func storageBucketClientTestCases(t *testing.T) []methodTestSet {
	return []methodTestSet{
		{
			name: "GetStorageBuckets",
			clientCall: func(ctx context.Context, client inventory.ServerClient, endpoint provisioning.Endpoint) (any, error) {
				return client.GetStorageBuckets(ctx, endpoint, "storage_pool")
			},
			testCases: []methodTestCase{
				{
					name: "success",
					response: []queue.Item[response]{
						{
							Value: response{
								statusCode: http.StatusOK,
								responseBody: mustJSONMarshal(t, api.ResponseRaw{
									Metadata: []incusapi.StorageBucketFull{
										{
											StorageBucket: incusapi.StorageBucket{
												Name:     "storageBucket one",
												Location: "one",
												Project:  "project one",
											},
										},
									},
								}),
							},
						},
					},

					assertErr: require.NoError,
					assertResult: func(t *testing.T, res any) {
						t.Helper()
						require.Len(t, res, 1)
					},
					wantPaths: []string{"GET /1.0/storage-pools/storage_pool/buckets?all-projects=true"},
				},
				{
					name: "error - not found",
					response: []queue.Item[response]{
						{
							Value: response{
								statusCode: http.StatusNotFound,
								responseBody: mustJSONMarshal(t, api.ResponseRaw{
									Type:       api.ErrorResponse,
									StatusCode: http.StatusNotFound,
								},
								),
							},
						},
					},

					assertErr:    require.Error,
					assertResult: noResult,
					wantPaths:    []string{"GET /1.0/storage-pools/storage_pool/buckets?all-projects=true"},
				},
				{
					name: "error - unexpected http status code",
					response: []queue.Item[response]{
						{
							Value: response{
								statusCode: http.StatusInternalServerError,
							},
						},
					},

					assertErr:    require.Error,
					assertResult: noResult,
					wantPaths:    []string{"GET /1.0/storage-pools/storage_pool/buckets?all-projects=true"},
				},
			},
		},

		{
			name: "GetStorageBucketByName",
			clientCall: func(ctx context.Context, client inventory.ServerClient, endpoint provisioning.Endpoint) (any, error) {
				return client.GetStorageBucketByName(ctx, endpoint, "project", "storage_pool", "name")
			},
			testCases: []methodTestCase{
				{
					name: "success",
					response: []queue.Item[response]{
						{
							Value: response{
								statusCode: http.StatusOK,
								responseBody: mustJSONMarshal(t, api.ResponseRaw{
									Metadata: incusapi.StorageBucketFull{
										StorageBucket: incusapi.StorageBucket{
											Name:     "storageBucket one",
											Location: "one",
											Project:  "project one",
										},
									},
								}),
							},
						},
					},

					assertErr: require.NoError,
					assertResult: func(t *testing.T, res any) {
						t.Helper()

						wantStorageBucket := incusapi.StorageBucketFull{
							StorageBucket: incusapi.StorageBucket{
								Name:     "storageBucket one",
								Location: "one",
								Project:  "project one",
							},
						}

						require.Equal(t, wantStorageBucket, res)
					},
					wantPaths: []string{"GET /1.0/storage-pools/storage_pool/buckets/name?project=project"},
				},
				{
					name: "error - unexpected http status code",
					response: []queue.Item[response]{
						{
							Value: response{
								statusCode: http.StatusInternalServerError,
							},
						},
					},

					assertErr:    require.Error,
					assertResult: noResult,
					wantPaths:    []string{"GET /1.0/storage-pools/storage_pool/buckets/name?project=project"},
				},
				{
					name: "error - not found",
					response: []queue.Item[response]{
						{
							Value: response{
								statusCode: http.StatusNotFound,
								responseBody: mustJSONMarshal(t, api.ResponseRaw{
									Type:   api.ErrorResponse,
									Status: http.StatusText(http.StatusNotFound),
								}),
							},
						},
					},

					assertErr:    require.Error,
					assertResult: noResult,
					wantPaths:    []string{"GET /1.0/storage-pools/storage_pool/buckets/name?project=project"},
				},
			},
		},
	}
}
