// Code generated by generate-inventory; DO NOT EDIT.

package incus_test

import (
	"context"
	"net/http"
	"testing"

	incusapi "github.com/lxc/incus/v6/shared/api"
	"github.com/stretchr/testify/require"

	"github.com/FuturFusion/operations-center/internal/inventory"
	"github.com/FuturFusion/operations-center/internal/provisioning"
	"github.com/FuturFusion/operations-center/internal/util/testing/queue"
	"github.com/FuturFusion/operations-center/shared/api"
)

func storagePoolClientTestCases(t *testing.T) []methodTestSet {
	return []methodTestSet{
		{
			name: "GetStoragePools",
			clientCall: func(ctx context.Context, client inventory.ServerClient, endpoint provisioning.Endpoint) (any, error) {
				return client.GetStoragePools(ctx, endpoint)
			},
			testCases: []methodTestCase{
				{
					name: "success",
					response: []queue.Item[response]{
						{
							Value: response{
								statusCode: http.StatusOK,
								responseBody: mustJSONMarshal(t, api.ResponseRaw{
									Metadata: []incusapi.StoragePool{
										{
											Name: "storagePool one",
										},
									},
								}),
							},
						},
					},

					assertErr: require.NoError,
					assertResult: func(t *testing.T, res any) {
						t.Helper()
						require.Len(t, res, 1)
					},
					wantPaths: []string{"GET /1.0/storage-pools?"},
				},
				{
					name: "error - not found",
					response: []queue.Item[response]{
						{
							Value: response{
								statusCode: http.StatusNotFound,
								responseBody: mustJSONMarshal(t, api.ResponseRaw{
									Type:       api.ErrorResponse,
									StatusCode: http.StatusNotFound,
								},
								),
							},
						},
					},

					assertErr:    require.Error,
					assertResult: noResult,
					wantPaths:    []string{"GET /1.0/storage-pools?"},
				},
				{
					name: "error - unexpected http status code",
					response: []queue.Item[response]{
						{
							Value: response{
								statusCode: http.StatusInternalServerError,
							},
						},
					},

					assertErr:    require.Error,
					assertResult: noResult,
					wantPaths:    []string{"GET /1.0/storage-pools?"},
				},
			},
		},

		{
			name: "GetStoragePoolByName",
			clientCall: func(ctx context.Context, client inventory.ServerClient, endpoint provisioning.Endpoint) (any, error) {
				return client.GetStoragePoolByName(ctx, endpoint, "name")
			},
			testCases: []methodTestCase{
				{
					name: "success",
					response: []queue.Item[response]{
						{
							Value: response{
								statusCode: http.StatusOK,
								responseBody: mustJSONMarshal(t, api.ResponseRaw{
									Metadata: incusapi.StoragePool{
										Name: "storagePool one",
									},
								}),
							},
						},
					},

					assertErr: require.NoError,
					assertResult: func(t *testing.T, res any) {
						t.Helper()

						wantStoragePool := incusapi.StoragePool{
							Name: "storagePool one",
						}

						require.Equal(t, wantStoragePool, res)
					},
					wantPaths: []string{"GET /1.0/storage-pools/name"},
				},
				{
					name: "error - unexpected http status code",
					response: []queue.Item[response]{
						{
							Value: response{
								statusCode: http.StatusInternalServerError,
							},
						},
					},

					assertErr:    require.Error,
					assertResult: noResult,
					wantPaths:    []string{"GET /1.0/storage-pools/name"},
				},
				{
					name: "error - not found",
					response: []queue.Item[response]{
						{
							Value: response{
								statusCode: http.StatusNotFound,
								responseBody: mustJSONMarshal(t, api.ResponseRaw{
									Type:   api.ErrorResponse,
									Status: http.StatusText(http.StatusNotFound),
								}),
							},
						},
					},

					assertErr:    require.Error,
					assertResult: noResult,
					wantPaths:    []string{"GET /1.0/storage-pools/name"},
				},
			},
		},
	}
}
