// Code generated by generate-inventory; DO NOT EDIT.

package incus

import (
	"context"

	incusapi "github.com/lxc/incus/v6/shared/api"
)

func (s serverClient) GetNetworkZones(ctx context.Context, connectionURL string) ([]incusapi.NetworkZone, error) {
	client, err := s.getClient(ctx, connectionURL)
	if err != nil {
		return nil, err
	}

	serverNetworkZones, err := client.GetNetworkZonesAllProjects()
	if err != nil {
		return nil, err
	}

	return serverNetworkZones, nil
}
