// Code generated by generate-inventory; DO NOT EDIT.

package incus

import (
	"context"

	incusapi "github.com/lxc/incus/v6/shared/api"
)

func (s serverClient) GetNetworkLoadBalancers(ctx context.Context, connectionURL string, networkLoadBalancerName string) ([]incusapi.NetworkLoadBalancer, error) {
	client, err := s.getClient(ctx, connectionURL)
	if err != nil {
		return nil, err
	}

	serverNetworkLoadBalancers, err := client.GetNetworkLoadBalancers(networkLoadBalancerName)
	if err != nil {
		return nil, err
	}

	return serverNetworkLoadBalancers, nil
}

func (s serverClient) GetNetworkLoadBalancerByName(ctx context.Context, connectionURL string, networkName string, networkLoadBalancerName string) (incusapi.NetworkLoadBalancer, error) {
	client, err := s.getClient(ctx, connectionURL)
	if err != nil {
		return incusapi.NetworkLoadBalancer{}, err
	}

	serverNetworkLoadBalancer, _, err := client.GetNetworkLoadBalancer(networkName, networkLoadBalancerName)
	if err != nil {
		return incusapi.NetworkLoadBalancer{}, err
	}

	return *serverNetworkLoadBalancer, nil
}
