// Code generated by generate-inventory; DO NOT EDIT.

package incus

import (
	"context"

	incusapi "github.com/lxc/incus/v6/shared/api"
)

func (s serverClient) GetProjects(ctx context.Context, connectionURL string) ([]incusapi.Project, error) {
	client, err := s.getClient(ctx, connectionURL)
	if err != nil {
		return nil, err
	}

	serverProjects, err := client.GetProjects()
	if err != nil {
		return nil, err
	}

	return serverProjects, nil
}
