// Code generated by mockery. DO NOT EDIT.
// template: github.com/FuturFusion/operations-center/internal/metrics/prometheus.gotmpl

package middleware

import (
	"context"
	"io"
	"time"

	"github.com/FuturFusion/operations-center/internal/provisioning"
	"github.com/prometheus/client_golang/prometheus"
	"github.com/prometheus/client_golang/prometheus/promauto"
)

// ClusterArtifactRepoWithPrometheus implements provisioning.ClusterArtifactRepo interface with all methods wrapped
// with Prometheus metrics.
type ClusterArtifactRepoWithPrometheus struct {
	base         provisioning.ClusterArtifactRepo
	instanceName string
}

var clusterArtifactRepoDurationSummaryVec = promauto.NewSummaryVec(
	prometheus.SummaryOpts{
		Name:       "cluster_artifact_repo_duration_seconds",
		Help:       "clusterArtifactRepo runtime duration and result",
		MaxAge:     time.Minute,
		Objectives: map[float64]float64{0.5: 0.05, 0.9: 0.01, 0.99: 0.001},
	},
	[]string{"instance_name", "method", "result"},
)

// NewClusterArtifactRepoWithPrometheus returns an instance of the provisioning.ClusterArtifactRepo decorated with prometheus summary metric.
func NewClusterArtifactRepoWithPrometheus(base provisioning.ClusterArtifactRepo, instanceName string) ClusterArtifactRepoWithPrometheus {
	return ClusterArtifactRepoWithPrometheus{
		base:         base,
		instanceName: instanceName,
	}
}

// CreateClusterArtifactFromPath implements provisioning.ClusterArtifactRepo.
func (_d ClusterArtifactRepoWithPrometheus) CreateClusterArtifactFromPath(ctx context.Context, artifact provisioning.ClusterArtifact, path string, ignoredFiles []string) (n int64, err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		clusterArtifactRepoDurationSummaryVec.WithLabelValues(_d.instanceName, "CreateClusterArtifactFromPath", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.CreateClusterArtifactFromPath(ctx, artifact, path, ignoredFiles)
}

// GetClusterArtifactAll implements provisioning.ClusterArtifactRepo.
func (_d ClusterArtifactRepoWithPrometheus) GetClusterArtifactAll(ctx context.Context, clusterName string) (clusterArtifacts provisioning.ClusterArtifacts, err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		clusterArtifactRepoDurationSummaryVec.WithLabelValues(_d.instanceName, "GetClusterArtifactAll", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.GetClusterArtifactAll(ctx, clusterName)
}

// GetClusterArtifactAllNames implements provisioning.ClusterArtifactRepo.
func (_d ClusterArtifactRepoWithPrometheus) GetClusterArtifactAllNames(ctx context.Context, clusterName string) (strings []string, err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		clusterArtifactRepoDurationSummaryVec.WithLabelValues(_d.instanceName, "GetClusterArtifactAllNames", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.GetClusterArtifactAllNames(ctx, clusterName)
}

// GetClusterArtifactArchiveByName implements provisioning.ClusterArtifactRepo.
func (_d ClusterArtifactRepoWithPrometheus) GetClusterArtifactArchiveByName(ctx context.Context, clusterName string, artifactName string, archiveType provisioning.ClusterArtifactArchiveType) (readCloser io.ReadCloser, size int, err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		clusterArtifactRepoDurationSummaryVec.WithLabelValues(_d.instanceName, "GetClusterArtifactArchiveByName", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.GetClusterArtifactArchiveByName(ctx, clusterName, artifactName, archiveType)
}

// GetClusterArtifactByName implements provisioning.ClusterArtifactRepo.
func (_d ClusterArtifactRepoWithPrometheus) GetClusterArtifactByName(ctx context.Context, clusterName string, artifactName string) (clusterArtifact *provisioning.ClusterArtifact, err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		clusterArtifactRepoDurationSummaryVec.WithLabelValues(_d.instanceName, "GetClusterArtifactByName", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.GetClusterArtifactByName(ctx, clusterName, artifactName)
}
