// Code generated by mockery. DO NOT EDIT.
// template: github.com/FuturFusion/operations-center/internal/util/logger/slog.gotmpl

package middleware

import (
	"context"
	"log/slog"

	"github.com/FuturFusion/operations-center/internal/provisioning"
	"github.com/FuturFusion/operations-center/internal/util/logger"
	"github.com/FuturFusion/operations-center/shared/api"
)

// componentClusterTemplateService identifies the log records of this decorator and allows the
// log level to be configured for it individually.
var componentClusterTemplateService = logger.RegisterComponent("provisioning.cluster_template_service")

// ClusterTemplateServiceWithSlog implements provisioning.ClusterTemplateService that is instrumented with slog logger.
type ClusterTemplateServiceWithSlog struct {
	_base      provisioning.ClusterTemplateService
	_component logger.Component
}

type ClusterTemplateServiceWithSlogOption func(s *ClusterTemplateServiceWithSlog)

// ClusterTemplateServiceWithSlogWithComponent overrides the component this instance is
// attributed to. Use it to tell several instances of the same interface apart,
// e.g. the individual members of a chain.
func ClusterTemplateServiceWithSlogWithComponent(component logger.Component) ClusterTemplateServiceWithSlogOption {
	return func(_base *ClusterTemplateServiceWithSlog) {
		_base._component = component
	}
}

// NewClusterTemplateServiceWithSlog instruments an implementation of the provisioning.ClusterTemplateService with simple logging.
func NewClusterTemplateServiceWithSlog(base provisioning.ClusterTemplateService, opts ...ClusterTemplateServiceWithSlogOption) ClusterTemplateServiceWithSlog {
	this := ClusterTemplateServiceWithSlog{
		_base:      base,
		_component: componentClusterTemplateService,
	}

	for _, opt := range opts {
		opt(&this)
	}

	return this
}

// Apply implements provisioning.ClusterTemplateService.
func (_d ClusterTemplateServiceWithSlog) Apply(ctx context.Context, name string, templateVariables api.ConfigMap) (servicesConfig map[string]any, applicationSeedConfig map[string]any, err error) {
	ctx = logger.ContextWithComponent(ctx, _d._component)
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.String("name", name),
			slog.Any("templateVariables", templateVariables),
		)
	}
	log.DebugContext(ctx, "=> calling Apply")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("servicesConfig", servicesConfig),
				slog.Any("applicationSeedConfig", applicationSeedConfig),
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			log.DebugContext(ctx, "<= method Apply returned an error")
		} else {
			log.DebugContext(ctx, "<= method Apply finished")
		}
	}()
	return _d._base.Apply(ctx, name, templateVariables)
}

// Create implements provisioning.ClusterTemplateService.
func (_d ClusterTemplateServiceWithSlog) Create(ctx context.Context, clusterTemplate provisioning.ClusterTemplate) (clusterTemplate1 provisioning.ClusterTemplate, err error) {
	ctx = logger.ContextWithComponent(ctx, _d._component)
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.Any("clusterTemplate", clusterTemplate),
		)
	}
	log.DebugContext(ctx, "=> calling Create")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("clusterTemplate1", clusterTemplate1),
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			log.DebugContext(ctx, "<= method Create returned an error")
		} else {
			log.DebugContext(ctx, "<= method Create finished")
		}
	}()
	return _d._base.Create(ctx, clusterTemplate)
}

// DeleteByName implements provisioning.ClusterTemplateService.
func (_d ClusterTemplateServiceWithSlog) DeleteByName(ctx context.Context, name string) (err error) {
	ctx = logger.ContextWithComponent(ctx, _d._component)
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.String("name", name),
		)
	}
	log.DebugContext(ctx, "=> calling DeleteByName")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			log.DebugContext(ctx, "<= method DeleteByName returned an error")
		} else {
			log.DebugContext(ctx, "<= method DeleteByName finished")
		}
	}()
	return _d._base.DeleteByName(ctx, name)
}

// GetAll implements provisioning.ClusterTemplateService.
func (_d ClusterTemplateServiceWithSlog) GetAll(ctx context.Context) (clusterTemplates provisioning.ClusterTemplates, err error) {
	ctx = logger.ContextWithComponent(ctx, _d._component)
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
		)
	}
	log.DebugContext(ctx, "=> calling GetAll")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("clusterTemplates", clusterTemplates),
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			log.DebugContext(ctx, "<= method GetAll returned an error")
		} else {
			log.DebugContext(ctx, "<= method GetAll finished")
		}
	}()
	return _d._base.GetAll(ctx)
}

// GetAllNames implements provisioning.ClusterTemplateService.
func (_d ClusterTemplateServiceWithSlog) GetAllNames(ctx context.Context) (strings []string, err error) {
	ctx = logger.ContextWithComponent(ctx, _d._component)
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
		)
	}
	log.DebugContext(ctx, "=> calling GetAllNames")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("strings", strings),
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			log.DebugContext(ctx, "<= method GetAllNames returned an error")
		} else {
			log.DebugContext(ctx, "<= method GetAllNames finished")
		}
	}()
	return _d._base.GetAllNames(ctx)
}

// GetByName implements provisioning.ClusterTemplateService.
func (_d ClusterTemplateServiceWithSlog) GetByName(ctx context.Context, name string) (clusterTemplate *provisioning.ClusterTemplate, err error) {
	ctx = logger.ContextWithComponent(ctx, _d._component)
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.String("name", name),
		)
	}
	log.DebugContext(ctx, "=> calling GetByName")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("clusterTemplate", clusterTemplate),
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			log.DebugContext(ctx, "<= method GetByName returned an error")
		} else {
			log.DebugContext(ctx, "<= method GetByName finished")
		}
	}()
	return _d._base.GetByName(ctx, name)
}

// Rename implements provisioning.ClusterTemplateService.
func (_d ClusterTemplateServiceWithSlog) Rename(ctx context.Context, oldName string, newName string) (err error) {
	ctx = logger.ContextWithComponent(ctx, _d._component)
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.String("oldName", oldName),
			slog.String("newName", newName),
		)
	}
	log.DebugContext(ctx, "=> calling Rename")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			log.DebugContext(ctx, "<= method Rename returned an error")
		} else {
			log.DebugContext(ctx, "<= method Rename finished")
		}
	}()
	return _d._base.Rename(ctx, oldName, newName)
}

// Update implements provisioning.ClusterTemplateService.
func (_d ClusterTemplateServiceWithSlog) Update(ctx context.Context, clusterTemplate provisioning.ClusterTemplate) (err error) {
	ctx = logger.ContextWithComponent(ctx, _d._component)
	log := slog.With()
	if slog.Default().Enabled(ctx, logger.LevelTrace) {
		log = log.With(
			slog.Any("ctx", ctx),
			slog.Any("clusterTemplate", clusterTemplate),
		)
	}
	log.DebugContext(ctx, "=> calling Update")
	defer func() {
		log := slog.With()
		if slog.Default().Enabled(ctx, logger.LevelTrace) {
			log = slog.With(
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = slog.With("err", err)
			}
		}
		if err != nil {
			log.DebugContext(ctx, "<= method Update returned an error")
		} else {
			log.DebugContext(ctx, "<= method Update finished")
		}
	}()
	return _d._base.Update(ctx, clusterTemplate)
}
