// Code generated by mockery. DO NOT EDIT.
// template: github.com/FuturFusion/operations-center/internal/logger/slog.gotmpl

package middleware

import (
	"context"
	"log/slog"

	"github.com/FuturFusion/operations-center/internal/logger"
	"github.com/FuturFusion/operations-center/internal/provisioning"
)

// ServerServiceWithSlog implements provisioning.ServerService that is instrumented with slog logger.
type ServerServiceWithSlog struct {
	_log  *slog.Logger
	_base provisioning.ServerService
}

// NewServerServiceWithSlog instruments an implementation of the provisioning.ServerService with simple logging.
func NewServerServiceWithSlog(base provisioning.ServerService, log *slog.Logger) ServerServiceWithSlog {
	return ServerServiceWithSlog{
		_base: base,
		_log:  log,
	}
}

// Create implements provisioning.ServerService.
func (_d ServerServiceWithSlog) Create(ctx context.Context, server provisioning.Server) (server1 provisioning.Server, err error) {
	log := _d._log.With()
	if _d._log.Enabled(ctx, logger.LevelTrace) {
		log.With(
			slog.Any("ctx", ctx),
			slog.Any("server", server),
		)
	}
	log.Debug("ServerServiceWithSlog: calling Create")
	defer func() {
		log := _d._log.With()
		if _d._log.Enabled(ctx, logger.LevelTrace) {
			log = _d._log.With(
				slog.Any("server1", server1),
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = _d._log.With("err", err)
			}
		}
		if err != nil {
			log.Error("ServerServiceWithSlog: method Create returned an error")
		} else {
			log.Debug("ServerServiceWithSlog: method Create finished")
		}
	}()
	return _d._base.Create(ctx, server)
}

// DeleteByName implements provisioning.ServerService.
func (_d ServerServiceWithSlog) DeleteByName(ctx context.Context, name string) (err error) {
	log := _d._log.With()
	if _d._log.Enabled(ctx, logger.LevelTrace) {
		log.With(
			slog.Any("ctx", ctx),
			slog.String("name", name),
		)
	}
	log.Debug("ServerServiceWithSlog: calling DeleteByName")
	defer func() {
		log := _d._log.With()
		if _d._log.Enabled(ctx, logger.LevelTrace) {
			log = _d._log.With(
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = _d._log.With("err", err)
			}
		}
		if err != nil {
			log.Error("ServerServiceWithSlog: method DeleteByName returned an error")
		} else {
			log.Debug("ServerServiceWithSlog: method DeleteByName finished")
		}
	}()
	return _d._base.DeleteByName(ctx, name)
}

// GetAll implements provisioning.ServerService.
func (_d ServerServiceWithSlog) GetAll(ctx context.Context) (servers provisioning.Servers, err error) {
	log := _d._log.With()
	if _d._log.Enabled(ctx, logger.LevelTrace) {
		log.With(
			slog.Any("ctx", ctx),
		)
	}
	log.Debug("ServerServiceWithSlog: calling GetAll")
	defer func() {
		log := _d._log.With()
		if _d._log.Enabled(ctx, logger.LevelTrace) {
			log = _d._log.With(
				slog.Any("servers", servers),
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = _d._log.With("err", err)
			}
		}
		if err != nil {
			log.Error("ServerServiceWithSlog: method GetAll returned an error")
		} else {
			log.Debug("ServerServiceWithSlog: method GetAll finished")
		}
	}()
	return _d._base.GetAll(ctx)
}

// GetAllByClusterID implements provisioning.ServerService.
func (_d ServerServiceWithSlog) GetAllByClusterID(ctx context.Context, clusterID int) (servers provisioning.Servers, err error) {
	log := _d._log.With()
	if _d._log.Enabled(ctx, logger.LevelTrace) {
		log.With(
			slog.Any("ctx", ctx),
			slog.Int("clusterID", clusterID),
		)
	}
	log.Debug("ServerServiceWithSlog: calling GetAllByClusterID")
	defer func() {
		log := _d._log.With()
		if _d._log.Enabled(ctx, logger.LevelTrace) {
			log = _d._log.With(
				slog.Any("servers", servers),
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = _d._log.With("err", err)
			}
		}
		if err != nil {
			log.Error("ServerServiceWithSlog: method GetAllByClusterID returned an error")
		} else {
			log.Debug("ServerServiceWithSlog: method GetAllByClusterID finished")
		}
	}()
	return _d._base.GetAllByClusterID(ctx, clusterID)
}

// GetAllNames implements provisioning.ServerService.
func (_d ServerServiceWithSlog) GetAllNames(ctx context.Context) (strings []string, err error) {
	log := _d._log.With()
	if _d._log.Enabled(ctx, logger.LevelTrace) {
		log.With(
			slog.Any("ctx", ctx),
		)
	}
	log.Debug("ServerServiceWithSlog: calling GetAllNames")
	defer func() {
		log := _d._log.With()
		if _d._log.Enabled(ctx, logger.LevelTrace) {
			log = _d._log.With(
				slog.Any("strings", strings),
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = _d._log.With("err", err)
			}
		}
		if err != nil {
			log.Error("ServerServiceWithSlog: method GetAllNames returned an error")
		} else {
			log.Debug("ServerServiceWithSlog: method GetAllNames finished")
		}
	}()
	return _d._base.GetAllNames(ctx)
}

// GetByName implements provisioning.ServerService.
func (_d ServerServiceWithSlog) GetByName(ctx context.Context, name string) (server provisioning.Server, err error) {
	log := _d._log.With()
	if _d._log.Enabled(ctx, logger.LevelTrace) {
		log.With(
			slog.Any("ctx", ctx),
			slog.String("name", name),
		)
	}
	log.Debug("ServerServiceWithSlog: calling GetByName")
	defer func() {
		log := _d._log.With()
		if _d._log.Enabled(ctx, logger.LevelTrace) {
			log = _d._log.With(
				slog.Any("server", server),
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = _d._log.With("err", err)
			}
		}
		if err != nil {
			log.Error("ServerServiceWithSlog: method GetByName returned an error")
		} else {
			log.Debug("ServerServiceWithSlog: method GetByName finished")
		}
	}()
	return _d._base.GetByName(ctx, name)
}

// RenameByName implements provisioning.ServerService.
func (_d ServerServiceWithSlog) RenameByName(ctx context.Context, name string, server provisioning.Server) (server1 provisioning.Server, err error) {
	log := _d._log.With()
	if _d._log.Enabled(ctx, logger.LevelTrace) {
		log.With(
			slog.Any("ctx", ctx),
			slog.String("name", name),
			slog.Any("server", server),
		)
	}
	log.Debug("ServerServiceWithSlog: calling RenameByName")
	defer func() {
		log := _d._log.With()
		if _d._log.Enabled(ctx, logger.LevelTrace) {
			log = _d._log.With(
				slog.Any("server1", server1),
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = _d._log.With("err", err)
			}
		}
		if err != nil {
			log.Error("ServerServiceWithSlog: method RenameByName returned an error")
		} else {
			log.Debug("ServerServiceWithSlog: method RenameByName finished")
		}
	}()
	return _d._base.RenameByName(ctx, name, server)
}

// UpdateByName implements provisioning.ServerService.
func (_d ServerServiceWithSlog) UpdateByName(ctx context.Context, name string, server provisioning.Server) (server1 provisioning.Server, err error) {
	log := _d._log.With()
	if _d._log.Enabled(ctx, logger.LevelTrace) {
		log.With(
			slog.Any("ctx", ctx),
			slog.String("name", name),
			slog.Any("server", server),
		)
	}
	log.Debug("ServerServiceWithSlog: calling UpdateByName")
	defer func() {
		log := _d._log.With()
		if _d._log.Enabled(ctx, logger.LevelTrace) {
			log = _d._log.With(
				slog.Any("server1", server1),
				slog.Any("err", err),
			)
		} else {
			if err != nil {
				log = _d._log.With("err", err)
			}
		}
		if err != nil {
			log.Error("ServerServiceWithSlog: method UpdateByName returned an error")
		} else {
			log.Debug("ServerServiceWithSlog: method UpdateByName finished")
		}
	}()
	return _d._base.UpdateByName(ctx, name, server)
}
