---

name: Vulnerability Check
on:
  schedule:
    - # Run at 07:00 UTC every Monday
      cron: "0 7 * * 1"

jobs:
  govulncheck:
    name: Run govulncheck
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: govulncheck
        uses: golang/govulncheck-action@v1
        with:
           go-version-input: stable
